### ISSUE TITLE
Linux: Hero portrait not shown in "Your last match" widget

### ISSUE THREAD

**Issue by tilman2** [ValveSoftware/Dota-2#491] opened 2015-09-26 08:28 UTC
A recent patch introduced a widget in the main UI that shows information about "Your last match". It includes a rectangle on the left hand side that supposedly shows the portrait of the hero that you played.

On my Linux system, the portrait isn't shown (said rectangle empty). This is with an Radeon Bonaire graphics card and the free Radeon driver (ie, Mesa).

Relevant part of my glxinfo output:

OpenGL renderer string: Gallium 0.4 on AMD BONAIRE
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.5
OpenGL core profile shading language version string: 3.30

**Comment by MrTheSoulz** [comment] 2015-09-26 18:00
Comfirmed also for nvidia blob 355.11.
I dont belive this has anything related to drivers whatsoever.

**Comment by Tele42** [comment] 2015-09-26 19:48
Possible duplicate of #54.

**Comment by gdrewb-valve** [comment] 2015-10-12 18:20
Yes, duplicate of #54.

**Closed as completed by gdrewb-valve** 2015-10-12 18:20 UTC
Labels: reviewed
