### ISSUE TITLE
MAC Problem: Dota 2 crashes as soon as I click on Play button

### ISSUE THREAD

**Issue by mwaqarshahid** [ValveSoftware/Dota-2#1377] opened 2018-01-16 21:58 UTC
Today, 16-January-2018, I was playing my game as usual. Suddenly update came and when I updated my game started crashing.

System Information:
macOS Sierra version 10.12.6
MacBook Pro (Retina, 15-inch, Late 2013)
Processor 2 Ghz Intel Core i7
Memory 8 GB 1600 MHz DDR3
Graphics Intel Iris Pro 1536 MB

**Comment by gu3st** [comment] 2018-01-16 21:58
See #1375

**Comment by danginsburg** [comment] 2018-01-16 21:59
Closing as duplicate of #1375.

**Closed as completed by danginsburg** 2018-01-16 21:59 UTC
