### ISSUE TITLE
Uname in dota.sh

### ISSUE THREAD

**Issue by gostapit** [ValveSoftware/Dota-2#2270] opened 2023-03-08 20:51 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/gostapit/59e0fd990fdb772282c16d87d8835f1d): 

#### Please describe your issue in as much detail as possible:
Dota.sh produces errors in lines 13,20 and 114 due to problems with UNAME variable which cannot be properly generated with 

```
UNAMEPATH=`which uname`
if [ -z $UNAMEPATH ]; then
        if [ -f /usr/bin/uname ]; then
                UNAMEPATH=/usr/bin/uname
        elif [ -f /bin/uname ]; then
                UNAMEPATH=/bin/uname
        fi
fi
UNAME=`${UNAMEPATH}`

```

#### Steps for reproducing this issue:

1. Try to run game with **set -x in dota.sh**

```
++ which uname
++ alias
++ eval declare -f
+++ declare -f
++ /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot uname
pid 7193 != 7138, skipping destruction (fork without exec?)
Illegal option --
pid 7192 != 7138, skipping destruction (fork without exec?)
+ UNAMEPATH='Usage: /usr/bin/which [-a] args'
+ '[' -z Usage: /usr/bin/which '[-a]' args ']'
/media/nvme/SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh: line 13: [: too many arguments

```

Setting UNAME to "Linux"
or UNAMEPATH to "/usr/bin/uname"
fixes problem. I am not sure why top of the script produces errors since it looks ok.

**Comment by danginsburg** [comment] 2023-03-08 21:23
Closing as duplicate of #2260

**Closed as completed by danginsburg** 2023-03-08 21:23 UTC
