### ISSUE TITLE
Game crashes when using specific spells.

### ISSUE THREAD

**Issue by ConnahGriffin** [ValveSoftware/Dota-2#2503] opened 2023-09-29 18:26 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/ConnahGriffin/c442d68040f42ce84f8ce5606219ca1d): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Issue:
The game crashes mid game when using some spells under certain conditions while sometimes needing none at all. This however may not be the reason but only the underlying cause. What I've notices to cause a crash so far are:

- Sun ray from phoenix(usually happens when I hit both an ally and an enemy)
- Power cog by clockwork
- Plague wards by venomancer with 25 talent

The crashes started happening after the compendium patch. Far more often after the audio bug fix patch, which it did indeed fix.
A dmesg output right after the crash:
`dota2[115995]: segfault at 38 ip 00007fc2552d13e4 sp 00007fff227d1fa0 error 4 in libclient.so [7fc253ba6000+2f5e000]
Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 63 c7 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6`

#### Steps for reproducing this issue:

I have tried those same spells in demo mode with no luck. But I am certain that my game crashes when those specific spells are being used or are used right before a crash.

**Comment by alexeysvrv** [comment] 2023-09-29 18:53
@kisak-valve @icculus I can confirm this behavior! The game often freezes. You have to kill the process and the responsiveness of the interface drops significantly. Because of this, I was considered abandoned game(((As if all the power of the computer was spent on mining or rendering something. Please fix this. Yesterday the sound disappeared, and today there are freezes. Fix Dota after adding the Compendium!!!

**Comment by kisak-valve** [comment] 2023-09-29 20:13
Hello @ConnahGriffin, this issue is already being tracked at #2499. There's no point in fragmenting the discussion of this issue across multiple issue reports.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2023-09-29 20:13 UTC

**Comment by ConnahGriffin** [comment] 2023-09-29 20:16
> Hello @ConnahGriffin, this issue is already being tracked at #2499. There's no point in fragmenting the discussion of this issue across multiple issue reports.
> 
> Closing as a duplicate.

Apologies. I thought that thread was ignored since the data provided wasn't in a valid manner or something.
