### ISSUE TITLE
i can't enter the game

### ISSUE THREAD

**Issue by cosaryus** [ValveSoftware/Dota-2#519] opened 2015-10-03 10:56 UTC
hey everyone. i was not able to play data 2 for a while. i updated my mac and my dota 2. but when i try to enter a game, it goes to deskop with this error. i can play with bots but not in real game. anyone got same error? or someone just can help me !! ?!
![ekran resmi 2015-10-03 13 49 06 1](https://cloud.githubusercontent.com/assets/14952425/10262565/78ed5356-69d6-11e5-8132-63e2a8be59bc.png)

**Comment by danginsburg** [comment] 2015-10-05 20:55
We have heard of this here too: http://dev.dota2.com/showthread.php?t=179817.  Could you do what is suggested in comment 7 and post here: http://dev.dota2.com/showthread.php?t=179817&p=1277908&viewfull=1#post1277908

**Comment by gdrewb-valve** [comment] 2015-10-12 19:19
Duplicate of #294.  Unfortunately we don't know what causes this for some people.

**Closed as completed by gdrewb-valve** 2015-10-12 19:19 UTC
Labels: reviewed
