### ISSUE TITLE
SCREEN GOT BLACKED IN MAC 

### ISSUE THREAD

**Issue by varito1234** [ValveSoftware/Dota-2#1925] opened 2021-04-19 00:03 UTC
when I put my mouse above someone or a tower my screen got blacked every time I play in Mac and is awful
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 49" src="https://user-images.githubusercontent.com/82777919/115160163-1fdcc500-a097-11eb-8218-f7aaedcc6e26.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 46" src="https://user-images.githubusercontent.com/82777919/115160168-24a17900-a097-11eb-9c49-01d070f7419c.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 51" src="https://user-images.githubusercontent.com/82777919/115160172-279c6980-a097-11eb-866d-5b969d997cc2.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 26 03" src="https://user-images.githubusercontent.com/82777919/115160175-2b2ff080-a097-11eb-8554-a9107d940053.png">

**Comment by kisak-valve** [comment] 2021-04-19 00:07
Hello @varito1234, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328 / #1924.

**Closed as completed by kisak-valve** 2021-04-19 00:07 UTC
