### ISSUE TITLE
[Linux] VERY low fps (Nvidia 8600m GT)

### ISSUE THREAD

**Issue by gipawu** [ValveSoftware/Dota-2#426] opened 2015-09-12 17:06 UTC
Before Reborn patch, I used to play fine with minimal graphic settings with 35-45 fps.
Now fps max to 15-20, and often they go down to 2-5, in main menu too.
I have a T9300 cpu and a Nvidia 8600m GT (with latest working driver 340.93). I know that my specs are low, but as I said I used to play fine before, and it is sad that now the game is really unplayable. And many others with relatively low spec machine are in the same situation. Thank you.

**Comment by TRiedling** [comment] 2015-09-13 19:52
Reborn is unplayable for me too. Before everything worked great.
I have intel core i5.

**Comment by danginsburg** [comment] 2015-09-13 20:46
@gipawu What settings/resolution are you running at?  Can you post full system specs from Steam -> Help -> System Information.  I haven't tested on that specific config, but generally the source 2 performance on NVIDIA GL Linux is better than source 1, so I'm a bit surprised it's so much worse on your machine.

**Comment by gipawu** [comment] 2015-09-13 21:11
Here you are:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2501 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.6-201.fc22.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11702000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce 8600M GT/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 340.93
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x407
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13,03" x 8,15"  (15,35" diag)
                                            33,1cm x 20,7cm  (39,0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 256 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: SigmaTel STAC9228

Memory:
    RAM:  3951 Mb

Miscellaneous:
    UI Language:  English
    LANG:  it_IT.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  40775 Mb
    Largest Free Hard Disk Block:  14652 Mb

Installed software:

Recent Failure Reports:
```

**Comment by TRiedling** [comment] 2015-09-14 22:22
Here my specs:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.5.9
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x682f
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 13,54" x 7,64"  (15,51" diag)
                                        34,4cm x 19,4cm  (39,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  7853 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  366735 Mb
    Largest Free Hard Disk Block:  331329 Mb

Installed software:

Recent Failure Reports:

**Comment by Tele42** [comment] 2015-09-15 00:01
With regards to @gipawu's system specs, this is most likely caused by the 256MB of vram on the video card, with the Source 2 engine, there is a significant increase in vram usage among other things, so I am reasonably confident more of the art assets are getting pushed over to system ram compared to the source 1 version.

@TRiedling, your system does not resemble @gipawu's from a vram perspective or a driver perspective. I think it would be worthwhile to open a separate issue report so that these two performance issues can be tracked separately.

**Comment by TRiedling** [comment] 2015-09-15 05:47
ok. I opened a new fps issue.

**Comment by gipawu** [comment] 2015-09-15 09:49
Thank you for the answer. If the problem is the low amount of ram, is there any way (console command etc.) I can reduce vram usage other that using obviously minimum graphical settings?

**Comment by gipawu** [comment] 2015-09-15 10:12
I also noticed that when I hover the mouse cursor over an hero I have almost always a fps drop.

**Comment by gdrewb-valve** [comment] 2016-12-13 21:25
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.

**Closed as completed by gdrewb-valve** 2016-12-13 21:25 UTC
Labels: reviewed
