### ISSUE TITLE
[Linux] Fullscreen not available

### ISSUE THREAD

**Issue by fasmat** [ValveSoftware/Dota-2#63] opened 2015-06-24 09:03 UTC
I can't play Dota 2 Reborn in full screen. If I select it in the options it will render as border-less window instead (same if I select border-less window).

I didn't have this issue with the old Dota 2 and other Linux games (e.g. Amnesia or CS:GO) also work in full screen.

**Comment by gdrewb-valve** [comment] 2015-06-24 15:44
This is currently the expected behavior as fullscreen causes some undesirable side effects in some situations.

**Comment by fasmat** [comment] 2015-06-24 16:55
I see. So I'll let this ticket open until its reverted again so it does not get reposted?

**Comment by computerquip** [comment] 2015-06-24 17:26
As far as I know, a fullscreen in X is just a borderless window that overlays everything with some hints to the window manager saying it's fullscreen. Im curious as to the differences in implementation.

**Comment by gdrewb-valve** [comment] 2015-06-24 17:47
Exclusive or true fullscreen can change resolutions and cause an actual mode switch (the WM does it based on the hints), whereas a borderless window will not.  A mode switch is a heavy-weight operation with a number of side effects, some of them undesirable.

@fasmat , yes leave this issue open.

**Comment by gdrewb-valve** [comment] 2016-02-25 22:50
After discussion with the SDL devs it doesn't look like the reasons to not offer exclusive fullscreen are going to change.  Are you running into some kind of issue with the current fullscreen support (which will request fullscreen status from the window manger, it's more than just a borderless window)?

**Comment by gdrewb-valve** [comment] 2016-02-29 22:20
Closing pending more information.

**Closed as completed by gdrewb-valve** 2016-02-29 22:20 UTC
Labels: enhancement, reviewed

**Comment by crystaldaking** [comment] 2023-09-11 13:02
any updates for this issue?
