### ISSUE TITLE
[Linux] game close when I try get to menu when play match (after latest patch) 

### ISSUE THREAD

**Issue by Eignar17** [ValveSoftware/Dota-2#567] opened 2015-10-14 07:51 UTC
is my system 

ubuntu 15.04

4 CPUs, Frequency: 3.0 Ghz,  Features: GenuineIntel SSE SSE2 SSE4.1 SSE4.2 AVX MMX

I walk a lot if the palette menu closes

**Comment by GreatBigWhiteWorld** [comment] 2015-10-14 10:59
Mine crashes as soon as I click the "Top spectated game now"

Linux amd64,  It's also after the latest patch.

**Comment by gdrewb-valve** [comment] 2015-10-14 14:01
@Eignar17, are you trying to watch a game as @GreatBigWhiteWorld is?  Watching games has a known crash covered in #561.

**Comment by khill** [comment] 2015-10-14 16:39
Feels like this is the same issue as in #557 - when playing a game and going to the menu, the game freezes.  Sometimes the display un-freezes in 5-30 seconds, sometimes it stays stuck, and other times the display unfreezes and the game is over (including the sound of the radiant or dire ancient being destroyed).

I have the same issue and pasted my specs in the other defect.

Please let me know if you need more info or testing.

Thanks!

**Comment by Gab0** [comment] 2015-10-16 19:09
I was having exactly the same problem, also #567. Now the game says it's out of date even though no automatic update happens. Game cache was checked and is fine.

**Comment by gdrewb-valve** [comment] 2015-10-16 20:37
Does the Oct. 16th update help?

**Comment by gdrewb-valve** [comment] 2015-10-16 23:20
I'm going to close this as a duplicate of #557.

**Comment by Eignar17** [comment] 2015-10-16 23:21
is new update fix

**Closed as completed** 2015-10-16 23:21 UTC
Labels: reviewed
