### ISSUE TITLE
SPRING CLEANING: MAC: replay viewing crash + queueing for game crash

### ISSUE THREAD

**Issue by lifesized** [ValveSoftware/Dota-2#805] opened 2016-03-25 08:19 UTC
Hi Valve devs,

1) Queueing for a game - random draft 
Client crashed as soon as we entered the pre-game process waiting for loaders. 
Result: On restart i had the low-priority message

2) Watching replay
I fast forwarded a little and client crashed. Reopened and fast forwarded and it crashed at the exact same spot. When restarted and forwarded past this event, the game completed the replay. I don't trust that the crash is completely time-stamp related though.

Reported from: 
MacBook Pro (Retina, 15-inch, Late 2013), Yosemite 10.10.4, NVIDIA GeForce GT 750M

**Comment by zanderzhng** [comment] 2016-03-25 11:41
Check temp fix at #794 .

**Comment by danginsburg** [comment] 2016-03-25 13:20
Likely duplicate of #794.  We are working on a fix.

**Comment by danginsburg** [comment] 2016-03-25 14:05
A patch was just pushed to Steam. Would someone that can reproduce the problem without risking an abandon please try running without "-threads 0". If you still see a crash, please provide the following info:
- Crash dump
- Steam -> Help -> System Information
-  Ideally repro instructions if you can repro reliably

**Comment by danginsburg** [comment] 2016-03-25 16:59
We believe this issue has been fixed.

**Closed as completed by danginsburg** 2016-03-25 16:59 UTC
Labels: duplicate, reviewed

**Comment by madtune** [comment] 2016-04-28 17:08
nope bug it's still alive :(
