### ISSUE TITLE
Bug with Arc Warden and Meteor Hammer

### ISSUE THREAD

**Issue by Kalovichok** [ValveSoftware/Dota-2#2306] opened 2023-04-22 10:05 UTC
Arc Warden doesnt work slowing by flux illusion and doesnt work the talent for 40 bonus magical damage from attacks in the illusion field
Meteor Hammer, slowing down doesn't work.

**Comment by jn64** [comment] 2023-04-22 12:24
Duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/8335 and https://github.com/ValveSoftware/Dota2-Gameplay/issues/8334

Report gameplay issues there. This is for client (software) issues.

**Comment by kisak-valve** [comment] 2023-04-22 12:59
Closing as a duplicate.

**Closed as not planned by kisak-valve** 2023-04-22 12:59 UTC
