### ISSUE TITLE
[linux] black screen at startup using xmonad

### ISSUE THREAD

**Issue by quarthex** [ValveSoftware/Dota-2#359] opened 2015-09-03 22:01 UTC
Whole screen stay black.
No sound.
Unable to switch to another virtual desktop.
Application does not end.
Legacy Dota2 works well.

I installed the [libudev0](https://aur.archlinux.org/packages/libudev0/) package, according to the ArchLinux [wiki](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Dependencies_.28Dota_2_reborn.29).

I extracted libpng12.so.0.50.0 from a [Debian package](http://packages.ubuntu.com/trusty/amd64/libpng12-0/download), and put it in $GAMEROOT/bin (where LD_LIBRARY_PATH point to).

I tried debugging it, overriding the GAME_DEBUGGER environment variable (using gdbserver as I needed to use another X session).
A segmentation fault seems to occur in libnvidia-glcore.so.

See [this Gist](https://gist.github.com/quarthex/7ccf6ffa4e85e08c1df5) for more detailed infos.

**Comment by gdrewb-valve** [comment] 2015-09-03 23:07
If the problem is in the NVIDIA driver there may not be much we can do from Valve's side.

**Comment by danginsburg** [comment] 2015-09-04 14:25
I installed the same driver you appear to have (NVIDIA 352.41) from http://www.nvidia.com/Download/driverResults.aspx/90279/en-us on Ubuntu 15.04 x64 with NVIDIA GTX 760 and did not encounter the crash.

Can you try adding -gl_disable_binary_shaders to your command-line and report back if that works?  Could you also post your full system information from Steam -> Help -> System Information?

**Comment by quarthex** [comment] 2015-09-04 16:08
Adding -gl_disable_binary_shaders did not solve the problem.
My system's informations are available in the shared Gist (https://gist.github.com/quarthex/7ccf6ffa4e85e08c1df5#file-sysinfos).
I added memory mapping to it.

**Comment by danginsburg** [comment] 2015-09-04 17:14
Can you upload your minidump somewhere I can grab?  I'll see if I can get a better idea what GL API call is triggering the crash.

**Comment by quarthex** [comment] 2015-09-04 18:23
Uploaded here: http://www.aprogsys.com/owncloud/index.php/s/Jv6vnB8NN2Gcjea

**Comment by quarthex** [comment] 2015-09-13 14:20
When I add the launch option "-sw", the issue does not occurs.
I do not have the problem any more since I switched from XMonad to i3.
Maybe the way the fullscreen setting is handled with XMonad...

**Comment by danginsburg** [comment] 2015-09-14 12:59
I have been able to repro that if you run in fullscreen mode or switch to fullscreen mode in dota2 with xmonad then you get a blackscreen.  Would you be willing to file a bug with xmonad on this issue?  Not sure this is really a problem with Dota 2.

**Comment by danginsburg** [comment] 2015-09-16 00:07
I am going to close this out since it seems to be an issue with xmonad.

**Closed as completed by danginsburg** 2015-09-16 00:07 UTC
Labels: reviewed
