### ISSUE TITLE
Display mode in a window without frame! iMac 27.

### ISSUE THREAD

**Issue by Azazelium** [ValveSoftware/Dota-2#480] opened 2015-09-22 09:40 UTC
When setting the display window without a frame , while playing the cursor jumps to the desktop. Please correct the mistake !

**Comment by danginsburg** [comment] 2015-09-22 12:51
Mouse is captured in borderless window mode once you enter the game, just not in the main menu.  Is that what you are seeing?  If so, this is by design and consistent with the behavior on Windows.

**Comment by danginsburg** [comment] 2015-09-28 20:17
I believe this to be a duplicate of #450 and I have checked in a fix that will be in a future update.  The issue was the same on Linux and OSX.

**Comment by danginsburg** [comment] 2015-09-29 20:32
The fix has been released.  Closing.

**Closed as completed by danginsburg** 2015-09-29 20:32 UTC
Labels: duplicate, reviewed

**Comment by Azazelium** [comment] 2015-10-15 05:21
Thanks you!!!
