### ISSUE TITLE
Units slow motion in single player

### ISSUE THREAD

**Issue by p4u45** [ValveSoftware/Dota-2#1809] opened 2015-07-11 03:25 UTC
Hi. So I've been playing Dota 2 for quite some time now. Usually I play with bots because of my intermittent internet connection. Dota 2 updated today and I was surprised when I tried to play single player and see EVERY UNITS walk/attack in SLOOOWWWWW MOTIONNN! I thought at first that it was just a simple problem and exiting the game would fix it, but it didn't. My hero, my allies, my enemies, roshan, the neutrals, the creeps, the couriers, and even the towers attack are all in slow motion! It even takes ages to activate a skill! For example, I tried using Legion Commander's Duel against an enemy hero, and she can't even hit the enemy hero because it takes so long for her to even do the attack aimation! I don't know what to do. Can anyone please help me? By the way, the game clock is working just fine. :P

P.S.: hehe I forgot to mention, I'm using 2010 iMac Mac OS X 10.7.5 3.2 GHz Intel Core i3 4 GB Memory

**Comment by DeaconFell** [comment] 2015-07-11 03:32
You aren't the only one. We can both rest assured it doesn't seem to be something unique to our systems. What are you running Dota2 on? I'm on 2015 Macbook Air. Hadn't tried playing on it until today... rude surprise to find. I'm sure Valve will fix it.... eventually...

**Comment by abaalkh** [comment] 2015-07-11 04:30
I also have the same problem.
In the console, it displays this error:

`Attack speed is <= 0 in GetAttackSpeed()! Check for uninitialized modifier values or extreme modifier combinations`

The game is unplayable.

**Comment by abaalkh** [comment] 2015-07-11 04:53
I too have this problem.
`Attack speed is <= 0 in GetAttackSpeed()! Check for uninitialized modifier values or extreme modifier combinations`
Is the error you see in the console.

**Comment by esperonr** [comment] 2015-07-11 05:09
Having same problem here. I wish I didn't update it. I even restart my computer, reinstall Dota again. Nothing fixed the issue. Please help

**Comment by ajinkyapisal** [comment] 2015-07-11 06:34
Same problem.  
{code}
extreme modifier combinations.
Attack speed is <= 0 in GetAttackSpeed()! Check for uninitialized modifier values or extreme modifier combinations.
{code}

**Comment by deplorableword** [comment] 2015-07-11 11:39
Same problem in Multiplayer / Local Lobby. Game is broken :(

https://www.reddit.com/r/DotA2/comments/3cwfb0/help_mac_client_running_in_slow_motion/

**Comment by juvenpajares** [comment] 2015-07-11 13:07
same problem. mac user

**Comment by flverhaegen** [comment] 2015-07-11 14:20
Same.  I've reinstalled twice and tried every console command I could think of to fix it, no joy.  Most boring DotA possible, unbearable to play

**Comment by esperonr** [comment] 2015-07-11 16:43
Any news on this? This is frustrating.

**Comment by DeaconFell** [comment] 2015-07-11 17:09
I wouldn't expect anything until next week. I doubt they have a ton of people out there looking to squash bugs on the Mac client on the weekend. :(
Has anyone heard if this is Mac only? Are there any Macs that aren't experiencing it?

**Comment by deplorableword** [comment] 2015-07-11 18:20
It's super annoying that critical bugs like this are missed by QA and left to hang. If this issue appeared on Windows, a patch would have be issued ASAP, instead mac users are left with a broken game.

**Comment by holmes2** [comment] 2015-07-11 18:54
Mac user Mid 2014 2.8 GHz Intel Core i7 16GB RAM experiencing same problem after the July 10th 2015 update....Now the syllabear would require moonshard to attack normally.

**Comment by OSnapz** [comment] 2015-07-11 20:34
Same here at MBP Mid 2014, my friend who is using ASUS don't have any kind of this issue. @DeaconFell I think only macs have this issue.

**Comment by kartikthapar** [comment] 2015-07-11 20:56
Fixed in Source 2? Please fix this among a 100 billion other issues on the mac client.

**Comment by dieva** [comment] 2015-07-12 15:37
same problem, I'm mac user too and i don't know how to fix this problem

**Comment by Isuru-Nanayakkara** [comment] 2015-07-12 18:46
The timing of this issue just couldn't get any worse. I actually started playing Dota 2 two days ago. The next day, this thing happened. >_<

**Comment by deplorableword** [comment] 2015-07-12 22:19
It looks like if you create a Lobby (not a local lobby) you can fill it with bots you can still play at regular speed. That appears to be the only workaround now :/

**Comment by Damdomy** [comment] 2015-07-12 23:15
@deplorableword That's a really weird issue.
I play local lobbies on the go due to bad internet. This needs to be fixed asap.

**Comment by deksden** [comment] 2015-07-13 13:36
Same problem on iMac - game is unplayable! All moves are SLOOOOW. Just after recent patch.

**Comment by mansarip** [comment] 2015-07-13 17:30
same problem here.
Mac OSX Yosemite 10.10.3

Problem occured after recent update (10 July)

**Comment by mansoor090** [comment] 2015-07-13 17:46
facing the same problem . i also play dota on PC - custom made . it is fine over there
using mid 2012 mac i5 4gb ram intel 4000 HD

i guess mac user only facing this issue

**Comment by deplorableword** [comment] 2015-07-14 08:31
paging @gdrewb-valve for help and triage :(

**Comment by gdrewb-valve** [comment] 2015-07-14 17:42
You're running the main Dota 2 client and not Reborn, correct?  I'm checking with that team.

**Comment by DeaconFell** [comment] 2015-07-14 17:45
Yes. In local lobby games in regular client is where I've seen it happen, and as has been said on the thread making a lobby on the game server and filling it with bots worked fine. Thanks for checking into it.

**Comment by davidw-valve** [comment] 2015-07-14 17:52
I have reproduced this and am looking into it. In the meantime note that this bug does not affect the Reborn Beta so you could consider playing bot games using Reborn.

**Comment by deksden** [comment] 2015-07-14 19:34
@davidw-valve : unfortunally - on my iMac Dota2-Reborn beta did not playable due to other bug - https://github.com/ValveSoftware/Dota-2-Reborn/issues/24#issuecomment-118946920

So, as for now - no Dota2 is working on my system ;) Just waiting for fixes))

**Comment by Damdomy** [comment] 2015-07-14 19:35
@davidw-valve Reborn runs very poorly on my macbook air.

**Comment by davidw-valve** [comment] 2015-07-14 21:41
We have a fix for this. Please expect it to be resolved in the next update.

Note that this only appears to affect bot games, you can still play online with others while waiting for this to be fixed.

**Comment by thanhkhoa85** [comment] 2015-07-17 16:50
Me too. After updated, I can't play game anymore. When I see my hero moving, I really boring. Could someone have any idea to fix this bugs?

**Comment by akalankapagoda** [comment] 2015-07-18 00:19
Same problem. Just here to notify.

**Comment by DeaconFell** [comment] 2015-07-18 00:20
I just tested after the latest update and it worked. If you haven't played since downloading it give it another try.

**Comment by Isuru-Nanayakkara** [comment] 2015-07-18 07:30
This issue is fixed in the last update. Just checked myself.

**Comment by akalankapagoda** [comment] 2015-07-18 12:46
Fixed! Finally!

**Comment by gdrewb-valve** [comment] 2015-07-20 17:52
Closing as this appears fixed.

**Closed by gdrewb-valve** 2015-07-20 17:52 UTC
Labels: State: Reviewed
