### ISSUE TITLE
[SOLVED]No sound after recent update.

### ISSUE THREAD

**Issue by pppkin** [ValveSoftware/Dota-2#1218] opened 2017-04-26 14:59 UTC
Update: I manage to fix this by specifying ```SDL_AUDIODRIVER=alsa``` in the launch options. I guess it's more like a configure problem rather a "program error". Thank you guys for pitching in!
 
After recent update I cannot get any sound in Dota 2. I'm running on Arch Linux with pulseaudio and pulseaudio-jack pulseaudio-alsa installed.(version 10.0.3). Other games are just fine.
I can find dota2 under the playback tab in pavucontrol though

```
$uname -a
Linux leois-ativbook 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux
```

I've got the following SDL libraries installed.
```
$pacman -Qs sdl
local/lib32-sdl 1.2.15-6
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard (32-bit)
local/lib32-sdl2 2.0.5-2
    Simple DirectMedia Layer
local/lib32-sdl2_image 2.0.1-1
    A simple library to load images of various formats as SDL surfaces
local/lib32-sdl2_mixer 2.0.1-1
    A simple multi-channel audio mixer
local/lib32-sdl2_ttf 2.0.14-2
    Library that allows you to use TrueType fonts in your SDL applications (Version 2) (32-bit)
local/lib32-sdl_image 1.2.12-3
    A simple library to load images of various formats as SDL surfaces (32-bit)
local/lib32-sdl_mixer 1.2.12-2
    A simple multi-channel audio mixer
local/lib32-sdl_ttf 2.0.11-3
    A library that allows you to use TrueType fonts in your SDL applications (32-bit)
local/lib32-smpeg 0.4.5-2
    SDL MPEG Player Library
local/lib32-smpeg2 2.0.0-2
    SDL2 MPEG Player Library
local/sdl 1.2.15-8
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard
local/sdl2 2.0.5-3
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard (Version 2)
local/sdl2_image 2.0.1-1
    A simple library to load images of various formats as SDL surfaces (Version 2)
local/sdl2_mixer 2.0.1-1
    A simple multi-channel audio mixer (Version 2)
local/sdl2_ttf 2.0.14-1
    A library that allows you to use TrueType fonts in your SDL applications (Version 2)
local/sdl_gfx 2.0.26-1
    SDL graphics drawing primitives and other support functions
local/sdl_image 1.2.12-4
    A simple library to load images of various formats as SDL surfaces
local/sdl_mixer 1.2.12-5
    A simple multi-channel audio mixer
local/sdl_net 1.2.8-3
    A small sample cross-platform networking library
local/sdl_sound 1.0.3-6
    A library to decode several popular sound file formats, such as .WAV and .MP3
local/sdl_ttf 2.0.11-4
    A library that allows you to use TrueType fonts in your SDL applications
local/smpeg 0.4.5-3
    SDL MPEG Player Library
local/smpeg2 1:2.0.0-2
    SDL2 MPEG Player Library
```

Here are the outputs when running steam from terminal

```
Game update: AppID 570 "Dota 2", ProcID 7219, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 7219 for game ID 570
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7221 != 7220, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198109383498
Setting breakpad minidump AppID = 373300
>>> Adding process 7220 for game ID 570
>>> Adding process 7222 for game ID 570
>>> Adding process 7223 for game ID 570
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD OLAND (DRM 2.49.0 / 4.10.11-1-ARCH, LLVM 4.0.0)
DumpContextInfo: Using OpenGL context version 4.5
DumpContextInfo: Context supports GLSL version 4.50
 failed to dlopen "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(gameoverlayui)/version(20170420215842)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded no]
[0426/222602.155400:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Game removed: AppID 570 "Dota 2", ProcID 7223 
No cached sticky mapping in ActivateActionSet.Generating new string page texture 406: 128x256, total string texture memory is 3.28 MB
Game update: AppID 570 "Dota 2", ProcID 7219, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 7219 for game ID 570
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7221 != 7220, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198109383498
Setting breakpad minidump AppID = 373300
>>> Adding process 7220 for game ID 570
>>> Adding process 7222 for game ID 570
>>> Adding process 7223 for game ID 570
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD OLAND (DRM 2.49.0 / 4.10.11-1-ARCH, LLVM 4.0.0)
DumpContextInfo: Using OpenGL context version 4.5
DumpContextInfo: Context supports GLSL version 4.50
 failed to dlopen "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(gameoverlayui)/version(20170420215842)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded no]
[0426/222602.155400:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Game removed: AppID 570 "Dota 2", ProcID 7223 
No cached sticky mapping in ActivateActionSet.
Game update: AppID 570 "Dota 2", ProcID 7219, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 7219 for game ID 570
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7221 != 7220, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nickleoi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198109383498
Setting breakpad minidump AppID = 373300
>>> Adding process 7220 for game ID 570
>>> Adding process 7222 for game ID 570
>>> Adding process 7223 for game ID 570
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD OLAND (DRM 2.49.0 / 4.10.11-1-ARCH, LLVM 4.0.0)
DumpContextInfo: Using OpenGL context version 4.5
DumpContextInfo: Context supports GLSL version 4.50
 failed to dlopen "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(gameoverlayui)/version(20170420215842)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/nickleoi/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198109383498 [API loaded no]
[0426/222602.155400:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Game removed: AppID 570 "Dota 2", ProcID 7223 
No cached sticky mapping in ActivateActionSet.
```

**Comment by kisak-valve** [comment] 2017-04-26 15:17
Hello @pppKin, are you running steam with the steam runtime or steam with the native runtime? If you are running with the native runtime, do you have the `steam-native-runtime` package installed?

Do you happen to know if any of the other games you tested are 64 bit?

I am not able to reproduce this issue on my Arch test box.

**Comment by pppkin** [comment] 2017-04-26 15:34
@kisak-valve thank you for replying.
yes I've installed steam-native-runtime. And I have this issue with steam runtime and native runtime. and I've tried them in xorg and wayland. None can work.

I tried these games and they work fine(not sure which one is 64bit though) : Metro 2033 redux, Sanctum 2, CSGO, Borderlands 2.

edit: I've just tried Dirt Rally, which appears to be a 64bit game, it doesn't even start. output shows a lot of libraries missing.

**Comment by gdrewb-valve** [comment] 2017-04-26 16:14
Do you know a rough timeframe of the update that changed things, something with a more specific date and what updated?

The only thing that might have affected this recently was our SDL update so I'm assigning to the SDL dev.

**Comment by pppkin** [comment] 2017-04-26 16:35
@gdrewb-valve I can confirmed that it happens within the last 10 days. My last game was on 18th April, which was perfectly fine.
After 18th I've done several upgrades. Not sure which part breaks the sound. I will try to downgrade some package and see if it can be fixed. Thank you for your reply.

**Comment by pppkin** [comment] 2017-04-26 18:11
I am posting some info about pulseaudio on my system. Not sure if it helps.
```
$pacmd list-sink-inputs
index: 57
	driver: <protocol-native.c>
	flags: DONT_MOVE 
	state: DRAINED
	sink: 0 <alsa_output.pci-0000_00_1b.0.analog-stereo>
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	muted: no
	current latency: 0.00 ms
	requested latency: 15.01 ms
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	resample method: (null)
	module: 12
	client: 72 <dota2>
	properties:
		media.name = "Simple DirectMedia Layer"
		application.name = "dota2"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "32"
		application.process.id = "3899"
		application.process.user = "nickleoi"
		application.process.host = "leois-ativbook"
		application.process.binary = "dota2"
		application.language = "en_US.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "5ff7fc4223b445438ec58550d28f6873"
		application.process.session_id = "c1"
		module-stream-restore.id = "sink-input-by-application-name:dota2"
```
the DRAINED confuses me. It seems that this only appear with dota 2. 
```
$pacmd list-cards
1 card(s) available.
    index: 0
	name: <alsa_card.pci-0000_00_1b.0>
	driver: <module-alsa-card.c>
	owner module: 6
	properties:
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf7f10000 irq 31"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "1e20"
		device.product.name = "7 Series/C216 Chipset Family High Definition Audio Controller"
		device.form_factor = "internal"
		device.string = "0"
		device.description = "Built-in Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	profiles:
		input:analog-stereo: Analog Stereo Input (priority 60, available: unknown)
		output:analog-stereo: Analog Stereo Output (priority 6000, available: unknown)
		output:analog-stereo+input:analog-stereo: Analog Stereo Duplex (priority 6060, available: unknown)
		output:hdmi-stereo: Digital Stereo (HDMI) Output (priority 5400, available: no)
		output:hdmi-stereo+input:analog-stereo: Digital Stereo (HDMI) Output + Analog Stereo Input (priority 5460, available: unknown)
		output:hdmi-surround: Digital Surround 5.1 (HDMI) Output (priority 300, available: no)
		output:hdmi-surround+input:analog-stereo: Digital Surround 5.1 (HDMI) Output + Analog Stereo Input (priority 360, available: unknown)
		output:hdmi-surround71: Digital Surround 7.1 (HDMI) Output (priority 300, available: no)
		output:hdmi-surround71+input:analog-stereo: Digital Surround 7.1 (HDMI) Output + Analog Stereo Input (priority 360, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <output:analog-stereo+input:analog-stereo>
	sinks:
		alsa_output.pci-0000_00_1b.0.analog-stereo/#0: Built-in Audio Analog Stereo
	sources:
		alsa_output.pci-0000_00_1b.0.analog-stereo.monitor/#0: Monitor of Built-in Audio Analog Stereo
		alsa_input.pci-0000_00_1b.0.analog-stereo/#1: Built-in Audio Analog Stereo
	ports:
		analog-input-internal-mic: Internal Microphone (priority 8900, latency offset -10000 usec, available: unknown)
			properties:
				device.icon_name = "audio-input-microphone"
		analog-input-mic: Microphone (priority 8700, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-input-microphone"
		analog-output-speaker: Speakers (priority 10000, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-speakers"
		analog-output-headphones: Headphones (priority 9000, latency offset 0 usec, available: yes)
			properties:
				device.icon_name = "audio-headphones"
		hdmi-output-0: HDMI / DisplayPort (priority 5900, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "video-display"
```

**Closed as completed** 2017-04-27 08:11 UTC
Labels: reviewed
