### ISSUE TITLE
Dota crash in ranked game after compendium update

### ISSUE THREAD

**Issue by shchemelevev** [ValveSoftware/Dota-2#1598] opened 2019-05-09 17:49 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/shchemelevev/c2520bef3281c12972c2bc74d10c4ec2
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After I bought new compendium game started to crush in ranked matches.
I tried to reboot mac, used -autoconfig option, -safe option nothing helps.
Mostly crashes happen during have battles with many players around.

#### Steps for reproducing this issue:

1. Start game
2. Start ranked match
3. Find many opponents in one place

**Comment by shchemelevev** [comment] 2019-05-09 18:33
Sorry for that, command+w started to close dota. Is there any way to disable it?

**Comment by kisak-valve** [comment] 2019-05-09 18:46
Hello @shchemelevev, the game shouldn't block system-wide keyboard shortcuts. Closing as a duplicate of #1536.

**Closed as completed by kisak-valve** 2019-05-09 18:46 UTC
Labels: reviewed

**Comment by shchemelevev** [comment] 2019-05-09 19:02
If I chose to block system-wide keyboard shortcut in the game I prefer to be notified if it is not possible. This behaviour is clearly unexpected and causes bad user experience.
Could you fix it please?

**Comment by shchemelevev** [comment] 2019-05-09 19:03
@kisak-valve

**Comment by shchemelevev** [comment] 2019-05-09 19:13
And can you please consider that there is multiple issues here and multiple question in the internet regarding this issue. May be it is not good to block system-wide keyboard, but looks if you block it no harm will be done.
