### ISSUE TITLE
[OSX] Volume/Brightness HUD No longer hidden

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#602] opened 2015-10-24 07:20 UTC
I've recently noticed that Volume and Brightness HUD starded popping up in game.

![](https://cobalt60.xyz/shared/Screen-Shot-2015-10-24-12-11-10.png)

**Comment by gdrewb-valve** [comment] 2015-10-24 19:29
Does it pop up on its own or when you hit certain keys?

**Comment by gxgani** [comment] 2015-10-24 19:30
Only upon usage.

**Comment by gxgani** [comment] 2015-10-24 19:31
To also add, FPS drops during the HUD duration.

**Comment by gdrewb-valve** [comment] 2015-10-24 19:31
Usage of the volume and brightness controls?  Do they then go away?

**Comment by gxgani** [comment] 2015-10-24 19:31
Yes, after the default timeout, they disappear.

**Comment by gdrewb-valve** [comment] 2015-10-24 19:33
Do they not work properly?  I'm not sure what the issue is here.  If you used the volume controls I would expect the volume control to pop up.

**Comment by gxgani** [comment] 2015-10-24 19:36
In source 1 and just before the recent update, the HUD was not appearing when brightness/volume were changed, which I suppose seemed normal? And just as I said, there's noticeable amount of drop in the FPS when the HUD appears.

**Comment by gdrewb-valve** [comment] 2015-10-24 19:42
OK, thanks for the clarification.

**Comment by NekR** [comment] 2015-11-11 22:42
@gxgani do you use Exclusive Fullscreen? I do not see any overlays in that mode, but it's expected in other, I think.

**Comment by gxgani** [comment] 2015-11-12 02:20
@NekR Yes, I do use desktop friendly fullscreen. As stated in the issue, this was not occurring in the previous patch.

**Comment by jeanlain** [comment] 2015-11-21 09:25
For me it's not an issue. In desktop-friendly fullscreen, you should be able to interact with the desktop and see the brightness/Volume HUD.

**Comment by gxgani** [comment] 2015-11-21 09:27
@jeanlain The thing is overlay is causing drastic FPS drop which shouldn't be occurring in desktop friendly mode.

**Comment by gdrewb-valve** [comment] 2015-11-22 20:01
Performance effects of the overlay will happen in any mode.  There might be a different overall perf difference between exclusive fullscreen and desktop-friendly fullscreen, but any Steam overlay will still affect both.

**Comment by gxgani** [comment] 2015-11-22 20:29
Can we have it disabled as it was earlier? And by overlay I am meaning Apple Brightness/Volume overlay.

**Comment by gdrewb-valve** [comment] 2015-11-23 17:16
DFF allows that sort of thing by-design.  If you use exclusive fullscreen you won't get them.

**Comment by gxgani** [comment] 2015-11-23 17:46
@gdrewb-valve May I know why was the overlay hidden previously? Is it possible to have an option to disable it?

**Comment by gdrewb-valve** [comment] 2015-11-23 18:16
There was a bug in SDL which prevent DFF from working the way it should (in a separate space).  That was fixed.  DFF is, as the name suggests, intended to cooperate with all of the normal desktop mechanisms.  Think of it as a windowed app that happens to be the size of the screen.  Exclusive fullscreen is the option you want where the game is all you get.  Choosing between the two is the option you are asking for so it's already available. 

Can you give details on why you aren't using EF?  Are you affected by an EF-related bug?

**Comment by gdrewb-valve** [comment] 2015-11-23 18:19
If you really want to override the DFF behavior you can set the environment variable SDL_VIDEO_MAC_FULLSCREEN_SPACES to 0 for Reborn and that should turn off the spaces change.  That will have other side effects but if you really want to run a partial DFF that's the closest you'll be able to get.

**Comment by gxgani** [comment] 2015-11-23 18:53
@gdrewb-valve I am not using EF because I keep switching spaces/applications while I'm dead or searching match, etc. Exclusive literally blocks me from doing anything else, ie no Cmd+Tab.

**Comment by gdrewb-valve** [comment] 2015-11-23 19:22
Allowing system hotkeys like Cmd+Tab should also allow hotkeys like volume control, so I'm not sure there's a way to provide a partially-system-aware mode.  You can try the SDL envvar but if you are using spaces it probably turns off beneficial behavior for you.

**Comment by gxgani** [comment] 2015-11-23 19:26
@gdrewb-valve games like Left 4 Dead 2 seems to be running on EF but it does allow system hotkeys such as CMD-Tab.

**Comment by gdrewb-valve** [comment] 2015-11-23 23:55
I haven't looked at the L4D2 settings in a long time but it doesn't distinguish DFF from EF, does it, it only has one fullscreen option?  It wouldn't be unusual if it was DFF.

Regardless, Reborn gets the fullscreen behavior that SDL provides and SDL only has two modes, DFF and EF.  The SDL devs have told us that Cmd+Tab and such aren't supposed to work in EF so I don't think they consider that a bug.

**Comment by gxgani** [comment] 2015-11-24 03:55
@gdrewb-valve When playing other games on DFF such as Distance, Borderlands 2, I didn't notice the micro freeze upon changing the brightness/volume(overlay).

**Comment by gdrewb-valve** [comment] 2015-11-24 06:10
You'd have to ask Apple to get information on why the OSX volume overlay behaves differently, Reborn isn't even aware of it.  Also if you do some searches you'll find a variety of people suggesting ways to disable or change the overlay images so if the overlay is a severe problem for you those might be options.

**Comment by gxgani** [comment] 2015-11-24 06:28
@gdrewb-valve I am not sure if Apple would help me on this since most of the full-screen application do not exhibit this freeze. I ended up completely disabling the BezelUIServer.

**Comment by gdrewb-valve** [comment] 2015-11-25 19:14
I'm glad you found a way to get things the way you wanted.  Do you still feel there's a Reborn issue here?  The hitching only occurs when the volume overlay is up, not when Reborn is running on its own, correct?  To me that suggests it is Apple's issue to investigate since Reborn seems to work correctly when the overlay is not present.

**Comment by gdrewb-valve** [comment] 2015-11-30 21:05
Closing.

**Closed as completed by gdrewb-valve** 2015-11-30 21:05 UTC
Labels: reviewed
