### ISSUE TITLE
[OS X] Flickering, Corrupted 3D Graphics

### ISSUE THREAD

**Issue by Andify** [ValveSoftware/Dota-2#24] opened 2015-06-23 07:48 UTC
The menus are quick and responsive but the actually rendered 3D content is glitching horribly; the content flickers rapidly to boot. The computer's specifications can be viewed [here](https://gist.github.com/Andify/72b39168813b2e9fb756).

![screen shot 2015-06-23 at 9 31 08 am](https://cloud.githubusercontent.com/assets/4118371/8301213/50a82578-198c-11e5-9541-0fe9774d1ecd.png)

![screen shot 2015-06-23 at 9 29 40 am](https://cloud.githubusercontent.com/assets/4118371/8301218/54937bf6-198c-11e5-87d9-bbfa5fb3ce65.png)

_EDIT_ Just as an addendum, this is independent of graphics settings, resolution, window mode or rendering quality. It happens any time regardless of the applied settings.

**Comment by Vincentmrl** [comment] 2015-06-24 17:05
I confirm this is happening on my iMac 24" late 2007 too with no difference if I change settings as well. Computer's specs [Here] (https://gist.github.com/Vincentmrl/a8e32d869b4c7c6c1f18)

Some images to show how the problem is virtually the same:
![ingame corruption](https://cloud.githubusercontent.com/assets/13036353/8336319/dc866a60-1aa3-11e5-883e-bf99173514cd.png)
![hero viewer corruption](https://cloud.githubusercontent.com/assets/13036353/8336320/dcb9978c-1aa3-11e5-8c55-36358a772164.png)

**Comment by bklooster** [comment] 2015-06-26 07:20
Just a guess, but I looked at your GPUs on Apple's OpenGL profile website (https://developer.apple.com/opengl/capabilities/) and both of your GPUs do not have the OS X extensions to meet the 4.1 OpenGL specification. Your GPUs currently only meet the OpenGL 3.3 specification. 

I'm not sure if Valve has explicitly put out any official system requirements for Reborn for Mac/Linux other than a 64-bit machine. However, they may require rendering extensions in OpenGL 4.1 that aren't available in 3.3 and thus why you're having such serious rendering issues. Hopefully, Valve developers can respond and let you know if they are planning on supporting OpenGL 3.3 on OS X or not. 

After a GPU is End of Lifed on OS X that class of hardware is very unlikely to receive any driver upgrades in future versions of OS X. So if Valve isn't going to support OpenGL 3.3, the only option you're going to have is to bootcamp into Windows or install Linux.

**Comment by Vincentmrl** [comment] 2015-06-26 10:12
If you do some search, you can see a Valve document about OpenGL: (http://media.steampowered.com/apps/steamdevdays/slides/movingtoopengl.pdf) and they show how OpenGL 3.3 is still used by many people (and from what I understood china intenet cafes with XP will also need to use the GL backend). But at the same time they say that Apple's currently on 4.1 so they either need to add compatibility to OpenGL 3.3 if it's planned or they can't actually add compatibility for reasons (I'm not (yet) a developer but there could be restrictions on OSX about this). The only thing we can do is wait for an official answer

**Comment by danginsburg** [comment] 2015-06-26 10:37
We do support OpenGL v3.3 on OS X.  I've tested for example on GeForce GT330M and it works fine.  I'm not yet sure what the issue is here, but the intent is to support all of the GPUs on the Apple OpenGL profile website including HD2600/HD4850.  Still investigating this one.

**Comment by gdrewb-valve** [comment] 2015-06-27 22:35
Does the 6/26 update change anything?

**Comment by Andify** [comment] 2015-06-27 22:47
Sadly not, the game is running on the latest available patch. The issue remains the exact same from what I can tell.

![screen shot 2015-06-28 at 12 41 54 am](https://cloud.githubusercontent.com/assets/4118371/8394240/23281f08-1d2f-11e5-8ed1-014326c2c63a.png)

![screen shot 2015-06-28 at 12 43 29 am](https://cloud.githubusercontent.com/assets/4118371/8394243/25d6d636-1d2f-11e5-8a65-61b93f9b0dab.png)

![screen shot 2015-06-28 at 12 43 54 am](https://cloud.githubusercontent.com/assets/4118371/8394244/276e3cbe-1d2f-11e5-8eb0-0050f5e2fae2.png)

**Comment by Vincentmrl** [comment] 2015-06-27 23:09
Same issue for me indeed, but I noticed something that could help you find a fix: On the same GPU on windows I remember that all champs had something missing in their portrait (sniper had no hat and cape for example) and the OSX bug looks similar to that (except it's global instead of just the portrait of course). I also noticed something else, if in hero preview I quickly switch between the different skin packs for the champ, I see the hero with the correct pose and no distortion for around half minute. 

Here's the best capture I could get of the problem (I had to take a fullscreen capture to actually get it). NOTE that the not distorted hero isn't transparent but it just fades away after a bit
![Hero Without Distortion](https://cloud.githubusercontent.com/assets/13036353/8394328/30cf07f4-1d32-11e5-8c19-0b68b597f97c.jpg)

**Comment by deksden** [comment] 2015-07-06 18:25
Same graphics issue for me (Late 2009-top config iMac)

**Comment by deksden** [comment] 2015-07-24 12:32
Latest patch as of 24-07-2015 did not resolve this issue!

**Comment by blakeb155** [comment] 2015-07-27 02:50
Top of the line 2009 iMac 27' - exact same issue for me.

**Comment by danginsburg** [comment] 2015-07-27 11:22
As I mentioned in #262, we have filed a Radar with Apple on this issue and are awaiting an update.  I will post progress when I hear something back on this.  We are aware this is impacting HD 2600 and HD 4850.  If there are any other GPUs that you see this on, please let us know.

**Comment by deksden** [comment] 2015-07-27 11:25
@danginsburg : Yup. Tnx - did not read #262, now i m subscribet for that issue too. 

Yes, you are right - my card is ATI Radeon HD 4850.

**Comment by alexmcjuicy** [comment] 2015-08-20 00:18
"If there are any other GPUs that you see this on, please let us know."

I have Late-2009 iMac with ATI Radeon HD 4670 GPU, this is happening to me.

**Comment by danginsburg** [comment] 2015-08-20 12:02
We worked with AMD and found a workaround for this bug.  I personally tested the fix on HD 4670, but it should fix the problem for all of HD 2400/2600/4670/4850/4870.  The fix will be in the next update to Dota 2 Reborn.

**Comment by blakeb155** [comment] 2015-09-02 11:45
Hi Dan,

Can confirm today's reborn update fixed the issue for me

Thanks!

**Comment by danginsburg** [comment] 2015-09-02 12:08
@blakeb155 Thanks for the confirmation.  Closing out this bug.

**Closed as completed by danginsburg** 2015-09-02 12:08 UTC
Labels: reviewed, drivers

**Comment by srhseungyeon** [comment] 2016-12-15 14:36
hi @danginsburg my mac ATI Radeon HD 4670 GPU is also having this graphic bug issue after i updated the dota 2 7.00 patch. can i get help on this?

**Comment by danginsburg** [comment] 2016-12-15 15:04
@srhseungyeon Please open a new issue with repro instructions, screenshot(s), and your system information.  This particular issue was a driver bug we worked around.
