### ISSUE TITLE
[Mac OSX] Client won't start up.

### ISSUE THREAD

**Issue by Shad3w** [ValveSoftware/Dota-2#397] opened 2015-09-10 13:58 UTC
When I click "Play" the game opens up to just a black screen. No loading screen. Just a black screen.

**Comment by davidw-valve** [comment] 2015-09-10 17:16
Have you been able to play Dota2 before? If so when did this start occurring?

What version of OS are you using?

**Comment by Shad3w** [comment] 2015-09-10 17:20
I am using OS X Yosemite 10.10.5. I've been able to play dota 2 prior to the update forcing source two to be played as the main client, and prior to that I just couldn't play reborn due to issues #24 After Issue #24 was resolved I couldn't play because of issue #345 and now, since it's been made into the main client it won't even load.

**Comment by danginsburg** [comment] 2015-09-10 19:23
Right, this is a duplicate of #345.  As far as I can tell from the reports the issue is particular to machines with HD2400/HD2600.  We are working on trying to repro.  It does not repro on similar iMacs with HD4xxx.

**Closed as completed by danginsburg** 2015-09-10 19:23 UTC
Labels: duplicate, reviewed
