### ISSUE TITLE
[Ubuntu] Can't spectate WCA EU qualifier games.

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1003] opened 2016-08-23 22:33 UTC
Since Dark Rift Update 2 i can't spectate games. I was casting Escape vs Empire and can't watch game 3.
It started again when trying to load the draft screen... Game crashed instantly but after the draft (when some months ago, and probably up to now, you could watch the game) it starts to load the game and at the same time goes back to watch tab follow by a couple of messages about not being able to spectate the game.

Ubuntu 16.04, Nvidia 367.35, Both -gl and -vulkan

First 3 lines are the erros from dmesg... after that the con_logfile
https://gist.github.com/admshao/62f21a7c0858496934ff60800bf2622b

**Comment by gdrewb-valve** [comment] 2016-08-23 22:52
That was a captain's mode game, correct?  That means this is a duplicate of #922.

**Comment by gdrewb-valve** [comment] 2016-08-24 20:55
Closing since this looks like a duplicate.

**Closed as completed by gdrewb-valve** 2016-08-24 20:55 UTC
Labels: reviewed
