### ISSUE TITLE
[Linux] empty popup

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#710] opened 2016-01-06 10:10 UTC
hi,
In the new stats page of the player profile, there is an empty mouseover popup.

![dota_2_reborn_bug2](https://cloud.githubusercontent.com/assets/5174562/12140165/fdb0cdfa-b465-11e5-8702-15d15189ebf4.png)

**Comment by gdrewb-valve** [comment] 2016-01-06 18:41
Duplicate of #54, that's a hero movie.

**Closed as completed by gdrewb-valve** 2016-01-06 18:41 UTC
Labels: duplicate, reviewed
