### ISSUE TITLE
No "Exclusive fullscreen" option

### ISSUE THREAD

**Issue by withthelemons** [ValveSoftware/Dota-2#430] opened 2015-09-12 22:06 UTC
There is no "Exclusive fullscreen" option in video settings. This causes desktop compositor to interfere with Dota. I also cannot set brightness and Dota is very dim.

**Comment by danginsburg** [comment] 2015-09-13 20:13
Duplicate of #428.

**Closed as completed by danginsburg** 2015-09-13 20:13 UTC
Labels: duplicate, reviewed
