### ISSUE TITLE
Client crashes after a few seconds on El Capitan

### ISSUE THREAD

**Issue by bxio** [ValveSoftware/Dota-2#57] opened 2015-06-24 01:14 UTC
Latest MacBook Pro retina, running OS X 10.11 beta2. The client successfully launches but crashes a few seconds after. 

I have tried reinstalling the beta, and verifying game cache. Please advise on next steps.

**Comment by gdrewb-valve** [comment] 2015-06-24 01:39
Duplicate of #15.

**Closed as completed by gdrewb-valve** 2015-06-24 01:39 UTC
Labels: duplicate, reviewed
