### ISSUE TITLE
[Linux] Broken ingame Hud on resolution change.

### ISSUE THREAD

**Issue by CommanderAlchemy** [ValveSoftware/Dota-2#214] opened 2015-07-05 02:25 UTC
I found that for me its related to how Dota 2 handles resolution changes.
Bug #13 Forces me to use Kwin rule to move the application to correct position.

If the game is in borderless window (im guessing it goes into fullscreen mode), changing resolution then breaks the ingame HUD as seen below. 

![b16fb718-1d56-11e5-8477-b04d124af3ef](https://cloud.githubusercontent.com/assets/3089330/8510044/a826416a-22cc-11e5-93ff-d62e2adf4f06.png)

Switching to Window mode with launch options and then force fullscreen with Kwin does not seem to trigger this issue however then modifier keys like ALT does not work in game since global hotkeys intercept it instead. #30.

**Comment by Pharmasolin** [comment] 2015-07-06 11:36
Also if change map location (via settings) while in game, will be crash in HUD too.

**Comment by danginsburg** [comment] 2015-08-24 11:35
Can you try using -sdl_displayindex N (0, 1, 2, etc.) to control which monitor the window starts on rather than using a Kwin rule?  Does that fix this bug?

**Comment by danginsburg** [comment] 2015-08-24 20:07
I believe this is a duplicate of #2 and that bug has been resolved. From my testing, I believe this works properly using -sdl_displayindex. Please reopen if this still happens with the latest client and post repro instructions.

**Closed as completed by danginsburg** 2015-08-24 20:07 UTC
Labels: reviewed
