### ISSUE TITLE
text input problem in recent updates

### ISSUE THREAD

**Issue by timxx** [ValveSoftware/Dota-2#1045] opened 2016-10-12 12:28 UTC
When installed fcitx (Chinese input method), and setting **export XMODIFIERS=@im=fcitx** env, 
all things goes wrong with dota 2:
In the home window (not start a game), press **Backspace** cause double effect, it will delete two chars no matter Chinese or English. When switch to fcitx (Ctrl + Space) to type Chinese, and in the predict window state, press Backspace also delete the text in chat window of dota 2.

In the game window (playing a game), when press **Enter**, the chat window disappear immediately, no chance to type any text :( 
Also the Y window can't control at all (I mean press Y and popup a circle window), the window keeps flick.

It seems that the recent updates handle the XIM message, all keyboard message wrongly send to input method first when the input method not in active state.

Please consider fix this problem ASAP, now I can't chat through text (unless unset the XMODIFIERS env).
The fcitx dbus implement already push to the SDL default repo (https://hg.libsdl.org/SDL/rev/6660aa9120d6), you should have a update on SDL.

Thanks (and sorry for my poor English)

OS: Arch Linux 64 bit

**Comment by Tele42** [comment] 2016-10-12 12:50
Duplicate of #1038.

**Comment by gdrewb-valve** [comment] 2016-10-12 15:40
Closing duplicate.

**Closed as completed by gdrewb-valve** 2016-10-12 15:40 UTC
