### ISSUE TITLE
[Linux] Cursor size on High DPI 

### ISSUE THREAD

**Issue by rcano** [ValveSoftware/Dota-2#410] opened 2015-09-11 14:56 UTC
I have a linux machine with 2880x1620 resolution and the cursor is the size of the head of a ranged creep.
In fact, the cursor shown throughout the UI is bigger than that shown ingame for some reason.
Here is a picture:

![smallcursor](https://cloud.githubusercontent.com/assets/759769/9817877/e232c768-587b-11e5-839a-fa90c1026b86.png)

You will find the cursor above Pudge's portrait. Notice it is roughly half the height of the portrait, while on 1080p the cursor size is the full height.

Here is my system info:

Processor Information:
Vendor: GenuineIntel
CPU Family: 0x6
CPU Model: 0x3c
CPU Stepping: 0x3
CPU Type: 0x0
Speed: 3700 Mhz
8 logical processors
4 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed:

Operating System Version:
Ubuntu 15.04 (64 bit)
Kernel Name: Linux
Kernel Version: 3.19.0-28-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11701000
X Window Manager: KWin
Steam Runtime Version: steam-runtime-release_2015-06-12

Video Card:
Driver: NVIDIA Corporation Quadro K2100M/PCIe/SSE2

Driver Version:  4.5.0 NVIDIA 352.41
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x11fc
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  2880 x 1620
Desktop Resolution: 4320 x 1620
Primary Display Size: 13.39" x 7.48"  (15.31" diag)
                                        34.0cm x 19.0cm  (38.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
Audio device: Intel Haswell HDMI

Memory:
RAM: 31805 Mb

Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 157576 Mb
Largest Free Hard Disk Block: 132078 Mb

Installed software:

Recent Failure Reports:

**Comment by gdrewb-valve** [comment] 2015-10-12 16:35
Duplicate of #347.

**Closed as completed by gdrewb-valve** 2015-10-12 16:35 UTC
Labels: reviewed
