### ISSUE TITLE
Dota 2 crash.

### ISSUE THREAD

**Issue by 4pih** [ValveSoftware/Dota-2#845] opened 2016-04-22 17:03 UTC
Hi,

Today is a very bad day for me. Dota 2 keep crashing game after game at random. Sometime only Dota2 crashed, but sometime my macbook crashed and restarted. It happens even when i'm just spectating other's game. Here is the **console.log** file. Hope this will help you to resolve the issue.
Thank you and have a great day.

[console.log.zip](https://github.com/ValveSoftware/Dota-2/files/232245/console.log.zip)

**Comment by gdrewb-valve** [comment] 2016-04-23 09:37
Can you post the full system information from Steam?

**Comment by 4pih** [comment] 2016-04-23 09:40
Hi, 
Here is the system info from Steam.
Thank you.

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro9,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.3 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.22" x 7.01"  (13.23" diag)
                                        28.5cm x 17.8cm  (33.6cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475766 Mb
    Largest Free Hard Disk Block:  156794 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment] 2016-04-23 09:50
There is no failure report information?  That means that none of the crashes have been recorded to look at.  This often indicates a driver problem but it's hard to say for sure.  We'll have to try and catch the problem here at Valve.

**Comment by 4pih** [comment] 2016-04-23 10:04
My mac usually generates crashed report. I'll update this thread once I manage to grab it. 
Thanks for your prompt reply.

**Comment by 4pih** [comment] 2016-04-23 10:43
By the way,
I attached the crash report but this is not the latest. Hope this can you in the investigation.
Thank you.

[dota2_2016-03-21-093859_BlackBeard.crash.zip](https://github.com/ValveSoftware/Dota-2/files/232909/dota2_2016-03-21-093859_BlackBeard.crash.zip)

**Comment by 4pih** [comment] 2016-04-30 08:31
Hi,
Here is the latest crash report from my mac.
Hope this helps.

Thank you

[Dota2.crash.zip](https://github.com/ValveSoftware/Dota-2/files/243511/Dota2.crash.zip)

**Comment by danginsburg** [comment] 2016-05-02 12:42
@4pih For dota2_2016-03-21-093859_BlackBeard.crash.zip are you able to provide any more information about what you were doing during this crash?  For example, if you were watching a match could you provide the match ID?  It looks like an infinite recursion problem in our code from the crash dump, but I will need to figure out a way to reproduce it.  The second Dota2.crash.zip looks like a crash inside the AppleIntelHD4000Graphics driver.

**Comment by gdrewb-valve** [comment] 2016-05-17 01:29
You have two different crashes, but are there still problems after the May 16 update?  Can you post a new failure report?

**Comment by 4pih** [comment] 2016-05-18 15:02
Hi,
Sorry for late reply.
I didn't play much lately. Will update this thread if have new crash report.
But, i do notice my mouse acting weird since last few days. It's like lag / stuttered / glitching. 
Its never happen before but I already try changing mouse battery, mousepad, connect wired mouse etc. But still no good. All my dota2 setting is at the lowest. 

Mouse works fine if dota2 is not running.

**Comment by gdrewb-valve** [comment] 2016-05-18 15:14
OK, closing for now.

You can open a new issue for mouse lag if you believe it's a Dota problem.

**Closed as completed by gdrewb-valve** 2016-05-18 15:14 UTC
Labels: reviewed

**Comment by 4pih** [comment] 2016-05-18 15:23
OK.. Thanks for the support :)

**Comment by 4pih** [comment] 2016-05-23 18:41
Hi, 
I'm not sure is it OK to update this thread again. But the crashes still happening. Here is my last 2 crash reports.

[Kernel_Task - Crash Report.zip](https://github.com/ValveSoftware/Dota-2/files/278037/Kernel_Task.-.Crash.Report.zip)

Hope you can take a look.
Thank you and have a nice day.

**Comment by gdrewb-valve** [comment] 2016-05-23 19:09
Kernel panics should be reported to Apple.

**Comment by 4pih** [comment] 2016-05-24 02:28
Noted. Thanks 👍

**Comment by 4pih** [comment] 2016-05-24 07:51
Hi, 
Its me again.
I played a lot today and got crashed a lot too.

Here is the latest one. 

Anonymous UUID:       533E1EF0-D3A6-141A-496E-5F87634E503F

Tue May 24 15:42:28 2016

**\* Panic Report ***
panic(cpu 0 caller 0xffffff802e511424): "Invalid queue element linkage for 0xffffff805197ad58: next 0xffffff820ca85068 next->prev 0xffffff805197ad58 prev 0xffffff80514791f8 prev->next 0xffffff805197ac58"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3248.50.21/osfmk/kern/queue.h:245
Backtrace (CPU 0), Frame : Return Address
0xffffff922e3f3bd0 : 0xffffff802e4dab12 
0xffffff922e3f3c50 : 0xffffff802e511424 
0xffffff922e3f3ca0 : 0xffffff802e511553 
0xffffff922e3f3d20 : 0xffffff802e4edb93 
0xffffff922e3f3d90 : 0xffffff802e515312 
0xffffff922e3f3dd0 : 0xffffff802e5172a0 
0xffffff922e3f3e10 : 0xffffff802e4efd1d 
0xffffff922e3f3e50 : 0xffffff7faf238b10 
0xffffff922e3f3e80 : 0xffffff7faf236cd8 
0xffffff922e3f3f00 : 0xffffff7faf236dc1 
0xffffff922e3f3f20 : 0xffffff802ea18c2e 
0xffffff922e3f3f60 : 0xffffff802ea286a1 
0xffffff922e3f3fb0 : 0xffffff802e5ecc66 
      Kernel Extensions in backtrace:
         com.apple.kec.pthread(1.0)[39D0B4EB-B7F4-3891-96C2-F8B886656C8A]@0xffffff7faf230000->0xffffff7faf23cfff

BSD process name corresponding to current thread: dota2

Mac OS version:
15F34

**Comment by Mis-tian** [comment] 2019-02-15 14:30
I've come across the same problem



BSD process name corresponding to current thread: dota2

Mac OS version:
18D109

Kernel version:
Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Kernel UUID: 1970B070-E53F-3178-83F3-1B95FA340695
Kernel slide:     0x000000001ce00000
Kernel text base: 0xffffff801d000000
__HIB  text base: 0xffffff801cf00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 692216983198
last loaded kext at 246035547625: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f9ff50000, size 69632)
last unloaded kext at 687806701096: com.apple.driver.usb.cdc.ecm	5.0.0 (addr 0xffffff7f9f351000, size 53248)
loaded kexts:
