### ISSUE TITLE
Battle Pass points was given incorrectly

### ISSUE THREAD

**Issue by math1over** [ValveSoftware/Dota-2#2159] opened 2022-09-29 16:02 UTC
See the following pictures. We were told that: if we make a correct guess of winner team, we would get 500 (Battle Pass) points. However, we only got 100 points for each correct guess.

https://steamcommunity.com/sharedfiles/filedetails/?id=2869066067
https://steamcommunity.com/sharedfiles/filedetails/?id=2869066048

**Comment by kisak-valve** [comment] 2022-09-29 16:21
Hello @math1over, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. Your previous issue report was transferred to Dota2-Gameplay because it reads like a general, cross-platform issue.

Closing as a duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/3532.

**Closed as not planned by kisak-valve** 2022-09-29 16:21 UTC
