### ISSUE TITLE
Segfaults since latest patch

### ISSUE THREAD

**Issue by kdwinter** [ValveSoftware/Dota-2#1438] opened 2018-04-03 14:09 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/kdwinter/465269b5a25c67099cd3744c44b77273
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Playing an unranked matchmaking game, the game begins segfaulting after around 10-15 minutes. Segfaults continue to occur between seconds to a few minutes after reconnecting, rendering the remainder of the match unplayable.

Output in stdout:

    crash_20180403154255_1.dmp[3610]: Uploading dump (out-of-process)
    /tmp/dumps/crash_20180403154255_1.dmp
    crash_20180403154255_1.dmp[3610]: Finished uploading minidump (out-of-process): success = yes
    crash_20180403154255_1.dmp[3610]: response: Discarded=1
    crash_20180403154255_1.dmp[3610]: file ''/tmp/dumps/crash_20180403154255_1.dmp'', upload yes: ''Discarded=1''
    pid 3610 != 3594, skipping destruction (fork without exec?)
    ~/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104:  3530 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

Dump from output above is attached here: [dump.zip](https://github.com/ValveSoftware/Dota-2/files/1871834/dump.zip)

#### Steps for reproducing this issue:

1. Play an unranked match (haven't tried ranked but I assume this makes no difference)
2. Experience crashes after 10-15 minutes

**Comment by kisak-valve** [comment] 2018-04-03 14:27
Hello @kdwinter, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

For reference, the attached minidump is a SIGSEGV coming from libnetworksystem.so (part of Dota 2).

**Comment by kdwinter** [comment] 2018-04-03 14:28
My bad; forgot to actually paste the link. I have edited the OP.

**Comment by gdrewb-valve** [comment] 2018-04-04 00:42
Duplicate of other Dota Plus issues (primary at #1419).

**Closed as completed by gdrewb-valve** 2018-04-04 00:42 UTC
