### ISSUE TITLE
[Linux] Dota 2 Reborn stuck on Black screen

### ISSUE THREAD

**Issue by wildtron** [ValveSoftware/Dota-2#406] opened 2015-09-11 10:27 UTC
logo shows up but stops there. and tuck. then the screen goes black. 

OS: Arch Linux x86_64
Kernel Release: 4.1.6-1-ARCH

Here's an output from dumps

```
Game update: AppID 570 "Dota 2", ProcID 26193, IP 0.0.0.0:0
ERROR: ld.so: object '/home/craeden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/craeden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 26195 != 26194, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/craeden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/craeden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198084011927 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198084011927
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20150819112831)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/craeden/.local/share/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/craeden/.local/share/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
/home/craeden/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 98: 26197 Killed                  ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 26197 
```

**Comment by danginsburg** [comment] 2015-09-11 12:43
Seems possibly a duplicate of #405 .  Can you provide what I asked for there:

Trying to repro this here on Ubuntu 15.04 x64 NVIDA 352.41 and not seeing it. Can you add -con_logfile to your command line and post game/dota/console.log? Can you also do Steam -> Help -> System Information and post that? Please also do Verify Game Cache on the game and finally you can try launching with -sw to start in windowed mode to see if it reveals anything else. I need to get more info to figure out what is going on.

**Comment by danginsburg** [comment] 2015-09-11 19:12
I'm going to mark this as a duplicate of #405.  If you have additional details please post them there so we can collect info in one place.  Thanks, closing.

**Closed as completed by danginsburg** 2015-09-11 19:12 UTC
Labels: duplicate, reviewed
