### ISSUE TITLE
Complete black screen when opening Dota2

### ISSUE THREAD

**Issue by TimotheeJeannin** [ValveSoftware/Dota-2#517] opened 2015-10-03 07:39 UTC
When I open the game I just have a **black screen**.

![screenshot from 2015-10-03 09 32 31](https://cloud.githubusercontent.com/assets/1969368/10261931/27b5bede-69b2-11e5-8a69-15c2636eabd3.png)

I do **have the sound** of the game, I **have the game** mouse cursor but apart from that **just a black screen**.

I tried different launch options like `-windowed -w 1920 -h 1080 -noborder -novid` without success. 

I'm running **Ubuntu 14.04 LTS** and I have a **GeForce GTX 560 Ti**.

I'm using the `nvidia-current-updates` apt package for the drivers and also tried the `nvidia-current` before this one.

Here is the result of the `lspci | grep VGA` command on my system:

```
01:00.0 VGA compatible controller: NVIDIA Corporation GF114 [GeForce GTX 560 Ti] (rev a1)
```

When adding the `-console` launch option I can see the console.

![screenshot from 2015-10-03 09 32 50](https://cloud.githubusercontent.com/assets/1969368/10261932/27cd8762-69b2-11e5-91cc-d41fc6d0544d.png)

Here is a copy of the logs found in the console:

```
CEntitySystem::BuildEntityNetworking (parallel build of server) took 123.216 msecs for 612 out of 630 classes
CEntitySystem::BuildEntityNetworking (parallel build of client) took 115.822 msecs for 617 out of 638 classes
Failed to load inventory shuffle information file "cfg/dota_player_loadout_shuffle.txt"!
Checking AUTO DLC
Could not load file resource/gamemenu.res. Using empty GameMenu keyvalues.
File error loading resource header "panorama/images/textures/startup_background_logo.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_music.vsndevts_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_stingers.vsndevts_c" (Error: ERROR_FILEOPEN)
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_strong.vmat!
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_med.vmat!
No valid vcs file found for shader gaussian_bloom_blur.vfx

/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!
config file 'cfg/game_convars.vcfg' is overriding an archived convar 'snd_ducktovolume' with value '1'. User will not be able to change this value!
SwitchToLoop levelload requested:  id [1] addons []
8 CPUs (4 physical), Frequency: 3.4 Ghz,  Features: GenuineIntel SSE SSE2 SSE4.1 SSE4.2 AVX MMX RDTSC CMOV FCMOV 
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
Idle (levelload)
Allocating new transform texture!
Writing configuration for slot 0
Compilation failed; no code produced.  Log string from driver:
0(29) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Vertex info
-----------
0(29) : error C3008: unknown layout specifier 'row_major'
Compilation failed; no code produced.  Log string from driver:
0(7) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Vertex info
-----------
0(7) : error C3008: unknown layout specifier 'row_major'
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [1] addons []
name[ 0 ] changing from 'unnamed' to 'Tim'
SV:  maxplayers set to 1
Initializing script VM...
...done
CL:  Adding Prequisite CWaitForGameServerStartupPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
Got network config from CDN.  Loaded revision 25 OK
SV:  Spawn Server: <empty>
Network configuration revision changed 0 -> 25
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  PS_SATISFIED CWaitForGameServerStartupPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  Sending connect to loopback
SV:  Sending S2C_CHALLENGE [3965948953 auth 2] to loopback
CL:  Received S2C_CHALLENGE [3965948953 auth 2] from loopback
CL:  Sending C2S_CONNECT [42 protocol 3965948953 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 42 3965948953 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'Tim' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 6917
Server Number: 1
Initializing script VM...
...done
Mismatch between client C_DOTAPlayer and server CDOTAPlayer
warning: (root)::m_vecClientQuickBuyState exists only in client
CL:  PS_SATISFIED CLoadStartupResourcePrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CLoadSpawnGroupsPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CFinalizeConnectionPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  OnStatusFinished for CGameClientConnectPrerequisite
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
Failed to load grid nav data, file 'maps/<empty>.gnv' not found!
SV:  Sending full update to client Tim (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 33.177 KB [7 pkts], outgoing 1.117 KB [6 pkts]
Compilation failed; no code produced.  Log string from driver:
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(10) : error C3008: unknown layout specifier 'row_major'
0(44) : error C3008: unknown layout specifier 'row_major'
0(99) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Vertex info
-----------
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(10) : error C3008: unknown layout specifier 'row_major'
0(44) : error C3008: unknown layout specifier 'row_major'
0(99) : error C3008: unknown layout specifier 'row_major'
Compilation failed; no code produced.  Log string from driver:
0(6) : error C3008: unknown layout specifier 'row_major'
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(43) : error C3008: unknown layout specifier 'row_major'
0(63) : error C3008: unknown layout specifier 'row_major'
0(78) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Fragment info
-------------
0(6) : error C3008: unknown layout specifier 'row_major'
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(43) : error C3008: unknown layout specifier 'row_major'
0(63) : error C3008: unknown layout specifier 'row_major'
0(78) : error C3008: unknown layout specifier 'row_major'
Compilation failed; no code produced.  Log string from driver:
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(10) : error C3008: unknown layout specifier 'row_major'
0(44) : error C3008: unknown layout specifier 'row_major'
0(98) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Vertex info
-----------
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(10) : error C3008: unknown layout specifier 'row_major'
0(44) : error C3008: unknown layout specifier 'row_major'
0(98) : error C3008: unknown layout specifier 'row_major'
Compilation failed; no code produced.  Log string from driver:
0(6) : error C3008: unknown layout specifier 'row_major'
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(43) : error C3008: unknown layout specifier 'row_major'
0(63) : error C3008: unknown layout specifier 'row_major'
0(78) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Fragment info
-------------
0(6) : error C3008: unknown layout specifier 'row_major'
0(7) : error C3008: unknown layout specifier 'row_major'
0(8) : error C3008: unknown layout specifier 'row_major'
0(9) : error C3008: unknown layout specifier 'row_major'
0(43) : error C3008: unknown layout specifier 'row_major'
0(63) : error C3008: unknown layout specifier 'row_major'
0(78) : error C3008: unknown layout specifier 'row_major'
**** Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
**** Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
Compilation failed; no code produced.  Log string from driver:
0(18) : error C3008: unknown layout specifier 'row_major'
0(19) : error C3008: unknown layout specifier 'row_major'
0(20) : error C3008: unknown layout specifier 'row_major'
0(21) : error C3008: unknown layout specifier 'row_major'
0(55) : error C3008: unknown layout specifier 'row_major'
0(110) : error C3008: unknown layout specifier 'row_major'
Link failed; no code produced.  Log string from driver:
Vertex info
-----------
0(18) : error C3008: unknown layout specifier 'row_major'
0(19) : error C3008: unknown layout specifier 'row_major'
0(20) : error C3008: unknown layout specifier 'row_major'
0(21) : error C3008: unknown layout specifier 'row_major'
0(55) : error C3008: unknown layout specifier 'row_major'
0(110) : error C3008: unknown layout specifier 'row_major'
File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)
/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1924):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!
Ping measurement complete.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
```

**Comment by danginsburg** [comment] 2015-10-05 12:21
This is a duplicate of #32 and is due to a bug an older versions of the NVIDIA driver.  The shaders are failing to compile due to a bug in the GLSL compiler.  Any NVIDIA driver after v331 will fix this issue.

**Closed as completed by danginsburg** 2015-10-05 12:21 UTC
Labels: duplicate, reviewed, drivers
