### ISSUE TITLE
[Linux] Full hanging of the game

### ISSUE THREAD

**Issue by Geradot** [ValveSoftware/Dota-2#1315] opened 2017-09-12 17:03 UTC
Hi. I have a problem: full hanging of the game at the beginning of the match (after the presentation of the towers). I can't kill the process. After reboot the PC this match is loaded and continues without problems.

UPD: I noticed that the problem manifested itself when I tried to change the screen resolution of the game several times in a row.
My system: 
`System:    Host: antergosPC Kernel: 4.12.12-1-ARCH x86_64 bits: 64`
                  `Desktop: Gnome 3.24.3 Distro: Antergos Linux`
`Graphics:  Card: NVIDIA GF108 [GeForce GT 630]`
                 `Display Server: x11 (X.Org 1.19.3 ) driver: nvidia`
                 `Resolution: 1680x1050@59.95hz`
                 `OpenGL: renderer: GeForce GT 630/PCIe/SSE2 version: 4.5.0 NVIDIA 384.69`

**Comment by gdrewb-valve** [comment] 2017-09-12 17:24
You'll want to check with NVIDIA also.

**Comment by Geradot** [comment] 2017-09-12 17:28
@gdrewb-valve so, what you mean? What I must do? What the info I must give yet?

**Comment by gdrewb-valve** [comment] 2017-09-12 17:30
Go to a forum for NVIDIA support and report the issue there also.  

Note in #1314 where you commented that the poster's problem is an NVIDIA issue and not a Dota issue.

**Comment by Geradot** [comment] 2017-09-12 17:33
@gdrewb-valve Oh, maybe it was a mistake. I just do not know what exactly is the problem. Yes, I'm sorry. I in vain commented on that topic :(

**Comment by Geradot** [comment] 2017-09-21 07:34
I mean, I solved the issue. Apparently, the problem was the unmounted swap partition in /etc/fstab because of what there was not enough memory.

**Comment by gdrewb-valve** [comment] 2017-09-21 15:09
Good, glad you found the cause.  This is OK to close then?

**Comment by gdrewb-valve** [comment] 2017-09-21 19:35
Closing.

**Closed as completed by gdrewb-valve** 2017-09-21 19:35 UTC
Labels: reviewed
