### ISSUE TITLE
[macOS] Capslock keybinding only firing on caps-lock "on"

### ISSUE THREAD

**Issue by PatrickOBoyle** [ValveSoftware/Dota-2#1657] opened 2019-08-11 15:43 UTC
Note: Currently on macOS Catalina beta, but issue was triggered from Summer Scrub updates and has been perfectly fine on all versions of beta thus far. Haven't changed beta version since the issue began. Not familiar with any key-input API changes in Catalina so it may somehow be related otherwise though

#### Your system information

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro14,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.0 (64 bit)

Video Card:
    Driver:  Intel Iris Plus Graphics 650
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x5927
    Revision:  0x6
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2304 x 1296
    Desktop Resolution: 4608 x 2592
    Primary Display Size: 18.86" x 10.59" (21.61" diag)
                                            47.9cm x 26.9cm (54.9cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  476802 Mb
    Largest Free Hard Disk Block:  149042 Mb
    VR Headset: None detected

#### Please describe your issue in as much detail as possible:
Key-binding for capslock seems broken on macOS.

Expect it to trigger any time the key is pressed, it's currently triggering only on capslock on. Specifically seeing it for learning skills keybinding.

#### Steps for reproducing this issue:

1. Set capslock as key for level-up
2. Press key twice
3. Observe interaction

**Comment by pulkitsharma07** [comment] 2019-08-12 08:51
Can confirm. Need to press it twice in order to register it as an input.
Another way to replicate this bug, is to go to Settings, and try binding 'CAPSLOCK' for any action/item slot.  It will be set only if capslock becomes "ON" on the keypress. So, if it is already "ON", it will require two keystrokes.

**Comment by danginsburg** [comment] 2019-08-15 18:12
I believe this bug is caused by this change in SDL: https://hg.libsdl.org/SDL/rev/6a3b2cc9d66c.  Assigning to @rcgordon

**Comment by pulkitsharma07** [comment] 2019-09-28 16:10
Update: This is resolved for me now, thanks for the fix.

**Comment by kisak-valve** [comment] 2019-11-01 15:20
Thanks for the feedback, closing per the last comment.

**Closed as completed by kisak-valve** 2019-11-01 15:20 UTC
Labels: reviewed
