### ISSUE TITLE
Segmentation fault while attempting to watch TI6

### ISSUE THREAD

**Issue by buhman** [ValveSoftware/Dota-2#982] opened 2016-08-11 03:36 UTC
Reliably, whenever I attempt to watch the hero draft in-game on TI6 games, dota 2 crashes with a segmentation fault. When I click "watch" the match after the draft is over, the crash does not happen.

I copied the verbatim contents of /tmp/dumps to:

https://gist.github.com/a322b00d345a414933b3696d6591adb7

**Comment by gdrewb-valve** [comment] 2016-08-11 04:53
Duplicate of #922.

**Closed as completed by gdrewb-valve** 2016-08-11 04:53 UTC
