### ISSUE TITLE
[MacOS]

### ISSUE THREAD

**Issue by jelostenan** [ValveSoftware/Dota-2#1374] opened 2018-01-16 21:39 UTC
Game crashes after Dota 2 Update - MAIN CLIENT - January 16, 2018. It crashes right after main menu screen

**Comment by markhughes** [comment] 2018-01-16 21:54
See #1375

**Comment by danginsburg** [comment] 2018-01-16 21:55
Closing as duplicate of #1375.  Fix incoming.

**Comment by jelostenan** [comment] 2018-01-16 21:56
Thanks!)

Ср, 17 янв. 2018 г. в 0:56, Dan Ginsburg <notifications@github.com>:

**Closed as completed by danginsburg** 2018-01-16 21:55 UTC
