### ISSUE TITLE
[MacOS] Crash when trying to watch tournament games during picks and bans 

### ISSUE THREAD

**Issue by Najadorel** [ValveSoftware/Dota-2#1083] opened 2016-12-07 20:29 UTC
If I try to watch a game from tournaments during picks and bans the game just crash and keeps crashing until the last 4 picks and bans.  I have witness this behaviour in the WESG, DreamLeague, The Summit and currently on the Boston Mayor

 

  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Memory:	16 GB

**Comment by Tele42** [comment] 2016-12-07 20:39
Duplicate of #922.

**Comment by gdrewb-valve** [comment] 2016-12-07 23:31
Closing duplicate.

**Closed as completed by gdrewb-valve** 2016-12-07 23:31 UTC
