### ISSUE TITLE
[OSX] Low FPS on Intel Iris (5100)

### ISSUE THREAD

**Issue by manicmouse** [ValveSoftware/Dota-2#274] opened 2015-07-25 20:46 UTC
I know this issue has been brought up before, but it isn't resolved.  In a previous thread a developer was saying he was getting 50fps at lowest settings on an intel HD4000.

On lowest settings on my Intel Iris I get 40fps max.  In comparison to DOTA source 1 the performance is completely abysmal.

Given that source one was basically emulating direct X I expected the performance of Reborn to blow source 1 out of the water.  But it doesn't even come close, despite running native Open GL, being 64 bit and being on a newer "more efficient" engine.  Surely with those 3 things we can expect significant performance boosts over the source 1 version, after all this was the entire point behind reborn.

I'm very confused how the developer, with a much worse intel integrated chip, is getting far better frame rates than I can manage.  I tested this in both Yosemite and El Capitan - similar results, with El Cap being a couple of frames faster but nothing to write home about.

Specs: 2.4Ghz core i5, 8Gb RAM, Intel Iris (HD 5100), tested under OSX Yosemite and El Capitan

At max settings frame rate varies between 15-28.  Lowering settings doesn't seem to make much of a difference, maybe 10 frames between highest and lowest which suggests to me (alongside the general poor performance) that there is something going on that's eating resources other than the graphical settings.

At lowest settings the max framerate I see in top lane with not much going on is 40ish fps (with potato level graphics), at max settings around 28fps.

**Comment by gdrewb-valve** [comment] 2015-07-26 03:52
Duplicate of #245/#246.  This is a 5100 but presumably the underlying cause is the same for all of this.

**Closed as completed by gdrewb-valve** 2015-07-26 03:52 UTC
Labels: reviewed
