### ISSUE TITLE
[Linux] cl_showfps shows unrecognizable text

### ISSUE THREAD

**Issue by z0mbieprocess** [ValveSoftware/Dota-2#65] opened 2015-06-24 09:14 UTC
Arch Linux, Gnome 3.16, kernel 4.0.5, i5-2520M, intel HD3000, mesa 10.6 (patched with http://patchwork.freedesktop.org/patch/52603/ taken from https://github.com/ValveSoftware/Dota-2-Reborn/issues/23)

![screenshot from 2015-06-24 12-01-12](https://cloud.githubusercontent.com/assets/13030753/8326405/b7f50ff6-1a69-11e5-89e5-3d6279965764.png)

**Comment by chaserhkj** [comment] 2015-06-24 09:25
Same issue confirmed with Gentoo Linux 64bit, Intel HD4000 using mesa 10.5.6

Seems like a fontconfig issue?

**Comment by imirkin** [comment] 2015-06-24 15:04
I see these fontconfig warnings when I run Dota 2 Reborn:

    Fontconfig warning: "/storage/tmp/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
    Fontconfig warning: "/storage/tmp/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected

This corresponds to

                <test name="family">
                        <string>Bitstream Vera Sans</string>
                        <string>DejaVu Sans</string>
                </test>

Which I guess is illegal at least in my system fontconfig? For the record, that's fontconfig-2.11.1

Perhaps related to this fonts issue?

**Comment by gdrewb-valve** [comment] 2015-06-25 03:27
Those fontconfig warnings are harmless and are not the issue (I get them and my FPS counter draws correctly).  It's unclear what the problem is, but likely is a rendering issue.

**Comment by chaserhkj** [comment] 2015-06-25 07:03
Furthermore, I discover today that all the player names rendered in game play or game watching view (above the HP bar of heroes) have similar rendering issues.

**Comment by gdrewb-valve** [comment] 2015-06-27 22:37
Did the 6/26 update change anything?

**Comment by z0mbieprocess** [comment] 2015-06-28 08:50
not for me... cl_showfps is still showing the same

**Comment by chaserhkj** [comment] 2015-06-28 13:00
Nope, 6/26 update didn't change anything for me either.

**Comment by gdrewb-valve** [comment] 2015-06-29 21:15
Possibly related to #120.

**Comment by danginsburg** [comment] 2015-07-03 15:07
Is this fixed by the 7/2 update?

**Comment by chaserhkj** [comment] 2015-07-04 03:57
Nope, text renderings still remain the same

**Comment by danginsburg** [comment] 2015-08-19 14:57
I haven't been able to repro this, my best guess is a fontconfig issue, but I'm not sure.  It appears the font used to render cl_showfps is "Lucida Console" with outline.  Are you able to set FC_DEBUG=1 and run the game and pipe the output of stdout to a file and post it here?  For me, it appears the font it matches to is /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf

**Comment by gdrewb-valve** [comment] 2015-11-13 20:38
The November 13 update might help with this, do you see any change in behavior?

**Comment by gdrewb-valve** [comment] 2015-11-16 21:11
Closing pending confirmation that this is still active.

**Closed as completed by gdrewb-valve** 2015-11-16 21:11 UTC
Labels: reviewed
