### ISSUE TITLE
[MAC] Black Flickering/"Flying" Pixels on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by LinoleumRipper** [ValveSoftware/Dota-2#529] opened 2015-10-04 11:12 UTC
Hi!

During game i have black  "flying pixels" on screen constantly. My game's video settings are Basic Setting's "Fastest". However, if I turn "Additive Light Pass" or "Ambient Occlusion" or "Specular" ON the issue completely stops. These black things only appears on the actual game area (not on the HUD). Another interesting thing is, these pixels don't show up on screenshots...

I wouldn't like to turn those graphic settings on because they lower my FPS... 
Everything was ok before with Reborn it started with El Capitan update.

Thank you for help!

MY SYSTEM INFORMATION

Processor Information:
    Model:  Macmini7,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  Intel Iris

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xa2e
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.82" x 10.55"  (21.57" diag)
                                        47.8cm x 26.8cm  (54.8cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  952704 Mb
    Largest Free Hard Disk Block:  780053 Mb

**Comment by danginsburg** [comment] 2015-10-05 12:44
Given that Dota 2 Reborn was working fine on your machine prior to the OS X El Capitan update, please file a Radar with Apple.  It would be useful to hear if this issue is impacting any other users or whether it is specific to your hardware configuration.  I will see if I can repro it on similar hardware, but it does not sound like an application issue.  Also, does this happen in borderless window, desktop friendly fullscreen, and exclusive fullscreen mode?  If it only happens in certain modes that would be useful to know.

**Comment by LinoleumRipper** [comment] 2015-10-05 15:57
Thank you for reviewing my issue.

I tested all screen modes and the issue is still there.
Is there any graphical setting (even from console) that could change the way the game looks (like "Additive Light Pass" / "Ambient Occlusion" / "Specular") but not lower drastically my FPS? It might help

**Comment by danginsburg** [comment] 2015-10-05 15:57
If you can post a screenshot or video I might be able to wager a guess.

**Comment by Tele42** [comment] 2015-10-05 16:45
per the opening post: "Another interesting thing is, these pixels don't show up on screenshots..."

**Comment by LinoleumRipper** [comment] 2015-10-05 17:50
I'll make a video with my phone

**Comment by danginsburg** [comment] 2015-10-05 19:03
What do you have "Game Screen Render Quality" set to?  Can you see if setting it to 100% resolves the issue?  If so, I think I know what the problem is.

**Comment by LinoleumRipper** [comment] 2015-10-05 20:26
With 100% "Game Screen Render Quality" they still there but they are smaller. I found out if i set shadow quality to mid or higher it also solve the problem it might be some shadow issue.  I don't know those other settings "Additive Light Pass" / "Ambient Occlusion" / "Specular" has anything to do with shadow "settings" because the also make the black things disappear.

Changing "Texture Quality" does nothing with the problem.

I'll make picture or video tomorrow about the issue.

**Comment by ap0l0** [comment] 2015-10-05 20:47
![bug dota2](https://cloud.githubusercontent.com/assets/14894967/10293153/08a01398-6b81-11e5-99aa-f3c0a3dce468.png)

I have the same issue. Using "El Capitan" public release. Let me know if you need the crash log. 

Crash log: http://pastebin.com/qugJrPza

**Comment by danginsburg** [comment] 2015-10-05 21:04
@ap0l0 Please open another bug because this looks like a completely different issue.  Also, make sure you include your system info from Steam -> Help -> System Information. 

@LinoleumRipper I have not had any luck repro'ing your issue yet.  Please also post your game/dota/cfg/video.txt

**Comment by LinoleumRipper** [comment] 2015-10-06 16:42
@ap0l0 Unfortunately, it's a different issue.

@danginsburg 
Here's the video i made about the issue: https://youtu.be/HzYcJevmwVI

And my "video.cfg"
{
    "VendorID"      "32902"
    "DeviceID"      "2606"
    "setting.cpu_level"     "1"
    "setting.mem_level"     "2"
    "setting.gpu_mem_level"     "2"
    "setting.defaultres"        "1920"
    "setting.defaultresheight"      "1080"
    "setting.gpu_level"     "3"
    "setting.version"       "1"
    "setting.mindxlevel"        "92"
    "setting.maxdxlevel"        "92"
    "setting.dxlevel"       "92"
    "setting.knowndevice"       "1"
    "setting.fullscreen"        "0"
    "setting.coop_fullscreen"       "1"
    "setting.nowindowborder"        "1"
    "setting.mat_vsync"     "0"
    "setting.fullscreen_min_on_focus_loss"      "1"
    "setting.dota_cheap_water"      "1"
    "setting.r_deferred_height_fog"     "0"
    "setting.r_deferred_simple_light"       "0"
    "setting.r_ssao"        "0"
    "setting.cl_globallight_shadow_mode"        "0"
    "setting.r_dota_fxaa"       "0"
    "setting.r_deferred_additive_pass"      "0"
    "setting.dota_portrait_animate"     "0"
    "setting.r_deferred_specular_bloom"     "0"
    "setting.r_deferred_specular"       "0"
    "setting.dota_ambient_creatures"        "0"
    "setting.r_texture_stream_mip_bias"     "2"
    "setting.r_dota_normal_maps"        "0"
    "setting.r_dashboard_render_quality"        "0"
    "setting.shaderquality"     "0"
    "setting.recommendedheight"     "600"
    "setting.mat_viewportscale"     "0.555556"
    "setting.r_fullscreen_gamma"        "2.200000"
    "setting.useadvanced"       "0"
    "setting.aspectratiomode"       "1"
}

**Comment by danginsburg** [comment] 2015-10-07 17:56
Thanks for the video.  If anyone else runs into this issue please post your system specs to help us narrow this down.  The only theory I had on what might be causing it would have been fixed by "setting.mat_viewportscale" "1.0", but I know you already tried that and it didn't work.  For now, I'm not sure what the issue is.

**Comment by danginsburg** [comment] 2015-10-21 13:47
Since the flickering has only been reported by a single user, I don't yet feel it warrants filing a bug with Apple since it is not clear if this is specific to this system or a universal bug.  If anyone else observes this issue please post here and if we get more than one report I will file a Radar with Apple.  Closing for now.

**Closed as completed by danginsburg** 2015-10-21 13:47 UTC
Labels: reviewed
