### ISSUE TITLE
[linux] Full screen mode dont switch to lower resolution

### ISSUE THREAD

**Issue by biji** [ValveSoftware/Dota-2#452] opened 2015-09-16 16:54 UTC
my desktop resolution is 1920x1080
my dota setting is 1360x768 full screen
but when playing it looks like scaled window to my desktop resolution, and lower fps
my graphic card is amd r7 m260

my workaround is running: 
xrandr -s 1360x768
before playing dota, the result sharper image and higher fps

i hope dota2 can do this automatically

**Comment by danginsburg** [comment] 2015-09-17 14:51
Duplicate of #63.  Right now "Exclusive Fullscreen" is not supported on Linux due to undesirable side effects.

**Closed as completed by danginsburg** 2015-09-17 14:51 UTC
Labels: duplicate, enhancement, reviewed
