### ISSUE TITLE
[Linux] No hitpoints number on the hitbar above your hero

### ISSUE THREAD

**Issue by weirddan455** [ValveSoftware/Dota-2#151] opened 2015-06-28 02:15 UTC
I've attached a picture. Above Anti-Mage's hitbar there's supposed to be a number showing how many hitpoints he has but it's just a blank blue box. I've enabled the relevant option in settings. If I disable it the little blue box just goes away. It works on Source 1 and works on Source 2 in Windows. Seems to be a Source 2 Linux specific bug.

![hitpoints](https://cloud.githubusercontent.com/assets/8128047/8394861/9005ccba-1d11-11e5-864a-124594cb4559.jpg)

**Comment by ArnaudAndre** [comment] 2015-06-29 01:13
I have this too. Can't find other reports about it so it may be system specific.
My system specs [here](https://gist.github.com/ArnaudAndre/12d5204c9347ccc3e94b).

Not sure it's related but I also have no text renderred in the console. I can type stuff and it has effect. The little rectangle under the input box is from the text suggestion/autocompletion.
![broken console](http://images.akamai.steamusercontent.com/ugc/437195915659129166/F5AFF3B3D754653526B53739CA6DEF32476942B4/)

**Comment by weirddan455** [comment] 2015-06-29 02:47
My console works fine.  I was thinking my problem may be related to installed font pacakges (or lack thereof) if other Linux users weren't affected.  Maybe yours is too.  I currently have dejavu, droid, liberation, and symbola installed but not sure what else I might be needing.  I'm running Arch Linux.

**Comment by presianbg** [comment] 2015-06-29 03:25
I'm also affected of this bug.

**Comment by gdrewb-valve** [comment] 2015-06-29 20:44
Probably the same thing as #120.

**Comment by danginsburg** [comment] 2015-07-02 13:19
Duplicate of #120, closing.

**Closed as completed by danginsburg** 2015-07-02 13:19 UTC
Labels: duplicate, reviewed
