### ISSUE TITLE
Cannot display words

### ISSUE THREAD

**Issue by Dream-math** [ValveSoftware/Dota-2#683] opened 2015-12-16 04:22 UTC
![2015-12-16-121451_1366x768_scrot](https://cloud.githubusercontent.com/assets/9656696/11832064/87c21b20-a3ef-11e5-81ce-549a3ef109f8.png)
![2015-12-16-121451_1366x768_scrot](https://cloud.githubusercontent.com/assets/9656696/11832069/8f6c2d20-a3ef-11e5-8832-60a51b798558.png)
Need help
I play on fedora 20

**Comment by gdrewb-valve** [comment] 2015-12-16 04:58
There are several issues here that this is a duplicate of.  Your graphics driver is likely the problem.  Can you post your full system info from Steam?

**Comment by danginsburg** [comment] 2015-12-16 13:29
Yes, this looks like a well known bug with mesa on Intel.  Assuming that is the case, please update to mesa 10.5.9+.

**Comment by gdrewb-valve** [comment] 2015-12-19 03:30
Closing pending more info.

**Comment by Dream-math** [comment] 2015-12-19 12:18
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Whistler [Radeon HD 6630M/6650M/6750M/7670M/7690M]

fedora20

**Comment by gdrewb-valve** [comment] 2015-12-19 15:14
Can you post your full system information from Steam?  There's a System Information selection in the menu that gives you a bunch of text.

**Comment by Dream-math** [comment] 2015-12-19 15:37
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.8-100.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile 

```
Driver Version:  3.0 Mesa 10.3.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6741
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12.17" x 6.85"  (13.94" diag)
                                        30.9cm x 17.4cm  (35.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  3863 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  414512 Mb
    Largest Free Hard Disk Block:  349214 Mb

Installed software:

Recent Failure Reports:

**Comment by Tele42** [comment] 2015-12-20 01:46
@danginsburg's initial assessment still holds true, mesa version is older than a known render fix.

**Comment by Dream-math** [comment] 2015-12-20 01:58
OK, thanks, I will have a try.

**Comment by danginsburg** [comment] 2015-12-21 14:03
Yeah, definitely an issue with mesa 10.3.3.  Please update to 10.5.9+ it will fix the issue.

**Closed as completed by danginsburg** 2015-12-21 14:03 UTC
Labels: duplicate, reviewed
