### ISSUE TITLE
Can not join matchmaking lobby after Battle Pass update.

### ISSUE THREAD

**Issue by upwork-noj** [ValveSoftware/Dota-2#1748] opened 2020-05-25 23:33 UTC
* System information from steam: https://gist.github.com/upwork-noj/2f59578031e66dd8da46b9000eaae85e
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

I wasn't able to run Dota 2 after the battle pass update and was able to resolve it by switching to Vulkan. But now I can't join any matchmaking lobbies.

So I queue for a match and when it's found I accept it and when everyone accept the match it brings me back to Dota 2 main screen where I can "Reconnect" or "Abandon" the match. Reconnecting results the same thing, back to the main screen.

**Comment by Nmerey** [comment] 2020-05-26 00:36
Same issue here.
I have Mojave also tried -vulkan -vconsole.

**Comment by Nmerey** [comment] 2020-05-26 02:37
Quick follow up.
The problem is gone now. Maybe it was due to overload on servers traffic...

**Comment by kisak-valve** [comment] 2020-05-26 12:55
Hello @Nmerey, glad to hear you got connected. Closing per the last comment.

**Closed as completed by kisak-valve** 2020-05-26 12:55 UTC
