### ISSUE TITLE
DOTA 2 Crashed Multiple Times During A Normal Game in Mac OS

### ISSUE THREAD

**Issue by leowyq** [ValveSoftware/Dota-2#803] opened 2016-03-25 07:05 UTC
After the newest 1G update, me and some friend using Mac, during the game, DOTA2 Crashed Multiple Times. What Happened? Programming Issue?

**Comment by gdrewb-valve** [comment] 2016-03-25 07:16
Closing duplicate of #794.

**Closed as completed by gdrewb-valve** 2016-03-25 07:16 UTC
Labels: duplicate, reviewed
