### ISSUE TITLE
strange disconnect/reconnect bug

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#650] opened 2015-11-19 21:51 UTC
hi,
Since the last patch I am having a strange issue with get disconnected from the server.
In this instance the following happened:
I found a single queue game, one of the players in the other team had issues loading so as the timer hit 40 seconds I switched to my web browser for a moment and back again (in less than a second). It then showed in the top right corner the disconnecting in x message.
I checked my internet connecting and everything was just fine. I then got disconnected and successfully reconnected.
To my surprise I found my self alone in the game, this is what 'status' showed:

 ----- Status -----
@ Current  :  game
source   : slot 3
hostname : Valve Dota 2 Source 2 EU West Server (srcds008.133.90)
spawn    : 2
version  : 43/43 6958 secure  public
steamid  : [A:1:2289451015:6081](90098112532987911)
udp/ip   : 146.66.153.92:27104
sdt     :  =146.66.153.92:30104
os/type  : Linux dedicated
sourcetv : 146.66.153.92:28109 delay 120.0s
players  : 10 humans, 1 bots (0 max) (not hibernating) (unreserved)
---------spawngroups----
loaded spawngroup(  1)  : SV:  [1: dota | main lump | mapload]
loaded spawngroup(  2)  : SV:  [2: dota | world_layer_dire_base | <none> | world_layer]
loaded spawngroup(  3)  : SV:  [3: dota | world_layer_radiant_base | <none> | world_layer]
---------players--------
  id     time ping loss      state   rate name
   1      BOT    0    0     active      0 'SourceTV'
  12    00:21   50    0     active  80000 'Turmfalke'

So there should be 10 humans, but I am somehow alone. I was unable to pick a hero, because the clock was stuck at 0:00 and my opponents had first pick. I figured it might be a good idea to disconnect and reconnect again, but when I did so the reconnect button disappeared and instead I got the  "you are prevented from searching for 10minutes message".
What happened here? This cannot possibly be the correct behaviour?

**Comment by gdrewb-valve** [comment] 2015-11-19 23:22
I'll send this to the larger team and see what they say.

**Comment by gdrewb-valve** [comment] 2015-11-19 23:24
Also could be #360 as you did do an app switch.

**Comment by gdrewb-valve** [comment] 2015-11-19 23:50
The larger team found an issue with a small timing window that explains why you came back into an empty state.  They'll be taking a look at that.  The original reason you disconnected was probably because of #360 so I'm closing this as a duplicate of #360.

**Closed as completed by gdrewb-valve** 2015-11-19 23:50 UTC
Labels: reviewed
