### ISSUE TITLE
Steam downloading steam runtime while playing dota2

### ISSUE THREAD

**Issue by biji** [ValveSoftware/Dota-2#941] opened 2016-07-11 02:13 UTC
I hope Steam don't download steam runtime or anything while playing dota2 , last time I downloaded +200mb steam runtime, and lag while playing 

I'm using Fedora 24

**Comment by Tele42** [comment] 2016-07-11 04:41
Duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/2765.

**Comment by gdrewb-valve** [comment] 2016-07-11 08:04
Steam issues should be filed at steam-for-linux, but as Tele42 points out there's already something there.

**Closed as completed by gdrewb-valve** 2016-07-11 08:04 UTC
