### ISSUE TITLE
Quickcast bugged

### ISSUE THREAD

**Issue by Seigren** [ValveSoftware/Dota-2#2263] opened 2023-03-07 02:20 UTC
Quickcast hotkeys actually double cast spells if another if hotkey is bound
See setup below
![image](https://user-images.githubusercontent.com/127161622/223302416-84e4db50-dd8a-4d9f-9b81-bb54f6268527.png)
![image](https://user-images.githubusercontent.com/127161622/223302447-4bcc0272-9ddd-4ac9-a15c-9a8b6a46928e.png)
When tapping Q in this exemple, the press will count as two casts, and bring troll back to original stance of Berserker's Rage
Because pressing down seems to be counted as one cast, and release seems to be counted as another cast

**Comment by kisak-valve** [comment] 2023-03-07 02:36
Hello @Seigren, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/7196.

**Closed as not planned by kisak-valve** 2023-03-07 02:36 UTC

**Comment by Seigren** [comment] 2023-03-07 02:40
sorry new to github, didn't see my issue anymore so thought it had bugged out, thanks for notification
