### ISSUE TITLE
Game freeze with creep kills hero challenge

### ISSUE THREAD

**Issue by ivanpepelko** [ValveSoftware/Dota-2#1432] opened 2018-03-29 21:51 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/ivanpepelko/a40fe048d2e3e7eeebe7422bfbc6bdba)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
The game will freeze, as it at first seemed at random times; later I confirmed it be related to this hero challenge:
```
Kill 60/140/220 creeps, 15/25/35 of them must be Ancient Creeps.
```
Upon reaching certain milestone (creep kills or ancient kills) while this challenge is active, the game will freeze. I never wait for dota process to crash, though I kill -9'd dota in all occurrences to be able to return to game in time.

#### Steps for reproducing this issue:

1. Pick a hero with mentioned challenge available and select/activate the challenge
2. Reach a number of creep kills/ancient kills required to reach challenge milestone (and update note on top-left of the screen)
3. Game will freeze at the moment the counter needs to be increased

**Comment by gdrewb-valve** [comment] 2018-03-29 22:07
Duplicate of existing issues.

**Closed as completed by gdrewb-valve** 2018-03-29 22:07 UTC
Labels: duplicate, reviewed
