### ISSUE TITLE
[Linux] Open mic causes "mic open, no sound" icon to appear constantly

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#356] opened 2015-09-03 08:52 UTC
When I have open mic enabled, the transmission is working correctly now (yay!), but instead of disappearing whenever I stop talking, the "no sound" icon stays on the UI. (I tried to take a screenshot, but either my hotkey isn't working, or it's saving somewhere I can't find.)

**Comment by budimanjojo** [comment] 2015-09-03 09:03
Yes, I can confirm this. But I think this happens on all platform, not Linux specific.

**Comment by gdrewb-valve** [comment] 2015-09-03 16:14
I'm checking with the larger team.

**Comment by budimanjojo** [comment] 2015-09-04 13:36
Maybe this is connected to #316?

**Comment by chrylis** [comment] 2015-09-04 20:36
@budimanjojo I saw that one but don't think so. In this case, the icon appears completely correctly--it's just there when it shouldn't be, and looks more like the application is failing to shut off the mic when it falls below the threshold.

**Comment by budimanjojo** [comment] 2015-09-04 22:15
Yeah I know it's different, but I think there is something wrong with the codes of the mic button that causes these two problems.

**Comment by budimanjojo** [comment] 2015-09-14 11:08
@gdrewb-valve where are you bro?

**Comment by gdrewb-valve** [comment] 2015-09-14 13:12
Out for a few weeks, but I'll be back.

**Comment by gdrewb-valve** [comment] 2015-10-12 17:10
The larger team says that this is by-design, here's what they said.  If you disagree I can pass that back but I'm not sure anything will change.

This is a design change in Reborn to accommodate better communicate your mic behavior at all times. The “no sound” with open mic is there to communicate a few things all the time.
1.  That open mic is enabled.
2.  Whether you have open mic set to transmit to party or team.
3.  Your open mic threshold currently has you muted.

Without the “no audio” display for party open mic. Some users would report being unsure where their voice was going because their open mic tended to only show transmission during intense moments where they couldn’t explicitly pay attention to its party state.

With the addition of the “no audio” display. The party state could be transmitted to the user during downtime in the game.

**Comment by chrylis** [comment] 2015-10-12 17:51
If that's the intent, there needs to be substantially more visual distinction. The current "no audio" and "speaking" states aren't distinguishable from peripheral vision, where the previous nothing/icon setup was.

**Comment by gdrewb-valve** [comment] 2015-11-30 21:06
Closing as this is not a Mac/Linux specific issue.

**Closed as completed by gdrewb-valve** 2015-11-30 21:06 UTC
Labels: reviewed
