### ISSUE TITLE
[Linux] Periodic FPS drops with stutter

### ISSUE THREAD

**Issue by xrisk** [ValveSoftware/Dota-2#996] opened 2016-08-20 15:46 UTC
I have a Macbook Pro 2015 running Ubuntu on the i3 window manager. I have all settings on low, with 1280x800 resolution. FPS is usually at 60 except that it goes down to 10 or so every 5 seconds, causing stutter. This makes it pretty much impossible to play...

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 16.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-34-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Iris 6100 (Broadwell GT3) x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.2.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x162b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 2560 x 1600
    Primary Display Size: 11.26" x 7.05"  (13.27" diag)
                                            28.6cm x 17.9cm  (33.7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Broadwell HDMI

Memory:
    RAM:  7885 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_IN
    Microphone:  Not set
    Total Hard Disk Space Available:  227015 Mb
    Largest Free Hard Disk Block:  180577 Mb
    VR Headset: None detected

Recent Failure Reports:

```

My video.txt :

```
"video.cfg"
{
    "VendorID"      "32902"
    "DeviceID"      "5675"
    "setting.cpu_level"     "0"
    "setting.mem_level"     "2"
    "setting.gpu_mem_level"     "2"
    "setting.defaultres"        "1280"
    "setting.defaultresheight"      "800"
    "setting.gpu_level"     "3"
    "setting.version"       "1"
    "setting.mindxlevel"        "92"
    "setting.maxdxlevel"        "92"
    "setting.dxlevel"       "92"
    "setting.knowndevice"       "1"
    "setting.fullscreen"        "0"
    "setting.coop_fullscreen"       "1"
    "setting.nowindowborder"        "0"
    "setting.mat_vsync"     "0"
    "setting.fullscreen_min_on_focus_loss"      "1"
    "setting.dota_cheap_water"      "1"
    "setting.r_deferred_height_fog"     "0"
    "setting.r_deferred_simple_light"       "0"
    "setting.r_ssao"        "0"
    "setting.cl_globallight_shadow_mode"        "0"
    "setting.r_dota_fxaa"       "0"
    "setting.r_deferred_additive_pass"      "0"
    "setting.dota_portrait_animate"     "0"
    "setting.r_deferred_specular_bloom"     "0"
    "setting.r_deferred_specular"       "0"
    "setting.dota_ambient_creatures"        "0"
    "setting.dota_ambient_cloth"        "0"
    "setting.r_texture_stream_mip_bias"     "2"
    "setting.r_dota_normal_maps"        "0"
    "setting.r_dashboard_render_quality"        "0"
    "setting.shaderquality"     "0"
    "setting.recommendedheight"     "600"
    "setting.mat_viewportscale"     "0.504142"
    "setting.r_fullscreen_gamma"        "2.200000"
    "setting.useadvanced"       "1"
    "setting.aspectratiomode"       "2"
}
```

What can I do to fix this? I did not have such FPS drops on OS X.

**Comment by gdrewb-valve** [comment] 2016-08-20 16:49
It's unclear what the problem is.  We'll have to see if enough people have it happen that we can see some kind of pattern.

If you turn off the Steam overlay does that change anything?

**Comment by xrisk** [comment] 2016-08-21 01:27
It's already turned off. Are there any more logs I can provide? Also, the problem persists even if I switch to using Unity instead of i3.

**Comment by gdrewb-valve** [comment] 2016-08-21 06:06
It depends on how deep you want to go.  I would check system perf tools and see if you can see a surge in network or disk traffic that correspond to the hitches.  Net sniffer and/or strace might be useful if you're familiar with them enough to remove standard traffic and see anything unusual.

Otherwise we'll wait and see if other people have similar issues.

**Comment by krutoileshii** [comment] 2016-10-14 05:28
Seems like a similar issue becomes a complete slideshow especially when hitting mega creep stages. 
it's been happening since the last 3 updates. will try Vulcan and see if that creates any difference. 

On fedora here. never had an issue before this.

playing on Core i7 i7-4790K 660 TI as well as a samsung SSD EVO 850. 1080P

**Comment by gdrewb-valve** [comment] 2016-12-13 21:57
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.

**Closed as completed by gdrewb-valve** 2016-12-13 21:57 UTC
Labels: reviewed
