### ISSUE TITLE
[Linux] Verify integrity of game cache causing client redownload

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#617] opened 2015-10-28 10:11 UTC
Hi,

There is sometimes my courier become ERROR, so I think there are issue on my client cache.

When I verify integrity of game cache, it said around 4k of file need to be acquired causing downloading 6.8 GB of file.

This happen to me before using a copy and paste dota 2 beta folder from my external, so I remove it back and redownload back the client, but I still sometimes found the ERROR ward,courier thing even in fresh install, so I verify back and the same thing happen, 4k file need to be acquired and need to redownload 6.8 GB of file.

**Comment by gdrewb-valve** [comment] 2015-10-28 16:46
Can you put up a gist of your content_log.txt after starting Steam and doing the validate?  I'll pass it on to the Steam team.

**Comment by rained23** [comment] 2015-10-29 12:00
https://gist.github.com/rained23/5d788bac1d7f9d198d3c

**Comment by gdrewb-valve** [comment] 2015-10-29 18:09
I've sent it on.

**Comment by gdrewb-valve** [comment] 2015-10-29 18:19
This line apparently shows the issue but not the reason:

[2015-10-28 17:45:07] Validation: file locked "/home/xxxxxx/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/pak01_081.vpk"

Validation can't open the given file so it fails and will revalidate the next time you try it.  Does that file exist on disk?  In particular is the exact case of the file path correct?  If it's correct could anything else be accessing those files?

**Comment by gdrewb-valve** [comment] 2015-10-29 18:29
Is Reborn running while you're validating?  If you exit it and validate to things work?

**Comment by gear4s** [comment] 2015-11-01 19:11
paste the output of this command in GitHub:

> lsof /home/xxxxxx/.local/share/Steam/steamapps/common/dota\ 2\ beta/game/dota/pak01_081.vpk

it allows us to see which process is locking the file (maybe Reborn, it's known for me that it doesn't close properly)

**Comment by rained23** [comment] 2015-11-02 15:15
Verify integrity was made on fresh install of reborn, so I am not sure the file didn't exist or not before, and no, reborn isn't running during verify integrity. I already downloaded the 6.8 GB and I will need a better time to test back another verify cause I afraid its gonna redownload the 6.8 GB file again.

If anyone on Linux with fast internet might can help testing this , this is how to reproduce:
1. Delete Dota 2 from disk ( if installed).
2. Fresh install Dota 2.
3. Run entire update.
   3.a. Maybe try play some game
4. Verify Integrity.

I am not sure if this happen to my machine only, but even it is, I think its something on Steam probably because this verify integrity been made on Fresh Install.

**Comment by gear4s** [comment] 2015-11-02 20:15
couldn't reproduce on my PC. also please read my comment above

**Comment by Tele42** [comment] 2015-11-03 02:31
This has the same smell as some old, known filesystem-related quirks with steam. What filesystem is your home folder on?

**Comment by rained23** [comment] 2015-11-03 13:20
ext4

**Comment by Tele42** [comment] 2015-11-03 16:00
@rained23 is there any encryption involved?

**Comment by rained23** [comment] 2015-11-04 00:41
Yes, my home folder is encrypted.

But I think Steam will have the decrypted version of my file.

Unless steam doing informal way of it.

**Comment by Tele42** [comment] 2015-11-04 01:19
That makes this issue report a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/2515.

**Comment by gdrewb-valve** [comment] 2015-11-04 01:22
Thanks for the pointer, closing.

**Closed as completed by gdrewb-valve** 2015-11-04 01:22 UTC
Labels: reviewed
