### ISSUE TITLE
[OSX] Hotkeys disabled in game, cmd+ click to interact with GUI

### ISSUE THREAD

**Issue by itixonal** [ValveSoftware/Dota-2#386] opened 2015-09-09 21:27 UTC
My keyboard is more or less disabled in Reborn, and in order to effectively click on any button or interact with the game at all I have to hold cmd while I click.

**Comment by davidw-valve** [comment] 2015-09-10 01:11
Can you please be more specific? Does the keyboard not work at all? What works and what doesn't work for you? Also what are your system specs?

**Comment by vsethuooo** [comment] 2015-09-11 14:14
Faced the same issue. I'm using Mac OSX. I thought this was a bug, and was using the previous version of Dota 2 (the one before Reborn). But now, since Dota2Reborn is enforced, I'm facing a problem. As soon as the game is launched, single click doesn't work. For every section/selection I've to double click. The keyboard doesn't work.

In-game: Worst game ever for me. The map doesn't scroll when you move mouse to end of screen. Array keys don't work (I mean, the keyboard doesn't work). Right click works normal. But left click doesn't work. I got a gaming mouse, so, there's 4th a button i've not configured, and for some strange reason, that works fine as left click.

Also, no sound, right since I launch Dota-2 reborn.

**Comment by gramathy** [comment] 2015-09-15 03:51
Sounds like #238 to me. Try to unfocus the game with cmd-H, then go back to the game and see if it captures everything normally?

Big giveaway for this is the mouse cursor looking like the system cursor and not the dota cursor.

**Comment by gdrewb-valve** [comment] 2015-10-12 16:09
Closing assuming that this is a duplicate of #238.

**Closed as completed by gdrewb-valve** 2015-10-12 16:09 UTC
Labels: reviewed

**Comment by vsethuooo** [comment] 2016-07-03 14:29
I'm not sure if this an OS issue. But tapping the Shift key, 5 times fixes it! :D Just putting it here, it might help someone who is facing the same issue.
