### ISSUE TITLE
[Linux] The game sometimes does not quit

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#661] opened 2015-11-28 20:17 UTC
Hi there,

This issue has been around for a really long time and it's pretty bothering.

Sometimes when I click on the Exit button in the game, and confirm the quit, the game freezes and won't quit.

I have to use the "**kill -9**" command to actually make it quit. (The regular "kill" and other force-kill options do not work properly. With other solutions, the window itself disappears but Steam will still detect DOTA 2 running.)

Currently I'm using Ubuntu 15.10 with Unity, however, this was an issue with 14.04 (also Unity) as well.

Usually when I don't actually play a game, just start the menu to check my items or something, DOTA manages to quit by itself.

[Here is a Gist containing my System Information](https://gist.github.com/helix42/895352598fb5cef94952)

**Comment by budimanjojo** [comment] 2015-11-29 11:14
Happened to me too, but will quit itself after 3 to 5 seconds later

**Comment by gdrewb-valve** [comment] 2015-11-30 04:52
Duplicate of #603.

**Closed as completed by gdrewb-valve** 2015-11-30 04:52 UTC
Labels: duplicate, reviewed
