### ISSUE TITLE
Dota 2 Reborn Ubuntu 15.04 Not Working

### ISSUE THREAD

**Issue by realbyx** [ValveSoftware/Dota-2#220] opened 2015-07-07 18:45 UTC
I use Version 15.04 Ubuntu. I have no problems wıth usage of Dota 2 but Dota 2 Reborn.
It crashes after I see its logo on screen. The game's logs are in the below

https://gist.github.com/90a1de2d9ea0d623bc04.git

<script src="https://gist.github.com/realbyx/90a1de2d9ea0d623bc04.js"></script>

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-22-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.7.0-devel (git-ff0a41b 2015-07-04 vivid-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x11a1
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 13,58" x 7,64"  (15,55" diag)
                                        34,5cm x 19,4cm  (39,5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  15940 Mb

Miscellaneous:
    UI Language:  English
    LANG:  tr_TR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  96021 Mb
    Largest Free Hard Disk Block:  21452 Mb

Installed software:

Recent Failure Reports:

Game update: AppID 570 "Dota 2", ProcID 3041, IP 0.0.0.0:0
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
pid 3054 != 3053, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198075820721 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198075820721
Setting breakpad minidump AppID = 373300
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Installing breakpad exception handler for appid(gameoverlayui)/version(20150604103636)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
ATTENTION: default value of option vblank_mode overridden by environment.
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/home/realbyx/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/realbyx/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Hero npc_dota_hero_antimage has no HeroID defined.  This will break stats tracking!Error: VerifyHeroIDs():
Hero npc_dota_hero_antimage has no HeroID defined.  This will break stats tracking!
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 670MX/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Game removed: AppID 570 "Dota 2", ProcID 3056 

```
Write Preview 
```

Parsed as Markdown Edit in fullscreen

**Comment by realbyx** [comment] 2015-07-07 19:55
Dmp files:

Running Steam on ubuntu 15.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1433441724)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0707/225726:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433414140)
[0707/225726:ERROR:nss_util.cc(981)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)

*\* (steam:7776): WARNING **: Unknown device type 14

*\* (steam:7776): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type
Installing breakpad exception handler for appid(steam)/version(1433441724)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Adding licenses for the following package(s): 0, 17250, 21292, 21327, 21337, 21353, 21423, 21430, 36804, 44226, 47159, 48901, 69835, 70012, 71953, 71956, 71957, 71958, 71961, 71962, 71975
roaming config store loaded successfully - 797 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/realbyx/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1433441724)
System startup time: 4,18 seconds
Generating new string page texture 70: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 71: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 72: 64x256, total string texture memory is 507,90 KB
Running Steam on ubuntu 15.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/realbyx/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/realbyx/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 80: 256x256, total string texture memory is 393,22 KB
[0707/225732:ERROR:renderer_main.cc(212)] Running without renderer sandbox
Generating new string page texture 94: 128x256, total string texture memory is 638,98 KB
Generating new string page texture 95: 384x256, total string texture memory is 1,03 MB
Generating new string page texture 96: 32x256, total string texture memory is 1,06 MB
Generating new string page texture 98: 24x256, total string texture memory is 1,09 MB
Generating new string page texture 126: 128x256, total string texture memory is 1,22 MB
Game update: AppID 570 "Dota 2", ProcID 7944, IP 0.0.0.0:0
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
pid 7959 != 7958, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ERROR: ld.so: object '/home/realbyx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198075820721 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198075820721
Setting breakpad minidump AppID = 373300
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Installing breakpad exception handler for appid(gameoverlayui)/version(20150604103636)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
ATTENTION: default value of option vblank_mode overridden by environment.
Fontconfig warning: "/home/realbyx/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/realbyx/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Hero npc_dota_hero_antimage has no HeroID defined.  This will break stats tracking!Error: VerifyHeroIDs():
Hero npc_dota_hero_antimage has no HeroID defined.  This will break stats tracking!
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 670MX/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Game removed: AppID 570 "Dota 2", ProcID 7961

**Comment by gdrewb-valve** [comment] 2015-07-08 05:14
This is a duplicate of #41, starting in the Turkish locale causes a problem.  If you switch LANG to en_US.UTF-8 the game should start.

**Closed as completed by gdrewb-valve** 2015-07-08 05:14 UTC
Labels: duplicate, reviewed
