### ISSUE TITLE
Frequent crashes while loading matches for viewing

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#973] opened 2016-08-04 01:29 UTC
Dota client is crashing rather frequently while trying to connect to a game to watch on both of my systems. 

System information 1:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 16.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-31-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.2.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6601
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 12.17" x 6.81"  (13.94" diag)
                                            30.9cm x 17.3cm  (35.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15944 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  223967 Mb
    Largest Free Hard Disk Block:  41807 Mb
    VR Headset: None detected

    Tue Aug  2 21:58:44 2016 GMT: file ''/tmp/dumps/crash_20160803075739_1.dmp'', upload yes: ''Discarded=1''
    Wed Aug  3 23:01:10 2016 GMT: file ''/tmp/dumps/crash_20160804084008_1.dmp'', upload yes: ''Discarded=1''
    Thu Aug  4 01:24:57 2016 GMT: file ''/tmp/dumps/crash_20160804112052_1.dmp'', upload yes: ''Discarded=1''
```

System information 2:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  4301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-80-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.63
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1080
    Primary Display Size: 20.47" x 11.42"  (23.43" diag)
                                            52.0cm x 29.0cm  (59.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7968 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104566 Mb
    Largest Free Hard Disk Block:  10520 Mb
```

**Comment by vadi2** [comment] 2016-08-04 01:54
Note that I alt+tab out of the game while it is connecting to the game.

**Comment by gdrewb-valve** [comment] 2016-08-04 02:51
Duplicate of #918 / #922.

**Closed as completed by gdrewb-valve** 2016-08-04 02:51 UTC
