### ISSUE TITLE
[Linux] Show Dota 2 as a seperate program in Unity launcher bar

### ISSUE THREAD

**Issue by Veske** [ValveSoftware/Dota-2#660] opened 2015-11-27 21:01 UTC
Currently, when you launch Dota 2, it will be completely random, if it actually shows as a separate program in the Unity launcher or not. 

The trend I see is that if it does decide that it's a good time to show, then it will do so until the computer is restarted. Same goes for the opposite situation.

![screenshot from 2015-11-27 22-50-49](https://cloud.githubusercontent.com/assets/5602603/11448106/8a107816-955a-11e5-9d32-3f1ba1688987.png)
![screenshot from 2015-11-27 22-57-25](https://cloud.githubusercontent.com/assets/5602603/11448107/8a10e24c-955a-11e5-8fbd-b2536a8216f4.png)

As you can see, on one picture I have Dota 2 as a separate program listen in the menu and on the other one after restarting the computer, it's merged under Steam program.

It would be nice if there would be some consistency here. Either it always is merged or it always is seperate. Or better yet...  make it configurable!

My specs:
Ubuntu 15.10 64 bit
Nvidia 760 with 352.63 driver
Intel i5-4570

EDIT:  Seems that it can occur also when after restart the game is shown separate. Then you have to close steam again and reopen it. It should start merging then.

**Comment by gdrewb-valve** [comment] 2015-11-30 04:51
Duplicate of #655.

**Closed as completed by gdrewb-valve** 2015-11-30 04:51 UTC
Labels: duplicate, reviewed
