### ISSUE TITLE
[Mac] OS X: Game shortcuts doesn't work in another language

### ISSUE THREAD

**Issue by Shchvova** [ValveSoftware/Dota-2#467] opened 2015-09-19 13:04 UTC
None of the abilities or other shortcuts work if keyboard layout is in other than english layout. This make game practically unplayable if you trying to chat in other than English. Potentially clone of #421

**Comment by danginsburg** [comment] 2015-10-08 13:53
Duplicate of #473?  Does -input_button_code_is_scan_code on the command-line resolve the issue?

**Comment by gdrewb-valve** [comment] 2015-10-12 17:32
Definitely a duplicate, closing.

**Closed as completed by gdrewb-valve** 2015-10-12 17:32 UTC
Labels: duplicate, reviewed

**Comment by Shchvova** [comment] 2015-10-12 19:05
Thanks @danginsburg. It works. Pity you have to do some magic for a game to work. Ty!
