### ISSUE TITLE
Some trees are much darker in Linux than on Windows

### ISSUE THREAD

**Issue by rodlorric** [ValveSoftware/Dota-2#56] opened 2015-06-24 00:29 UTC
As shown in these screenshots below some trees are much darker on Linux, almost black.

Linux
![Linux](http://i.imgur.com/0DvFSk1.jpg)

Windows
![Windows](http://i.imgur.com/6wXtSBx.jpg)

These very dark trees are very common on the Dire side of the map.
*Edit. Grammar

**Comment by danginsburg** [comment] 2015-06-24 13:44
I'm inferring from your other bug #52 that this is your system configuration.  Correct? 

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2668 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,98" x 12,28"  (24,29" diag)
                                            53,3cm x 31,2cm  (61,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1200
    
Memory:
    RAM:  5958 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  100564 Mb
    Largest Free Hard Disk Block:  26705 Mb
```

**Comment by sphexing** [comment] 2015-06-24 15:29
Yes, that is correct.

**Comment by danginsburg** [comment] 2015-06-24 18:40
I was able to repro this bug.  It turns out it has the same cause as #52 and is fixed by the same resolution.  Marking as a duplicate of #52 and closing.  The fix will be in the next update.

**Closed as completed by danginsburg** 2015-06-24 18:40 UTC
Labels: duplicate, reviewed
