### ISSUE TITLE
[LINUX] game doesn't lock cursor

### ISSUE THREAD

**Issue by jackmitch** [ValveSoftware/Dota-2#1056] opened 2016-10-22 16:25 UTC
I'm not sure which update exactly broke it but at least on ArchLinux the game now no longer locks the cursor to the screen when playing a match. Edge panning works, but the mouse can navigate to the other monitor. I run it in 'Desktop Friendly Fullscreen Mode' however the same issue happens in windowed and borderless window. Never had an issue before with this for the past 2 years.

**Comment by ramma** [comment] 2016-10-22 16:40
My understanding is this is expected, since the source 2 update no longer has true fullscreen. That's at least what happens with modifier keys being passed to the desktop, which is still an issue.

**Comment by Tele42** [comment] 2016-10-22 17:30
My memory seems to recall that desktop friendly fullscreen should capture the mouse during the match, but not when in the main menu. I can confirm the mouse is not captured when watching a live match.

**Comment by gdrewb-valve** [comment] 2016-10-22 21:51
@jackmitch, to be clear your are talking about while you're in the game and not in the menu, correct?

**Comment by jackmitch** [comment] 2016-10-23 07:52
Yes, this is in game. I did a bit more experimenting and it seems it may have something to do with the update to Gnome 3.22. I tried out a different window manager (i3) and the pointer locking was working. I haven;t played for a few weeks so both Dota and Gnome were updated in tandem so I can't be sure that it was _only_ the Gnome update which broke it, but as it works in other desktop environments it's looking pretty likely. Gnome 3.22 was only released a couple of weeks ago so I expect more people will be along soon as they upgrade.

**Comment by Tele42** [comment] 2016-10-23 11:54
hmm ... in my case the DE is Cinnamon 3.0.

**Comment by jackmitch** [comment] 2016-10-24 18:23
OK, I figured this out. Gnome 3.22 defaults to using Wayland. Wayland hasn't yet had pointer lock implemented, hence it doesn't work. I hadn't realised that the default had changed automatically from an X11 session to being a Wayland session on upgrade.

**Comment by gdrewb-valve** [comment] 2016-10-27 15:02
Sounds like this isn't a Dota issue then?

**Comment by gdrewb-valve** [comment] 2016-10-29 15:43
Closing as this doesn't seem to be a Dota issue.

**Closed as completed by gdrewb-valve** 2016-10-29 15:43 UTC
Labels: reviewed

**Comment by Faraclas** [comment] 2017-03-16 16:51
This is a Dota issue (I have the same issue). I am also using gnome 3.22 but am using X11 not Wayland (gentoo).  I just noticed this issue over the past week.

**Comment by Cabanur** [comment] 2017-03-16 17:16
Works properly on KDE with X11 in my Debian Testing system.
