### ISSUE TITLE
After getting into REBORN. Keep getting this message when I try to get in a game or try spectating 

### ISSUE THREAD

**Issue by jxyang131** [ValveSoftware/Dota-2#402] opened 2015-09-10 23:38 UTC
bool CNetworkSystem::OpenSocketInternal(int, int, int, const char *, int, bool)():
Couldn't allocate any client IP port, tried 1 addresses

please help!
heres my system information: 
Processor Information:
    Model:  MacBookAir6,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 5000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0xa26
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 11.42" x 7.09"  (13.43" diag)
                                        29.0cm x 18.0cm  (34.1cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114560 Mb
    Largest Free Hard Disk Block:  61613 Mb

Installed software:
    Adobe Reader
    App Store
    Automator
    Calendar
    Contacts
    Dota 2
    Dropbox
    Equation Editor
    FaceTime
    Game Center
    Google Chrome
    iBooks
    Image Capture
    Install Spotify
    Keynote
    Launchpad
    Maps
    Messages
    Microsoft Alerts Daemon
    Microsoft Chart Converter
    Microsoft Clip Gallery
    Microsoft Communicator
    Microsoft Database Daemon
    Microsoft Database Utility
    Microsoft Document Connection
    Microsoft Excel
    Microsoft Graph
    Microsoft Language Register
    Microsoft Messenger
    Microsoft Office Reminders
    Microsoft Office Setup Assistant
    Microsoft Outlook
    Microsoft PowerPoint
    Microsoft Query
    Microsoft Upload Center
    Microsoft Word
    MiniTerm
    Mission Control
    Movist
    My Day
    Notes
    Numbers
    OBS
    Office365Service
    Open XML for Excel
    Pages
    Photos
    Reminders
    Remote Desktop Connection
    Skype
    Solver
    Spotify
    Steam
    Stickies
    Symantec Endpoint Protection Installer
    SyncServicesAgent
    SyphonInject
    uTorrent
    XpressConnect

**Comment by gdrewb-valve** [comment] 2015-10-12 16:25
Duplicate of #294.

**Closed as completed by gdrewb-valve** 2015-10-12 16:25 UTC
Labels: reviewed
