### ISSUE TITLE
Server crash abuse 

### ISSUE THREAD

**Issue by mydeardota** [ValveSoftware/Dota-2#2838] opened 2024-10-26 09:05 UTC
#### Steps for reproducing this issue:

1.  Today I had one more server crash
game id 8004086603 and 8000820086 
the person who crashed the server 1220003663 and his friend 294789305
2.  They dissconnect at the same time (at least 2 from dire team and 1 from opposite team)
3.  Server crashing

**Comment by kisak-valve** [comment] 2024-10-26 13:18
Hello @mydeardota, please do not intentionally open duplicate issue reports. This issue tracker is limited to issues with the Mac and Linux Dota 2 client.

Closing as a duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/22445.

**Closed as not planned by kisak-valve** 2024-10-26 13:18 UTC
