### ISSUE TITLE
[Mac] Vsync kills frame rate

### ISSUE THREAD

**Issue by Najadorel** [ValveSoftware/Dota-2#206] opened 2015-07-03 21:44 UTC
When Sync is active frame rate drops bellow 20 fps and when is disable I get 100 FPS, this is a a new issue than wasn't happening before.

I'm playing on a:
  Model Name:   MacBook Pro 11,3
  Processor Name:   Intel Core i7
  Processor Speed:  2.5 GHz
  Video Card: NVIDIA GeForce GT 750M 2GB
  Memory:   16 GB

**Comment by ssnl** [comment] 2015-07-07 05:37
I also experienced this.

**Comment by danginsburg** [comment] 2015-07-13 15:44
Does this happen both in fullscreen and windowed mode?  What resolution and settings?  I haven't been able to repro this on any of my Macs here.  Vsync behaves as I would expect (capping the framerate at the vertical refresh rate).

**Comment by Najadorel** [comment] 2015-07-13 17:51
In full screen resolution 1920x1200

**Comment by jeanlain** [comment] 2015-07-21 20:20
I too have described this issue with additional details. 
https://github.com/ValveSoftware/Dota-2-Reborn/issues/248

**Comment by danginsburg** [comment] 2015-09-29 19:51
Duplicate of #248.  Closing.  I'm about to post an update there.

**Closed as completed by danginsburg** 2015-09-29 19:51 UTC
Labels: duplicate, reviewed
