### ISSUE TITLE
Exclusive full screen does not work properly after Dueling fate updates

### ISSUE THREAD

**Issue by bojunwu** [ValveSoftware/Dota-2#1333] opened 2017-11-01 01:09 UTC
I'm using the 2017 15-inch Macbook Pro with Radeon 560 graphics card + i7-7820HQ and 16GB of RAM. For stability issue I'm using the lastest Mac OS Sierra, no high sierra yet. This is what I see when I launch the game today after the updates.
Desktop-friendly full screen works but the resolution is so low on a retina display.
<img width="1440" alt="screen shot 2017-10-31 at 6 05 41 pm" src="https://user-images.githubusercontent.com/9892226/32255605-77b2d592-be66-11e7-99cc-0a74bd1b987b.png">

**Comment by bojunwu** [comment] 2017-11-01 01:10
This is a FULL screen screenshot.

**Comment by webquali** [comment] 2017-11-01 16:34
I have the same macbook and the same problem. I reinstall steam and dota but problem not leave.
And also I don't have real full screen. If I move mouse to left top corner I have call Dshboard
<img width="1680" alt="2017-11-01 18 33 46" src="https://user-images.githubusercontent.com/2962899/32285530-3e13d822-bf33-11e7-8e1b-095d293bcacd.png">

**Comment by macbook15** [comment] 2017-11-01 19:10
the same MacBook the same problem, that's too upset

**Comment by macbook15** [comment] 2017-11-01 19:25
the screen resolution is 2880*1800,but only 1440 resolutions can be used properly, if use 2880 with a -fullscreen code, the mouse can't click the right side of the screen, it's disaster, the game has been ruined by the new patch.

**Comment by bojunwu** [comment] 2017-11-02 20:32
As of Nov/2 the bug has not yet been fixed. Only part of the game is displayed on the screen.
<img width="1440" alt="screen shot 2017-11-02 at 1 28 04 pm" src="https://user-images.githubusercontent.com/9892226/32348791-2cb3a220-bfd2-11e7-9ae7-2ed28f88b6d2.png">

**Comment by webquali** [comment] 2017-11-03 15:45
Hey Valve any updates?

**Comment by Oxidian2005** [comment] 2017-11-04 13:59
+1

Mac pro here

10.12.5

3,7 GHz Quad-Core Intel Xeon E5
12GB 1866 MHz DDR3
AMD Fire Pro D500 3072 MB

**Comment by jeffreythen** [comment] 2017-11-05 02:41
I have the same problem here.
iMac 4k
![img_0016](https://user-images.githubusercontent.com/33385113/32411460-cbedf008-c215-11e7-9772-dbd5c313a815.JPG)
Please help!!!

**Comment by natbro** [comment] 2017-11-06 19:32
@Oxidian2005 - what type of monitor are you using on your Mac Pro? we haven't yet been able to reproduce this on a variety of different machines but are trying to do so asap.

**Comment by webquali** [comment] 2017-11-06 19:40
I have the same @jeffreythen  problem on my macbook pro 15 2017

**Comment by Oxidian2005** [comment] 2017-11-06 21:44
@natbro I use one 27’ Mac monitor. The thing is that even in exclusive full screen it is windowed and mac hot corners and dashboard still in use. Don’t think it has to do with actual resolution of size of the screen.

**Comment by bojunwu** [comment] 2017-11-06 22:09
I have two 15-inch Macbook Pros. Both machines have discrete GPU. I only have this issue on the one with Mac OS sierra 10.12.6. The other one has high sierra 10.13.1 and it works just fine. But there is another issue with high sierra(GPU performance drop significantly after sleep) so I want to keep one of my laptop at sierra for now.

**Comment by webquali** [comment] 2017-11-06 22:16
I have Hight Sierra and have really low fps 13

**Comment by bojunwu** [comment] 2017-11-06 22:21
@webquali restart the machine solves the low fps issue for me. But it will come back everytime I put it in sleep mode. Guess it's an issue with high sierra.

**Comment by webquali** [comment] 2017-11-06 23:13
@bojunwu the same problem

**Comment by Oxidian2005** [comment] 2017-11-07 11:49
@bojunwu I had Sierra and updated to high sierra to see if it solved the problem. But fps still messed up and there isn’t exclusive full screen.

**Comment by danginsburg** [comment] 2017-11-07 23:16
We are still having trouble getting a repro for this here.  For those having the problem, can you please post:

* What is resolution of your desktop?
* What is the exact video setting you are using? (i.e. Exclusive Fullscreen - 2880x1800)?
* Steam -> Help -> System Information

Right now we don't have a repro.  We'll need to get one to figure it out.

**Comment by bojunwu** [comment] 2017-11-07 23:38
@danginsburg  Thanks for the reply.
![img_0294](https://user-images.githubusercontent.com/9892226/32523658-812d2488-c3d9-11e7-9e68-1c6f8183750d.JPG)

My desktop resolution is 2880x1800
Video settings are shown in the pic, in case the picture is not clear enough, the settings are: User Advanced Settings, Aspect Ratio 16:10, size 2048x1280(I tried to change this but it doesn't solve the problem),Display Mode Exclusive Fullscreen. Effects are most on and qualities are all high. Rendering quality is 100%.

System info:

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro14,3
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.12.6 (64 bit)

Video Card:
    Driver:  Radeon Pro 560
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x1002
    DeviceID:  0x67ef
    Revision:  0xc0
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11" (15.31" diag)
                                            33.1cm x 20.6cm (38.9cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  476182 Mb
    Largest Free Hard Disk Block:  224008 Mb
    VR Headset: None detected

**Comment by ericliu123** [comment] 2017-11-08 10:25
Same issue please fix valve!!!!

**Comment by danginsburg** [comment] 2017-11-08 13:12
Thanks, I was able to get this repro'd.  It appears to be a regression in SDL which I am investigating.  As a temporary workaround, you could replace ~/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/libSDL2-2.0.0.dylib with the attached version.

We'll work on getting a real fix though.

[libSDL2-2.0.0.dylib.tar.gz](https://github.com/ValveSoftware/Dota-2/files/1453967/libSDL2-2.0.0.dylib.tar.gz)

**Comment by bojunwu** [comment] 2017-11-08 14:04
@danginsburg 
Thank you. It's working. Will replacing this file affect future update of this game ?

**Comment by danginsburg** [comment] 2017-11-08 14:07
@bojunwu If you Verify Game Cache it will replace it with the original version.  It also will get replaced on a future update once we fix it.  Hopefully we'll have a proper fix soon, I will update the bug when we do.

**Comment by danginsburg** [comment] 2017-11-08 14:38
Actually, here is a better workaround: add -gl_osx_check_display_mode to your Launch Options in Steam.  That should work with the most recent SDL that we shipped.  Still root causing it here...

**Comment by bojunwu** [comment] 2017-11-08 15:05
Thanks for the help. It works perfectly for me now.

**Comment by danginsburg** [comment] 2017-11-08 19:07
The specific SDL commit that is causing the problem is this one:

http://hg.libsdl.org/SDL/rev/1e26564c7288

The problem is that after that change, CGDisplaySetDisplayMode fails in Cocoa_SetDisplayMode with kCGErrorFailure.  The following is also output:

Nov  8 11:29:28  dota2[62909] <Warning>: displaySetMode: unable to find mode dict in array

I'm working with SDL devs to try to find a fix.  It is using an undocumented API (kCGDisplayShowDuplicateLowResolutionModes) to make it so CGDisplayCopyAllDisplayModes returns scaled modes, but then downsteam of that the CGDisplaySetDisplayMode seems to fail.  It appears to be isolated to AMD, although I'm not sure why.

**Comment by danginsburg** [comment] 2017-11-08 19:40
SDL bug filed: https://bugzilla.libsdl.org/show_bug.cgi?id=3949

**Comment by danginsburg** [comment] 2017-11-08 21:13
I've put in a fix for this, should be in the next Dota 2 Update.

**Comment by danginsburg** [comment] 2017-11-09 00:44
The update has shipped.  Should be fixed now.

**Comment by ericliu123** [comment] 2017-11-09 01:41
Appreciate the fast response! Thanks a lot.

**Closed as completed** 2017-11-09 13:28 UTC
Labels: reviewed
