### ISSUE TITLE
[macOS] Player details overlays match info

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1359] opened 2017-12-04 04:23 UTC
Scenario:

1. Go to match details
2. Select certain player to see the details
3. Go somewhere out of this page, for example, main menu
4. Open match again (for example, from profile -> match)

Result: player details overlap other info (see screenshot: https://i.imgur.com/8SeHgRv.jpg)

**Comment by gdrewb-valve** [comment] 2017-12-04 04:55
This seems to be a duplicate of #1357, does that cover what you're seeing?

**Comment by RankoR** [comment] 2017-12-04 05:30
@gdrewb-valve yep, that's a duplicate, sorry.

**Comment by gdrewb-valve** [comment] 2017-12-04 05:32
Thanks, closing.

**Closed as completed by gdrewb-valve** 2017-12-04 05:32 UTC
