### ISSUE TITLE
[OS X] Steam overlay not working on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by MiniLarsen** [ValveSoftware/Dota-2#526] opened 2015-10-04 09:06 UTC
The steam overlay ingame is not working. I cannot buy anything from the market eather. Have been trying to buy the compendium since release but its just loading forever. Also tryed to buy from the steam store site with same issue.

I live in Norway.

Have tested the steam overlay in FM15, works just fine there.

Processor Information:
    Model:  MacBookPro10,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 650M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xfd5
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                        33.1cm x 20.6cm  (38.9cm diag)
Primary VRAM: 1024 MB
```

Memory:
    RAM:  8192 Mb

**Comment by danginsburg** [comment] 2015-10-05 12:38
We are working on a fix for this issue.  The problem is to do with OS X El Capitan 10.11 System Integrity Protection (SIP).  I am not recommending this, but a temporary workaround for the issue would be to disable SIP.  We are working on a real fix.

**Comment by MiniLarsen** [comment] 2015-10-05 12:45
Thank you.

**Comment by danginsburg** [comment] 2015-10-05 12:56
I'm going to leave this open until we push out a fix.

**Comment by danginsburg** [comment] 2015-10-12 20:11
The fix for Steam is available in the Steam Beta Channel.  Go to Steam -> Preferences -> Beta Participation and choose "Steam Beta Update" and it now works on El Capitan.  Closing.

**Closed as completed by danginsburg** 2015-10-12 20:11 UTC
Labels: reviewed
