### ISSUE TITLE
Desktop Shortcut for Dota 2 one Mac not shown as Dota's but Steam one

### ISSUE THREAD

**Issue by levihuayuzhang** [ValveSoftware/Dota-2#2104] opened 2022-08-15 17:37 UTC
MacOS: 12.5

The icon in Desktop Shortcut for Dota seems not correct. Please ship an official one for Mac players!

Seems wait for several years (laugh) <https://github.com/ValveSoftware/Dota-2/issues/1168>

**Comment by kisak-valve** [comment] 2022-08-15 18:09
Hello @levihuayuzhang, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #1168.

**Closed as not planned by kisak-valve** 2022-08-15 18:09 UTC
