### ISSUE TITLE
Can't bind '~' otherwise know as ' `' on keyboard.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#697] opened 2015-12-24 20:03 UTC
So, I'm trying to bind my ` or other wise ~ key (same key) to a control group or anything in dota but I can't.

I've tried the launch option:

-input_button_code_is_scan_code

And i've also selected the extra options in the advanced hotkey menu which should allow me to bind this key but it doesn't work. 

My keyboard has british layout and the ~ is next to the key Z. 

Curiously my '§±' key worked without needing to configure any options or anything like that and it's been working well since source1.
I'm on mac, using mac wireless keyboard. Latest OS.

**Comment by Tele42** [comment] 2015-12-24 20:29
Duplicate of #268, being tracked at https://bugzilla.libsdl.org/show_bug.cgi?id=3076.

**Comment by gdrewb-valve** [comment] 2015-12-25 14:23
Closing duplicate.

**Closed as completed by gdrewb-valve** 2015-12-25 14:23 UTC
Labels: duplicate, reviewed
