### ISSUE TITLE
Hero portraits are cut in half after the game ends (in the summary screen) - Vulkan related?

### ISSUE THREAD

**Issue by filipejunqueira** [ValveSoftware/Dota-2#1876] opened 2021-01-22 04:33 UTC
#### Your system information

https://gist.github.com/filipejunqueira/7678cd2b1918304981150b80b227b74e

Have you checked for system updates?: YES
Are you using the latest stable video driver available for your system? YES
Have you verified the game files?: YES

#### Please describe your issue in as much detail as possible:

Hero portraits are cut in half in the summary post-game screen, that's pretty much it. Likely Related to vulkan I think. 
This has happened after the "watch tab update", likely to be related to vulkan since the issue happens only with vulkan enabled.
#### Steps for reproducing this issue:

1. Finish a game in Dota2
2. Notice that the hero portraits in the summary screen after the game are cut in half-ihs

**Comment by danginsburg** [comment] 2021-01-22 17:58
This is a duplicate of #1870 and was fixed yesterday.

**Closed as completed by danginsburg** 2021-01-22 17:58 UTC
Labels: duplicate

**Comment by filipejunqueira** [comment] 2021-01-22 19:15
> This is a duplicate of #1870 and was fixed yesterday.

Thank you and sorry for the duplicate.
