### ISSUE TITLE
libcurl.so not found or wrong ELF when linking manually

### ISSUE THREAD

**Issue by JackTemaki** [ValveSoftware/Dota-2#1534] opened 2018-12-08 18:25 UTC
After updating Dota today, i crash on launch with the following error:

```Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198007814181 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198007814181
Setting breakpad minidump AppID = 373300
crash_20181208183228_1.dmp[5997]: Uploading dump (out-of-process)
/tmp/dumps/crash_20181208183228_1.dmp
crash_20181208183228_1.dmp[5997]: Finished uploading minidump (out-of-process): success = no
crash_20181208183228_1.dmp[5997]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20181208183228_1.dmp[5997]: file ''/tmp/dumps/crash_20181208183228_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
[1]    5987 segmentation fault (core dumped)  ./dota2
```

When i manually link libcurl (i tried 3 and 4),
```sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0 libcurl.so```

I get:

```
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198007814181 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198007814181
Setting breakpad minidump AppID = 373300
crash_20181208183904_1.dmp[6906]: Uploading dump (out-of-process)
/tmp/dumps/crash_20181208183904_1.dmp
crash_20181208183904_1.dmp[6906]: Finished uploading minidump (out-of-process): success = no
crash_20181208183904_1.dmp[6906]: error: libcurl.so: wrong ELF class: ELFCLASS64
crash_20181208183904_1.dmp[6906]: file ''/tmp/dumps/crash_20181208183904_1.dmp'', upload no: ''libcurl.so: wrong ELF class: ELFCLASS64''
[1]    6894 segmentation fault (core dumped)  ./dota2
``` 

It seems that the newest Dota 2 binary was compiled against a version of libcurl that is not available on Ubuntu 16.04

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-139-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-beta-release_2018-11-28

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1c03
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.43" x 12.76" (24.06" diag)
                                            51.9cm x 32.4cm (61.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: ICE1712 - multitrack

Memory:
    RAM:  15984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  124818 Mb
    Largest Free Hard Disk Block:  12881 Mb
    VR Headset: None detected

**Comment by kisak-valve** [comment] 2018-12-08 18:38
Hello @JackTemaki, curl in your log is being used by steam (32 bit) to send a minidump of Dota 2 after things have gone awry. There's nothing special about the curl version, and you should be able to add the `libcurl4-gnutls-dev:i386` or `libcurl4-openssl-dev:i386` package to your system to provide it.

This is completely after Dota 2 has crashed and the issue is most likely the same issue being tracked at #1530 / #1532. Closing in favor of the existing issue reports.

**Closed as completed by kisak-valve** 2018-12-08 18:38 UTC
