### ISSUE TITLE
Dota2 Reborn on linux executing windows path

### ISSUE THREAD

**Issue by djaney** [ValveSoftware/Dota-2#541] opened 2015-10-08 13:29 UTC
I'm on ubuntu 14.04. I try to run dota 2 on steam and says "missing executable".

In logs it seems to be trying to execute a windows path:
[2015-10-08 21:27:05] Failed running app 570 (missing executable "/home/zeratul/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/win32/dota2.exe"

**Comment by danginsburg** [comment] 2015-10-08 13:50
Duplicate of #439.  I assume you are on Ubuntu 32-bit?  We do need a better error message, but Dota 2 is only supported on 64-bit Linux now.

**Closed as completed** 2015-10-08 16:45 UTC
Labels: duplicate, reviewed
