### ISSUE TITLE
Huge FPS issues MAC OS

### ISSUE THREAD

**Issue by jgouth** [ValveSoftware/Dota-2#1284] opened 2017-07-26 08:30 UTC
For last 25ish days, I think after a update, the mac OS got completely screwed with FPS. 

I used to AT LEAST stabilize with ~ 50-60 fps but now its always 12-30. 

Please help valve.

**Comment by gdrewb-valve** [comment] 2017-07-26 15:02
This seems like a duplicate of the open Mac perf issues.  Do you have something specific that those don't cover?

**Comment by Sidai-13** [comment] 2017-07-26 17:47
+1 similar issues here. Used to run at 60fps max settings. Now I am on lowest settings with the game stabilizing at about 20fps after 10-15min. Have tried verifying game cache as well as full reinstalls of steam and Dota 2.

 Model Name: iMac
 Model Identifier: iMac17,1
 Processor Name: Intel Core i5
 Processor Speed:	3.3 GHz
 Number of Processors: 1
 Total Number of Cores: 4
 L2 Cache (per Core): 256 KB
 L3 Cache: 6 MB
 Memory: 32 GB

**Comment by gdrewb-valve** [comment] 2017-07-27 18:28
Closing in favor of open issues like #1101 and #1188.

**Closed as completed by gdrewb-valve** 2017-07-27 18:28 UTC

**Comment by gdrewb-valve** [comment] 2017-07-27 18:30
Also referencing #1259 to keep things linked.
