### ISSUE TITLE
libclient.so segfault with some animations

### ISSUE THREAD

**Issue by paboum** [ValveSoftware/Dota-2#2499] opened 2023-09-28 21:49 UTC
Build ID 12310626
```
[851616.464878] dota2[28862]: segfault at 38 ip 00007fcd213d23e4 sp 00007ffd5a0ba1a0 error 4 in libclient.so[7fcd1fca7000+2f5e000] likely on CPU 8 (core 16, socket 0)
```

I'm tired of reporting these frequent bugs. If you can't into memory allocation in C++, then use static analysis tools. Or drop the project.

**Comment by dssouza-ti** [comment] 2023-09-29 03:37
I confirm this bug. Also happening with me after last audio fix update:

`[44943.760154] dota2[42025]: segfault at 38 ip 00007f00911ce3e4 sp 00007ffe9647a4f0 error 4 in libclient.so[7f008faa3000+2f5e000] likely on CPU 4 (core 4, socket 0)`

`[46212.970562] dota2[43731]: segfault at 38 ip 00007f37a51ce3e4 sp 00007ffe637f77b0 error 4 in libclient.so[7f37a3aa3000+2f5e000] likely on CPU 11 (core 5, socket 0)
`

Happened 2 times in the last match.

**Comment by ConnahGriffin** [comment] 2023-09-29 15:54
I can confirm that this does happen to me too... So far happened because of cog from clockwork and sunray from pheonix. Not always but often when using those skills. This too when used by other players.
Here's my error: `segfault at 38 ip 00007f5817bd23e4 sp 00007ffd723877a0 error 4 in libclient.so[7f58164a7000+2f5e000]`

**Comment by Znimator** [comment] 2023-09-29 20:01
Can confim it happened to me several times

**Comment by Turmfalke2** [comment] 2023-09-29 21:49
Unfortunately a frequent issue.

**Comment by Thorinori** [comment] 2023-09-29 23:09
Can also confirm happening for me too (Ubuntu 22.04.3)

**Comment by Turmfalke2** [comment] 2023-09-30 13:28
`[ 6700.123692] dota2[4468]: segfault at 38 ip 00007f6c3d3d1414 sp 00007ffff604abf0 error 4 in libclient.so[7f6c3bca6000+2f5f000] likely on CPU 3 (core 3, socket 0)`

[crash_20230930133409_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12774770/crash_20230930133409_2.dmp.txt)

Is there anything we can do to help get this fixed?

**Comment by pure-bliss** [comment] 2023-09-30 17:37
<details>
  <summary>Bit more detailed logs/stack</summary>

  ```
Sep 30 18:40:29 harczos kernel: dota2[2499]: segfault at 38 ip 00007f93669ce414 sp 00007ffc11086010 error 4 in libclient.so[7f93652a3000+2f5f000] likely on CPU 7 (core 7, socket 0)
Sep 30 18:40:29 harczos kernel: Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
Sep 30 18:40:29 harczos systemd[1]: Created slice Slice /system/systemd-coredump.
Sep 30 18:40:29 harczos systemd[1]: Started Process Core Dump (PID 13306/UID 0).
Sep 30 18:40:43 harczos systemd-coredump[13308]: [🡕] Process 2499 (dota2) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 2499:
                                                 #0  0x00007f93669ce414 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bce414)
                                                 #1  0x00007f9366994a15 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4b94a15)
                                                 #2  0x00007f9366998bc0 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4b98bc0)
                                                 #3  0x00007f9366603dec n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4803dec)
                                                 #4  0x00007f9366824380 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4a24380)
                                                 #5  0x00007f93666d9425 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x48d9425)
                                                 #6  0x00007f93654d1865 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x36d1865)
                                                 #7  0x00007f93669b6a17 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bb6a17)
                                                 #8  0x00007f93668be3a4 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4abe3a4)
                                                 #9  0x00007f936679e639 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x499e639)
                                                 #10 0x00007f941e5aed22 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1aed22)
                                                 #11 0x00007f941e5aed22 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1aed22)
                                                 #12 0x00007f941e5b3d1d n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1b3d1d)
                                                 #13 0x00007f941e5987c9 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1987c9)
                                                 #14 0x00007f941e598ba5 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x198ba5)
                                                 #15 0x00007f941e58cca3 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x18cca3)
                                                 #16 0x00007f941e592652 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x192652)
                                                 #17 0x00007f941e59291f n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x19291f)
                                                 #18 0x00005563dfbaae30 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3e30)
                                                 #19 0x00005563dfbaa903 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3903)
                                                 #20 0x00007f9421c27cd0 n/a (/run/host/usr/lib/libc.so.6 + 0x27cd0)
                                                 ELF object binary architecture: AMD x86-64
  ```
  
</details>

**Comment by dssouza-ti** [comment] 2023-09-30 18:32
I played this match yesterday (ID 7358100874), and my game crashed about 5 times during team fights. I don´t know what skills/animations were being used, but if you can figure it out, maybe it helps. It's a really annoying bug, it makes almost impossible to play certain matches of dota.

**Comment by mewt666** [comment] 2023-09-30 21:51
Happened twice in the last match. journal log below:

Sep 30 23:36:10  kernel: dota2[242732]: segfault at 39 ip 00007fe5451ce414 sp 00007ffd3190f770 error 4 in libclient.so[7fe543aa3000+2f5f000] likely on CPU 4 (core 5, socket 0)
Sep 30 23:36:10  kernel: Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
Sep 30 23:36:10  systemd[1]: Started Process Core Dump (PID 246753/UID 0).
░░ Subject: A start job for unit systemd-coredump@3-246753-0.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit systemd-coredump@3-246753-0.service has finished successfully.
░░ 
░░ The job identifier is 4673.
Sep 30 23:36:36  systemd-coredump[246755]: [🡕] Process 242732 (dota2) of user 1000 dumped core.
                                                       
                                                       Stack trace of thread 242732:
                                                       #0  0x00007fe5451ce414 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bce414)
                                                       #1  0x00007fe545194a15 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4b94a15)
                                                       #2  0x00007fe545198bc0 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4b98bc0)
                                                       #3  0x00007fe5451d3f5d n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bd3f5d)
                                                       #4  0x00007fe544e03dec n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4803dec)
                                                       #5  0x00007fe545024380 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4a24380)
                                                       #6  0x00007fe544ed9425 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x48d9425)
                                                       #7  0x00007fe543cd1865 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x36d1865)
                                                       #8  0x00007fe5451b6a17 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bb6a17)
                                                       #9  0x00007fe5451cf601 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4bcf601)
                                                       #10 0x00007fe5450be3a4 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x4abe3a4)
                                                       #11 0x00007fe544f9e639 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so + 0x499e639)
                                                       #12 0x00007fe610daed22 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1aed22)
                                                       #13 0x00007fe610daed22 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1aed22)
                                                       #14 0x00007fe610db3d1d n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1b3d1d)
                                                       #15 0x00007fe610d987c9 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1987c9)
                                                       #16 0x00007fe610d98ba5 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x198ba5)
                                                       #17 0x00007fe610d8cca3 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x18cca3)
                                                       #18 0x00007fe610d92652 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x192652)
                                                       #19 0x00007fe610d9291f n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x19291f)
                                                       #20 0x000055bfcf988e30 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3e30)
                                                       #21 0x000055bfcf988903 n/a (/home//.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3903)
                                                       #22 0x00007fe614538cd0 n/a (/run/host/usr/lib/libc.so.6 + 0x27cd0)
                                                       ELF object binary architecture: AMD x86-64

**Comment by Turmfalke2** [comment] 2023-09-30 22:31
crashed twice in the same game:
```
[44836.850236] dota2[11708]: segfault at 39 ip 00007f9b253d1414 sp 00007ffdd4139540 error 4 in libclient.so[7f9b23ca6000+2f5f000] likely on CPU 0 (core 0, socket 0)
[44836.850248] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
[44963.800694] dota2[15936]: segfault at 39 ip 00007fdf413d1414 sp 00007ffe54315df0 error 4 in libclient.so[7fdf3fca6000+2f5f000] likely on CPU 0 (core 0, socket 0)
[44963.800704] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
```
[crash_20231001000945_20.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12775648/crash_20231001000945_20.dmp.txt)
[crash_20231001001152_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12775649/crash_20231001001152_2.dmp.txt)

**Comment by Turmfalke2** [comment] 2023-10-01 12:20
```
[ 5326.377357] dota2[2730]: segfault at 38 ip 00007fa8793d1414 sp 00007ffd1914d110 error 4 in libclient.so[7fa877ca6000+2f5f000] likely on CPU 3 (core 3, socket 0)
[ 5326.377368] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
```
[crash_20231001113111_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12777105/crash_20231001113111_2.dmp.txt)

**Comment by Turmfalke2** [comment] 2023-10-01 17:03
3 more

```
[29230.274569] dota2[9462]: segfault at 39 ip 00007f37913d1414 sp 00007ffdce4d24d0 error 4 in libclient.so[7f378fca6000+2f5f000] likely on CPU 3 (core 3, socket 0)
[29230.274580] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
[29266.128695] traps: dunst[11269] trap int3 ip:7f71b79e542f sp:7fff798b6d30 error:0 in libglib-2.0.so.0.7600.4[7f71b79a1000+97000]
[29421.744409] traps: dunst[11333] trap int3 ip:7f070b06842f sp:7fff89fabc70 error:0 in libglib-2.0.so.0.7600.4[7f070b024000+97000]
[29534.656243] kworker/dying (36) used greatest stack depth: 11272 bytes left
[31659.246079] dota2[11200]: segfault at 38 ip 00007f78c13d1414 sp 00007fff5e510990 error 4 in libclient.so[7f78bfca6000+2f5f000] likely on CPU 2 (core 2, socket 0)
[31659.246090] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
[31937.012634] dota2[11767]: segfault at 38 ip 00007f25f93d1414 sp 00007ffe4241d470 error 4 in libclient.so[7f25f7ca6000+2f5f000] likely on CPU 0 (core 0, socket 0)
[31937.012645] Code: 00 4c 89 e6 4c 89 ef 41 5c 41 5d 5d 48 8b 80 f8 07 00 00 ff e0 90 55 48 89 e5 41 56 41 55 49 89 fd 41 54 49 89 f4 48 83 ec 18 <48> 8b 7e 38 e8 33 cc 54 01 3c 07 75 4f 45 0f b6 74 24 5c 45 84 f6
```

[crash_20231001185441_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12777703/crash_20231001185441_2.dmp.txt)
[crash_20231001185003_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12777705/crash_20231001185003_2.dmp.txt)
[crash_20231001180934_2.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/12777706/crash_20231001180934_2.dmp.txt)

**Comment by csbuja** [comment] 2023-10-02 06:09
![image](https://github.com/ValveSoftware/Dota-2/assets/6466300/f1852c68-984e-450c-8bb8-5154dda76002)
I'm having the same issue.

**Comment by headlesscyborg** [comment] 2023-10-03 08:41
I'm having the same issue. It can also be easily reproduced by clicking on match history (always crashes in my case).
Yesterday I was able to crash the game for everyone, including the enemy team, simply by firing the ultimate as Hoodwink. People were confused and one of them said that they see 0 kills on both sides. The match is reported on Dotabuff as lost even though I won.
This should be handled with priority because it seems the Linux client can be used to abuse the match.

Not sure if HW/SW is related but if so, I'm using up to date Arch, stable Steam client and an RX 6700 XT.

**Comment by alexeysvrv** [comment] 2023-10-03 20:02
I don’t know why, but for the last 2 days (yesterday and today) my game has never frozen or crashed. Manjaro latest version. Video card RX 6600M. Fresh mesa. True, I launch in native steam, and not in runtime. Try it, maybe it will help

**Comment by Thorinori** [comment] 2023-10-04 07:51
After the update on Oct. 3rd, feels like the crashing has been mostly fixed (Played several games in a row no crashes, used to be crashes per game rather than games per crash, so big improvement). Seems sound might have been messed up a bit again though (but that is part of a different issue on here already)

**Comment by dssouza-ti** [comment] 2023-10-05 03:14
Today I played 5 matches with no crash.

**Comment by paboum** [comment] 2023-10-07 14:31
I think we have mixed several issues in one ticket. For me, this stopped occuring after the very next update, so I'd close it.

Other than this, segmentation faults are a proof of very bad programming practice and, for example, can cause a match be lost if the enemy initiates a specific animation if they know your client is susceptible for this crash.

The developers should at least run each Linux client version with valgrind in their CI pipeline and let bots play 124 / 10 matches with all heroes automatically to detect such crashes and identify culprit routines. I can't understand how such an unstable version even gets released to production. This bug could have been detected by a proper test automation.

**Comment by kisak-valve** [comment] 2023-11-10 20:35
Closing per the last handful of comments.

**Closed by kisak-valve** 2023-11-10 20:35 UTC
Labels: Need Retest

**Comment by paboum** [comment] 2023-11-11 10:05
> Closing per the last handful of comments.

Fine with me, it's been 6 months since I paid a single dollar to Valve.
