### ISSUE TITLE
[OSX] 3D graphic bug after updating patch 7.00 on dota 2

### ISSUE THREAD

**Issue by srhseungyeon** [ValveSoftware/Dota-2#1120] opened 2016-12-15 15:27 UTC
Hello, my mac came out around 2009 and its currently running on Yosemite 10.10.2
graphic card ATI Radeon HD 4670 256 MB/ processor 3.06 GHz Intel Core i3
i could play dota perfectly fine before the patch 7 came and this happens only after i updated my dota 2
![screen shot 2016-12-15 at 11 17 57 pm](https://cloud.githubusercontent.com/assets/24589883/21229822/d2b76ac4-c31d-11e6-8048-ab1bbd71f697.png)
![screen shot 2016-12-15 at 11 18 20 pm](https://cloud.githubusercontent.com/assets/24589883/21229844/e007aa2c-c31d-11e6-8a14-b088d71575e2.png)
 pls help :(

**Comment by danginsburg** [comment] 2016-12-15 16:35
I have been able to reproduce this on ATI 2600 XT 256MB.  It seems to be made worse as I increase video settings.  It may be a problem with the driver handling GPU memory oversubscription.  I'll see what can be done to workaround it.  If you turn all video settings to lowest does it still happen for you?

**Comment by srhseungyeon** [comment] 2016-12-16 00:37
@danginsburg yeah its the same, the screenshot above is actually running on the lowest settings

**Comment by deksden** [comment] 2016-12-16 16:06
Same for my system, again (this bug was fixed before, but after 7.00 patch it appears again!)
**Upd**: playing with any video config options did not help at all. 

Model Name:	iMac
  Model Identifier:	iMac11,1
  Processor Name:	Intel Core i7
  Processor Speed:	2,8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Processor Interconnect Speed:	4,8 GT/s
  Boot ROM Version:	IM111.0034.B04
  SMC Version (system):	1.54f36
  Serial Number (system):	W80078265RU
  Hardware UUID:	42E4360C-9013-5891-B44E-485DC9C7046D

ATI Radeon HD 4850:

  Chipset Model:	ATI Radeon HD 4850
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	512 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x944a
  Revision ID:	0x0000
  ROM Revision:	113-B9110C-425
  EFI Driver Version:	01.00.383
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	2560 x 1440
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Built-In:	Yes

**Comment by deksden** [comment] 2016-12-16 16:06
![dota2-7 00-bug](https://cloud.githubusercontent.com/assets/2203023/21269179/4917878c-c3e4-11e6-9c09-5fd250fbdaee.png)

**Comment by deksden** [comment] 2016-12-16 16:07
Also this bug is visible during observing hero 3D models

![dota2-7 00-bug-hero](https://cloud.githubusercontent.com/assets/2203023/21271115/2ded925a-c3ec-11e6-9832-65aca2767917.png)

**Comment by deksden** [comment] 2016-12-16 16:38
IMHO, exactly same as: https://github.com/ValveSoftware/Dota-2/issues/24

**Comment by srhseungyeon** [comment] 2016-12-16 17:19
@deksden i feel you bro, i think the last time this happened, was when the reborn client first came out. I thought i couldnt play it anymore but somehow a few patches later the problem was solved

**Comment by danginsburg** [comment] 2016-12-16 17:56
@srhseungyeon I think I've found a workaround and I do agree it is the same root cause as #24.  Are you sure you didn't at some point toggle video settings (specifically Grass) on during play?  Did you start out at lowest quality video settings?  I do not see this happen on ATI 2600 XT if I start at low quality settings and never change them.  I believe the grass is bumping up against the limit with > 16 textures which then causes the corruption.

**Comment by deksden** [comment] 2016-12-16 18:32
@danginsburg : Ouch! Restarting on lowest settings do the trick! this is real workaround. After that i can even add some graphics stuff (did not touched grass ;) Many tnx)))

**Summary for workaround**: set lowest settings. Restart game.

**Comment by danginsburg** [comment] 2016-12-16 18:36
@deksden Thanks.  I am working on a fix that will disable grass on AMD 2xxx-4xxx, but it will basically do the same thing.

**Comment by deksden** [comment] 2016-12-16 18:45
@danginsburg : my bad luck was that once you have that bug - changing video settings did not help. You should start at lowest settings and add them later. Thank to pointing to key step: restart at lowest settings. 

After that i was able to add most video setting back. I can confirm that touching "grass" option returns graphical issues.

**Comment by srhseungyeon** [comment] 2016-12-16 19:14
@danginsburg oh i thought you meant by texture low quality, i disabled grass and it works TT thank you so much

**Comment by danginsburg** [comment] 2016-12-16 19:18
Great, glad we got to the bottom of it.  I've also checked in a workaround to forcibly disable grass on AMD 2xxx-4xxx on Mac.  It will be in the next dota update.

**Closed as completed by danginsburg** 2016-12-16 19:18 UTC
Labels: reviewed
