### ISSUE TITLE
[linux] problem with bindings and changing keyboard layouts

### ISSUE THREAD

**Issue by SuperFlick** [ValveSoftware/Dota-2#143] opened 2015-06-27 19:18 UTC
If i start dota with russian keyboard layout (but i think it's for any lang), then game binds are not work. And they wont even if I switch to eng. It allows to type with both layouts, but I cant use spells and inventory. So I have to restart my client with eng layout.
ubuntu 14.04

**Comment by gdrewb-valve** [comment] 2015-06-27 19:44
This is largely a duplicate of the other key-binding issues here but keeping open for now.

**Comment by gdrewb-valve** [comment] 2015-07-13 16:08
Can you post your system info?

**Comment by gdrewb-valve** [comment] 2015-07-15 17:11
Are you still seeing problems?

**Comment by SuperFlick** [comment] 2015-07-16 00:45
now i can switch layout to eng and back. but still have to switch back from rus to eng (if i binded it with eng layout) to use spells and back again to type something in chat with rus layout.

sysinfo
Intel® Core™ i5-2410M CPU @ 2.30GHz × 4 
Intel® Sandybridge Mobile HD 3000
6gb ram
x64

**Comment by davidw-valve** [comment] 2015-07-16 00:46
Does this work as you think it should in Source1?

**Comment by SuperFlick** [comment] 2015-07-16 00:49
davidw-valve
yes. it works fine in source1. i can type with rus layout and cast spells w/o switching to eng layout even if its binded with eng. 
Even better in source1 - i have rus layout now, but when i'm trying rebind an action dota binds it with eng letter.

**Comment by gdrewb-valve** [comment] 2015-07-16 04:30
To make sure I understand you're saying the problem occurs if you bind a key in one layout and then try to use it in another layout?  That's by-design behavior since bindings are layout-sensitive.  For example, if you bind something to 'z' in a US layout on an US keyboard and then switch to a French layout, where the 'z' key on the US keyboard is now 'w', pressing the US 'z' key should not trigger the action since that key is no longer 'z'.  Put another way bindings are tied to the layout-specific name of the key, not the physical key on the keyboard.

**Comment by SuperFlick** [comment] 2015-07-16 06:53
exactly. a key binded on a layout1 won't work on a layout2

**Comment by gdrewb-valve** [comment] 2015-07-16 07:35
OK, that's the way it's supposed to work now and for the forseeable future.  I'll leave this open as an enhancement request to somehow make it work across layouts.

**Comment by tpruzina** [comment] 2015-08-02 18:09
The problem here is afaik the fact that old dota ignored layouts and did read raw keysyms, whereas reborn seems to use libSDL better and recognize layouts properly.

This naturally screws people who switch between the two since if you used for example programmers Dvorak layout on source1, your spells were still bound as " q w e r t y ", but on dvorak this would translate to " ; , . p y " (source2 behavior).

source2 behaviour is correct and we asked for it ages ago in source1 (I think there should still be some old bugs about this lying around).
This said, unless you plan to fix this in source1 version (soon to be deprecated I hope), there is not much to do here IMHO.

**Comment by gdrewb-valve** [comment] 2015-08-02 19:52
In theory Reborn could detect the layout change, let the user know and offer a way to remap things.  We have no plans to offer such functionality but there are things that could be done to ease the pain of this.

**Comment by gdrewb-valve** [comment] 2015-10-12 14:27
An update added the -input_button_code_is_scan_code command-line option which switches things to something like Source 1 (note that switching between using this and not using it may invalidate your key bindings).  If you try it does it work the way you want?

**Comment by gdrewb-valve** [comment] 2015-10-19 17:16
There is now a UI option in the Advanced section of the key bindings settings to turn on positional binds.  Closing pending info that this isn't sufficient.

**Closed as completed by gdrewb-valve** 2015-10-19 17:16 UTC
Labels: reviewed

**Comment by tpruzina** [comment] 2018-11-07 22:53
I might have to open a separate issue, but I've run into windows<>linux troubles (couldn't remap "Q" key on linux/dvp layout box that used cloud config from windows), "**-input_button_code_is_scan_code"** worked nicely as a workaround.
For whatever reason, the bug was only present on friends account which I have borrowed.
