### ISSUE TITLE
Can't launch Dota 2 (HP250G2 Ubuntu 22.04)

### ISSUE THREAD

**Issue by k0w4lk** [ValveSoftware/Dota-2#2110] opened 2022-08-26 09:14 UTC
#### Your system information

* System information from steam: https://gist.github.com/k0w4lk/2d0a63d181b0de83e3cb701caa42b4f6 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I'm trying to run Dota 2 on my laptop, but whether I'm waiting for shaders caching or not (skip it because first time I've waited for an hour for this and it hasn't changes anything, and also after every  reboot I need to wait for it again and again), in Steam the Play button changes briefly to Stop and then back to Play. The game does not launch. The game itself runs on another computer on Linux. Also this laptop allows me to play Tomb Raider 2013, which indicates either the inability of this laptop to run Dota 2 in general (although a couple of years ago I could do it on my machine) or the absence of any additional system or game settings. I've already tried to add -gl to launch options, but result the same.

#### Steps for reproducing this issue:

1. Click Play Dota 2
2. Skip Processing Vulkan Shaders
3. Game don't lauch

![Peek 2022-08-26 12-12](https://user-images.githubusercontent.com/74924763/186870773-36239eab-28cf-486b-9a53-5710a2ef45cb.gif)

**Comment by kisak-valve** [comment] 2022-08-26 12:06
Hello @k0w4lk, the NVIDIA 390 series driver install makes this issue report a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/420 (similar to https://github.com/ValveSoftware/steam-runtime/issues/500). Unfortunately, the 390 series NVIDIA driver is also the last release that supports your video driver, so there isn't a quick fix.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2022-08-26 12:06 UTC
