### ISSUE TITLE
Game State Integration (GSI) works intermitently

### ISSUE THREAD

**Issue by boombatower** [ValveSoftware/Dota-2#1023] opened 2016-09-15 23:33 UTC
I have a GSI  config at `dota 2 beta/game/dota/cfg/gamestate_integration/gamestate_integration_dota2-gsi.cfg`:

```
"dota2-gsi Configuration"
{
    "uri"               "http://localhost:3000/"
    "timeout"           "5.0"
    "buffer"            "0.1"
    "throttle"          "0.1"
    "heartbeat"         "30.0"
    "data"
    {
        "provider"      "1"
        "map"           "1"
        "player"        "1"
        "hero"          "1"
        "abilities"     "1"
        "items"         "1"
    }
    "auth"
    {
        "token"         "hello1234"
    }
}
```

and a serve to listen for integration. I toggle some logitech keyboard state based on cooldowns, deaths, and kills. Everything works perfectly...sometimes.

For the curious:
- https://www.youtube.com/watch?v=zjbV-9NIKm8
- https://www.youtube.com/watch?v=pW9P2XqNgw0
- webcam reaction shot on death/kill :-)

It seems the first time or two dota does not even make an attempt to connect to gsi server regardless of whether it is started before or after dota is launched. Typically around the third launch (after playing games) it will connect, many times delayed (after match has been going for a bit), but still not send events. Eventually, and sometimes on the first try it will connect and function properly.

I start the server the same way each time and it prints out any messages it receives.

Presumably this is not specific to Linux, but I only have a Linux setup at this point and this is a much nicer way to report the issue. Please let me know what else I can provide to assist in debugging.

Most likely irrelevant, but my system information:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  6300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE Tumbleweed" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.3-1-default
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.45.0 / 4.7.3-1-default, LLVM 3.8.0)

    Driver Version:  3.0 Mesa 12.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Revision Not Detected
    Number of Monitors:  3
    Number of Video Cards Not Detected
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 6400 x 1600
    Primary Display Size: 25.24" x 15.75"  (29.72" diag)
                                            64.1cm x 40.0cm  (75.5cm diag)
    Primary VRAM: 6144 MB

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  32125 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  201933 Mb
    Largest Free Hard Disk Block:  18228 Mb
    VR Headset: None detected
```

**Comment by MattBoone** [comment] 2016-09-16 00:29
Can you give some details on the http server that gsi is connecting to? Do you not receive any connections in the case where Dota is not connecting properly, or malformed data? It would be worth trying the same connection but with win32 to eliminate the chance that the issue is with Dota specifically under linux.

**Comment by boombatower** [comment] 2016-09-16 01:53
Given the available options, I ended up using https://www.npmjs.com/package/dota2-gsi which does the trick. Since it uses express.oi I set env variable for debugging to show everything: `DEBUG=express:* node index.js`.

With that I can see GET requests I make from browser in such. I'll have to run through cases where it "half-connects", but the default case it appears it never sends anything.

I have never come across any error messages or anything in console, but not sure if it would complain there. As for win32 sure, but as I stated in initial post I do not have such an environment.

**Comment by antonpup** [comment] 2016-09-19 06:02
Let me just quickly drop my Dota 2 GSI project for C# here. https://github.com/antonpup/Dota2GSI and https://www.nuget.org/packages/Dota2GSI/ It includes some documentation for overall GSI.

I was one of the first to discover GSI with Dota 2, but that is beside the point.

**Comment by gdrewb-valve** [comment] 2017-03-13 23:42
This isn't a Mac/Linux issue so I'm closing this out.

**Closed as completed by gdrewb-valve** 2017-03-13 23:42 UTC
Labels: reviewed

**Comment by mateim4** [comment] 2025-06-28 20:58
> This isn't a Mac/Linux issue so I'm closing this out.

I think it actually is, because of pressure-vessel, GSI network communication with servers outside the container is impossible, regardless of launch parameters used. This is specific to the native Linux Dota 2 running via Sniper Runtime 3.0. I managet to get the Flatpak version to work via Flatpost, but the native client... not as much.
