### ISSUE TITLE
[Linux] Start Dota 2 on Vulkan API

### ISSUE THREAD

**Issue by mrdeathman** [ValveSoftware/Dota-2#764] opened 2016-02-20 12:44 UTC
# 
# VULKAN INFO

Vulkan API Version: 1.0.3

NVIDIA 355.00.27

Ubuntu 15.10

LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011' !

failed to dlopen "librendersystemvulkan.so" error=librendersystemvulkan.so: cannot open shared object file: No such file or directory

**Comment by Tele42** [comment] 2016-02-20 13:19
Duplicate of #763, the vulkan backend is not yet publically available.

**Closed as completed** 2016-02-20 17:27 UTC
Labels: duplicate, reviewed
