### ISSUE TITLE
[Linux] Game launches on the wrong monitor

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#130] opened 2015-06-27 05:47 UTC
Dota Reborn, unlike the original Dota, launches on the wrong monitor for me - not on the currently selected one but the first one in the list, I think. System information:

``````
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  4301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-57-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1080
    Primary Display Size: 20.47" x 11.42"  (23.43" diag)
                                            52.0cm x 29.0cm  (59.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7968 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104566 Mb
    Largest Free Hard Disk Block:  3913 Mb

Installed software:

Recent Failure Reports:
    ```
``````

**Comment by gdrewb-valve** [comment] 2015-06-27 05:59
Duplicate of #13.

**Closed as completed by gdrewb-valve** 2015-06-27 05:59 UTC
Labels: duplicate, reviewed
