### ISSUE TITLE
[Linux] Crash when will start "Start bot match" closing the game

### ISSUE THREAD

**Issue by Bubous** [ValveSoftware/Dota-2#148] opened 2015-06-27 23:08 UTC
OS: Linux Mint Mate 17.1
Processor:Phenom 64 bit X4 810 2.6Gb
Ram: 6gb 1300mhz
Video: ATI Radeon sapphire HD 7770 GPU:1100 OC GDDR5 1G 5.6MHz
Driver proprietary: Catalyst 15.5
Game: Dota 2 Reborn

[Code Error]
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/media/sdb6/JogosLinux/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/media/sdb6/JogosLinux/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Setting breakpad minidump AppID = 570
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198129992157 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198129992157
Setting breakpad minidump AppID = 373300
ERROR: ld.so: object '/home/phenom810/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150627195902_1.dmp[14428]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150627195902_1.dmp
/media/sdb6/JogosLinux/steamapps/common/dota 2 beta/game/dota.sh: linha 98: 14383 Instrução ilegal      ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 14383 
crash_20150627195902_1.dmp[14428]: Finished uploading minidump (out-of-process): success = no
crash_20150627195902_1.dmp[14428]: error: HTTP response code said error
crash_20150627195902_1.dmp[14428]: file ''/tmp/dumps/crash_20150627195902_1.dmp'', upload no: ''HTTP response code said error''
pid 14428 != 14427, skipping destruction (fork without exec?)

**Comment by gdrewb-valve** [comment] 2015-06-27 23:23
Duplicate of #10.

**Closed as completed by gdrewb-valve** 2015-06-27 23:23 UTC
Labels: reviewed
