### ISSUE TITLE
[Linux] Client is always crashing just after the Captains Mode draft phase.

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1027] opened 2016-09-21 00:41 UTC
Since monday, and still happening after today's update

dmesg -> [ 6727.344549] dota2[30787]: segfault at 0 ip 00007f21a16ed63a sp 00007ffc54951ba0 error 6 in libscaleformui_4_vulkan.so[7f21a1525000+b0a000]

i didn't have the -con_logfile enabled at the time. (waiting for a new crash)

**Comment by admshao** [comment] 2016-09-21 01:52
And again. Now with:

console.log -> https://gist.github.com/admshao/a8b5db89f47ae12ae1a3e4c943b37441

dmesg -> 
[10995.445963] perf: interrupt took too long (2515 > 2500), lowering kernel.perf_event_max_sample_rate to 79500
[11297.245641] dota2[19061]: segfault at 0 ip 00007f6d60fd663a sp 00007ffc25bb0730 error 6 in libscaleformui_4_vulkan.so[7f6d60e0e000+b0a000]

**Comment by gdrewb-valve** [comment] 2016-09-21 16:30
Duplicate of #922.

**Closed as completed by gdrewb-valve** 2016-09-21 16:30 UTC
