### ISSUE TITLE
[Linux] Flickering HUD

### ISSUE THREAD

**Issue by Aldrog** [ValveSoftware/Dota-2#90] opened 2015-06-25 04:47 UTC
The in-game HUD flickers heavily making it impossible to play.

![shot_0003](https://cloud.githubusercontent.com/assets/6755141/8346768/3bb9b04e-1b0a-11e5-918f-c8b9f063a5ea.jpg)
![shot_0004](https://cloud.githubusercontent.com/assets/6755141/8346766/3bb93844-1b0a-11e5-9bd7-49e761642a35.jpg)

Also, player name and amount of health are not displayed above a hero.

![shot_0008](https://cloud.githubusercontent.com/assets/6755141/8346767/3bb95c52-1b0a-11e5-855c-493b4216d495.jpg)

I have AMD HD7870 video card with opensource drivers (mesa 10.6)
System info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD PITCAIRN

    Driver Version:  3.0 Mesa 10.6.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6818
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,08" x 11,42"  (23,07" diag)
                                            51,0cm x 29,0cm  (58,6cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  55709 Mb
    Largest Free Hard Disk Block:  25712 Mb
```

**Comment by danginsburg** [comment] 2015-06-25 13:20
This is a duplicate of #79 .  The visual manifestation is slightly different, but it is the same issue.

**Closed as completed by danginsburg** 2015-06-25 13:20 UTC
Labels: duplicate, reviewed
