### ISSUE TITLE
game wot launch anymore since last update on linux nor macos (dota2 compilation id 3413998) [SOLVED]

### ISSUE THREAD

**Issue by predacon** [ValveSoftware/Dota-2#1548] opened 2018-12-19 23:53 UTC
i've plaiyng fine 1 hour before, then i updated the game as requested and dont start anymore showing this error:
Type_DeclaredClass ():
Fatal error: class "From Class Binding" has whitespace in its registration macro.

**Comment by kisak-valve** [comment] 2018-12-20 00:00
Hello @predacon, are you using Dota 2's vulkan backend? If so, does adding `-vulkan_disable_pipeline_cache` to the game's launch options help? (from #1547)

**Comment by predacon** [comment] 2018-12-20 00:07
no, I don't have vulkan support installed. we are 6 people with the same issue (dota2 community thread)

**Comment by predacon** [comment] 2018-12-20 00:12
my fault, i have -vulkan in the launch options by mistake, maybe from the last time i try to play with vulkan backend. deleting -vulkan from launch options solve the problem. game launch normally again. sorry ^^

**Comment by kisak-valve** [comment] 2018-12-20 00:18
Closing as a duplicate of #1547.

**Closed as completed by kisak-valve** 2018-12-20 00:18 UTC
Labels: reviewed
