### ISSUE TITLE
Dota 2 Crashing Instantly on Startup

### ISSUE THREAD

**Issue by mfed3** [ValveSoftware/Dota-2#2698] opened 2024-05-06 23:52 UTC
#### Your system information

* System information from steam:  https://gist.github.com/mfed3/213559ef909b232171158e273e92a1c1
* Steam Runtime Diagnostics: https://gist.github.com/mfed3/6e16d24f4565dee225fc3c3a0b23753c
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Expected behavior: Game launches and can play normally
Behavior experienced: Dota launches, instantly crashes
Crash Log: https://gist.github.com/mfed3/128116ff35c5bfbe08c59cc46a7754c1

#### Steps for reproducing this issue:

1. Launch Steam
2. Launch Dota 2

**Comment by kisak-valve** [comment] 2024-05-07 00:16
Hello @mfed3, this is a video driver issue being tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343.

Closing as a duplicate of #2694.

**Closed as not planned by kisak-valve** 2024-05-07 00:16 UTC

**Comment by mfed3** [comment] 2024-05-07 02:34
Downgraded kernel to 6.6.30 and still crashing. Noticed someone mentioned the same in the recent comments
