### ISSUE TITLE
[Linux] Short film contest videos don't play.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/Dota-2#1289] opened 2017-08-02 05:03 UTC
The short film contest voting page only shows a black space where the video is expected to be.

![20170801220232_1](https://user-images.githubusercontent.com/2745346/28858423-3e5748e4-7705-11e7-8638-9cbd478740f9.jpg)

[System info](https://gist.github.com/ramma/925cc19fb6fd7805979e)

Side note - When does voting close? I don't have easy access to other OS's to vote, and the workshop link in the blog goes to a page with "Voting for the Dota 2 - Short Film Contest starts on Wednesday, May 31st."

**Comment by kisak-valve** [comment] 2017-08-02 12:14
Possible duplicate of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/214.

**Comment by ramma** [comment] 2017-08-02 16:53
That bug says it works in OpenGL, but that's what I'm using and get no videos.

**Comment by r3pek** [comment] 2017-08-02 18:15
I tried with Vulkan and OpenGL and it doesn't work on any of them

**Comment by jazztickets** [comment] 2017-08-03 00:39
Works for me fine in Vulkan and OpenGL

System Info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/95ce9e4e293f9e082227e6bb428b48cfec781b06/gistfile1.txt

**Comment by gdrewb-valve** [comment] 2017-08-03 00:41
The Steam team believes they know what's going on.  The next Steam beta client will have a change to address it.

**Comment by gdrewb-valve** [comment] 2017-08-03 01:34
The beta Steam client update is live, give it a try.

**Comment by r3pek** [comment] 2017-08-03 01:50
Anything we could use to check if we got the update? like and md5 of some changed file or something? 'cause I don't think I got the update (and the videos are still not playing).

**Comment by gdrewb-valve** [comment] 2017-08-03 01:53
When you look at your Steam client settings, in the Account tab there's a "Beta participation" section.  What does that say?

**Comment by ramma** [comment] 2017-08-03 02:06
Restarted and got the beta updated, but the video area is still black. Not sure if there's much of use, but here's a console log where I clicked through a few pages of videos.

[console.log.txt](https://github.com/ValveSoftware/Dota-2/files/1195780/console.log.txt)

**Comment by r3pek** [comment] 2017-08-03 02:22
@gdrewb-valve Steam Beta client participation :) (or something like that)

**Comment by gdrewb-valve** [comment] 2017-08-03 02:46
I'll pass this on to the Steam team.

**Comment by Plagman** [comment] 2017-08-03 19:04
Can anyone still affected by black video issue post the terminal output? You'll need to fully shut down Steam and start it from a terminal in order to also get Dota's output into that terminal.

**Comment by r3pek** [comment] 2017-08-03 19:18
[steam_log.txt](https://github.com/ValveSoftware/Dota-2/files/1198340/steam_log.txt)

Can't really see anything special

**Comment by Plagman** [comment] 2017-08-03 23:41
Can you confirm whether today's Beta update fixes the issue?

**Comment by r3pek** [comment] 2017-08-03 23:59
@Plagman Yes. It works with Steam runtime now.

Any pointers to what it was so that it can work with native runtime too?

**Comment by Plagman** [comment] 2017-08-04 00:07
There was an internal timing issue in Steam's code that shouldn't really be affected by what other libraries are loaded. I would guess that there is a different unrelated issue with the web component's dependencies using the native runtime.

**Comment by r3pek** [comment] 2017-08-04 00:18
@Plagman ok, it's working on native too. My bad. You can close this now.

**Comment by ramma** [comment] 2017-08-04 01:11
I'm still getting the black screen.

[terminal.txt](https://github.com/ValveSoftware/Dota-2/files/1198979/terminal.txt)

**Comment by Plagman** [comment] 2017-08-04 01:25
Are you able to watch community broadcasts in the Steam client? Can you re-try the Dota short film scenario after having watched a broadcast in the client?

**Comment by ramma** [comment] 2017-08-04 01:33
Unless a update came after my last comment, I think I just hadn't gotten the latest. Had to restart Steam 3-4 times before the update install progress window was shown, and videos are working now. Thanks!

**Comment by kisak-valve** [comment] 2017-08-04 01:39
You can tell steam to check for updates immediately with the `Steam` -> `Check for Steam Client Updates...` menu option.

Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2017-08-04 01:39 UTC
Labels: reviewed
