### ISSUE TITLE
dark texture

### ISSUE THREAD

**Issue by Eignar17** [ValveSoftware/Dota-2#776] opened 2016-03-05 00:41 UTC
![captura de pantalla de 2016-03-04 18 25 37](https://cloud.githubusercontent.com/assets/8561550/13544153/f0deef4a-e240-11e5-9336-9c68d2cb3799.png)
is error in linux ubuntu 15.04 reset game in the error sometimes it happens

**Comment by gdrewb-valve** [comment] 2016-03-05 02:27
We'll need your specific driver, driver version and graphics hardware info (the Steam system info has this).  Also if you have an idea of what repro steps cause this that'll help.

**Comment by Tele42** [comment] 2016-03-05 02:41
This looks like a system missing s3tc... @Eignar17 are you using mesa and are missing 64 bit libtxc-dxtn-s2tc0?

**Comment by Eignar17** [comment] 2016-03-05 08:18
yes is in certain items it appears well and I must restart the game

**Comment by Eignar17** [comment] 2016-03-05 08:21
@Tele42 yes is bug in game reset game and fix and others not is dark

**Comment by Turmfalke2** [comment] 2016-03-06 19:46
I had this earlier today, restarting the game fixed it.

**Comment by danginsburg** [comment] 2016-03-07 15:20
@Eignar17 Please post Steam -> Help -> System Information so we can try to repro this.  Any additional information on how to reproduce this bug would be helpful.

**Comment by Eignar17** [comment] 2016-03-09 21:11
@danginsburg is update wind ubuntu 15.04 for 15.10 is bug I persists even though I have the latest version of the driver intel this error is already unusual but persists

**Comment by astroty** [comment] 2016-03-10 20:48
This error happened to me on Windows (Nvidia OpenGL) once. Can't reproduce it though

**Comment by danginsburg** [comment] 2016-03-15 13:40
I haven't personally repro'd this, but given the intermittent nature of this corruption and that it is happening across drivers and platforms, I suspect this might be a multithreading bug I fixed with the creation of renderstate objects.  Once that patch goes into a Dota 2 update I'll post here and ask if it is still reproducible.  If it is, we are going to need more specific system information.  None of the reports here have posted Help -> Steam -> System Information.

**Comment by danginsburg** [comment] 2016-03-20 19:53
Is this still happening with the most recent updates to Dota 2?

**Comment by Turmfalke2** [comment] 2016-03-20 19:54
hard to tell, I only ever had it happen once and was unable to reproduce it.

**Comment by gdrewb-valve** [comment] 2016-03-20 21:12
I think we can close this.  If it happens again we'll reopen.

**Closed as completed by gdrewb-valve** 2016-03-20 21:12 UTC
Labels: reviewed
