### ISSUE TITLE
[OSX] movetodirection command not working

### ISSUE THREAD

**Issue by C0ckerel** [ValveSoftware/Dota-2#747] opened 2016-01-31 12:45 UTC
Hi,

I'm using a macbook pro and the force move to a direction command isn't working. I've tried using:

bind "OPTION" +dota_unit_movetodirection
bind "," +dota_unit_movetodirection 
cl_dota_alt_unit_movetodirection "1"

I also have this enabled:
dota_unit_allow_moveto_direction "1"

 None of these combinations are working. Am I doing something wrong? It's extremely frustrating.

I've attached a copy of my config file.

Cheers

[config.cfg.txt](https://github.com/ValveSoftware/Dota-2/files/111265/config.cfg.txt)

**Comment by gdrewb-valve** [comment] 2016-01-31 17:24
It's unlikely this is Mac-specific, you might want to post at dev.dota2.com also.

**Comment by justSQL** [comment] 2016-01-31 20:11
With Reborn the command was renamed to cl_dota_alt_unit_movetodirection 1 (as you mentioned). On my Windows box pasting that to console and proceeding to test in a game it works just fine when pressing Alt and rightclicking somewhere. Are you trying to bind that to a different key or what? I'm not sure if it works with anything else than Alt.

**Comment by C0ckerel** [comment] 2016-02-01 08:09
Ideally I would use the 'option' key on mac to do this. However, as this didn't work I experimented with ',' just in case there was some special functionality on 'option' that couldn't be overwritten. This didn't work either. 
Finally I tried cl_dota_alt_unit_movetodirection 1, however this didn't work. 
I haven't been using the console, just the config file.

Is this the official Valve support place? I'm not sure how to get official feedback about this (dev.dota2.com linked to here).

**Comment by C0ckerel** [comment] 2016-02-01 08:12
Ok well the commands work via the console! 
Still not sure why the commands in config.cfg are having no effect.

For some reason, the fn, control, option, command and caps lock keys are all 'not valid'. Is there are reason for this or is it a bug?

**Comment by gdrewb-valve** [comment] 2016-02-01 23:46
I don't believe Reborn uses config.cfg.  If you put your commands in autoexec.cfg does that work?

Modifier keys like shift and control generally aren't allowed as key binds since that interferes with binding like Ctrl+2 for a control group.  I don't know specifically what the rules are for movetodirection.  If you want specifics post a question at dev.dota2.com where the general forums are.

**Comment by gdrewb-valve** [comment] 2016-02-05 23:51
Did autoexec.cfg work?

**Comment by gdrewb-valve** [comment] 2016-02-09 00:43
Closing as I believe this is expected behavior.  It's also not platform-specific.

**Closed as completed by gdrewb-valve** 2016-02-09 00:43 UTC
Labels: reviewed
