### ISSUE TITLE
[OSX] Game client crashes when joining a TI game as spectator during pick phase

### ISSUE THREAD

**Issue by keebuhm** [ValveSoftware/Dota-2#971] opened 2016-08-03 19:28 UTC
It crashes after showing the loading screen.

Late 2015 Retina 4k iMac
OS X 10.11.6

**Comment by Tele42** [comment] 2016-08-03 19:42
Duplicate of #918 / #922.

**Comment by gdrewb-valve** [comment] 2016-08-03 19:56
Closing duplicate.

**Closed as completed by gdrewb-valve** 2016-08-03 19:56 UTC
