### ISSUE TITLE
Dota 2 Mouse Camera moves up down left but not to the right. Any Ideas?

### ISSUE THREAD

**Issue by killdrm** [ValveSoftware/Dota-2#2326] opened 2023-05-09 01:08 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Ubuntu
* Nvidia Driver 530 Nvidia 940mx
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
expected the camera to go right when i move the mouse to the right but its not moving. It should move as it does to the left up and down when i move the mouse.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment] 2023-05-09 11:25
Hello @killdrm, you've described the issue which was evaluated at #2085, which is a distro package issue.

If your laptop isn't using a 1366x768 which is being seen as 1360x768, then please share your system information and we can ponder this further.

Closing as a duplicate of #2085.

**Closed as not planned by kisak-valve** 2023-05-09 11:25 UTC

**Comment by killdrm** [comment] 2023-05-10 20:10
installed those libraries, it is still not solving the problem.
