### ISSUE TITLE
[Linux] dota can not launch when using steam

### ISSUE THREAD

**Issue by bugsuse** [ValveSoftware/Dota-2#1270] opened 2017-07-14 04:20 UTC
I have trouble getting the logo and then crash when running DOTA 2 on openSUSE 42.2.  

I downloaded and installed steam and dota2 yesterday.

the information for error as fllow:

`Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198257515004 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198257515004
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor Intel Open Source Technology Center
DumpContextInfo: OpenGL renderer Mesa DRI Intel(R) Sandybridge Mobile 
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30
 failed to dlopen "/home/storm/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/storm/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Fontconfig warning: "/home/storm/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/storm/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
crash_20170714115956_1.dmp[2568]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170714115956_1.dmp
`
Thanks for your help!

**Comment by kisak-valve** [comment] 2017-07-14 12:32
Hello @bugsuse, did you try completely closing steam, then start steam from a terminal with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` (from https://github.com/ValveSoftware/steam-for-linux/issues/5000)?

**Comment by bugsuse** [comment] 2017-07-14 14:57
@kisak-valve  Thank you! It's working for me! But the game crashed when I launch the steam by desktop. And the steam update today, the trouble exist yet.

**Comment by kisak-valve** [comment] 2017-07-14 15:00
Glad to hear that helped. Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5000.

**Closed as completed by kisak-valve** 2017-07-14 15:00 UTC

**Comment by bugsuse** [comment] 2017-07-14 15:44
But the trouble happened even though running steam with STEAM_RUNTIME_PREFER_HOST_LIBRARIES =0 steam after dota and steam updated.

**Comment by pw00t** [comment] 2017-07-24 15:30
for how long we need to run STEAM_RUNTIME_PREFER_HOST_LIBRARIES =0 steam each time we want to play Dota? issue haven't been fixed so far.

**Comment by pwaterz** [comment] 2018-08-13 19:08
Recently ran into this issue. I updated my nvidia drivers to nvidia-driver-396, and I also update to the latest linux kernel and the game started loading again for me.
