### ISSUE TITLE
[Linux] Cursor fails to capture if tabbed out during loading

### ISSUE THREAD

**Issue by 32charactername** [ValveSoftware/Dota-2#503] opened 2015-09-28 18:11 UTC
If tabbed out when loading, the cursor will fail to capture, making edge panning incredibly difficult. Moving the cursor out of the window causes all inputs to fail, such as space, which I use to screen drag. All display modes are affected. It can be temporarily fixed by changing the window type, such as from windowed to borderless windowed and back. It does not seem to be an issue with multiple monitors, as this happens in windowed modes as well.

Lubuntu 15.04 with LXDE/OpenBox
nVidia 650 TI, drivers version 346.59
Two monitors, 1280x1024 with 1600x900 on right.

**Comment by danginsburg** [comment] 2015-09-28 18:36
Duplicate of #450.

**Closed as completed by danginsburg** 2015-09-28 18:36 UTC
Labels: reviewed
