### ISSUE TITLE
Error : LoadSystemAndDependencies

### ISSUE THREAD

**Issue by srelelele** [ValveSoftware/Dota-2#350] opened 2015-09-02 16:32 UTC
Hi all
i have some problem with dota 2 reborn beta..
i have manjaro linux the latest version

system info :

[srele@robot ~]$ inxi -Fx
System:    Host: robot Kernel: 3.18.20-1-MANJARO x86_64 (64 bit gcc: 5.2.0)
           Desktop: Xfce 4.12.3 (Gtk 2.24.28)
           Distro: ManjaroLinux 0.8.13.1 Ascella
Machine:   Mobo: MSI model: MS-7309 v: 1.0
           Bios: American Megatrends v: V9.4 date: 02/17/2009
CPU:       Dual core AMD Athlon X2 250 (-MCP-) cache: 2048 KB
           flags: (lm nx sse sse2 sse3 sse4a svm) bmips: 12060
           clock speeds: max: 3013 MHz 1: 3013 MHz 2: 3013 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Turks PRO [Radeon HD 6570/7570/8550]
           bus-ID: 02:00.0
           Display Server: X.Org 1.17.2 driver: radeon
           Resolution: 1680x1050@59.95hz
           GLX Renderer: Gallium 0.4 on AMD TURKS
           GLX Version: 3.0 Mesa 10.6.5 Direct Rendering: Yes
Audio:     Card-1 NVIDIA MCP61 High Definition Audio
           driver: snd_hda_intel bus-ID: 00:05.0
           Card-2 Advanced Micro Devices [AMD/ATI] Turks/Whistler HDMI Audio [Radeon HD 6000 Series]
           driver: snd_hda_intel bus-ID: 02:00.1
           Card-3 Pixart Imaging driver: USB Audio usb-ID: 002-002
           Sound: Advanced Linux Sound Architecture v: k3.18.20-1-MANJARO
Network:   Card-1: NVIDIA MCP61 Ethernet
           driver: forcedeth port: de00 bus-ID: 00:07.0
           IF: enp0s7 state: down mac: 00:24:21:38:5c:3d
           Card-2: Atheros AR9271 802.11n driver: ath9k_htc usb-ID: 001-002
           IF: wlp0s2f1u1 state: N/A mac: N/A
Drives:    HDD Total Size: 1000.2GB (4.1% used)
           ID-1: /dev/sda model: TOSHIBA_DT01ACA1 size: 1000.2GB
Partition: ID-1: / size: 913G used: 35G (4%) fs: ext4 dev: /dev/sda2
           ID-2: /boot size: 247M used: 41M (18%) fs: ext2 dev: /dev/sda1
           ID-3: swap-1 size: 4.15GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
Sensors:   System Temperatures: cpu: 36.5C mobo: N/A gpu: 44.5
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 179 Uptime: 1:26 Memory: 1178.4/3957.3MB
           Init: systemd Gcc sys: 5.2.0
           Client: Shell (bash 4.3.391) inxi: 2.2.28 

i installed the manjaro linux few fays ago , downloaded dota2 and try to play but it tells me that i have to download dota2 reborn so i did , and now its telling me to play dota 2 reborn, i cant play just dota2.. when i run dota 2 reborn beta i get some error message right at the start :

Error 
LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011' !

thats it..
sorry for bad eng. 
thanks :D

**Comment by gdrewb-valve** [comment] 2015-09-02 16:59
Likely a duplicate of #35 / #105.

**Comment by srelelele** [comment] 2015-09-02 17:03
so what should i do to fix it ?

**Comment by gdrewb-valve** [comment] 2015-09-02 17:15
Those issues have a couple of different suggestions, give them a read and see if those suggestions help.

**Comment by srelelele** [comment] 2015-09-02 17:19
ln -s /usr/lib/libudev.so.1 "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libudev.so.0

#105 is the same problem but this is not working for me.. maybie i need to wait ...10 minutes and nothing, just standing there in terminal

**Comment by gdrewb-valve** [comment] 2015-09-02 17:23
Is your user name 'hs'?  The home directory depends on the user name, so really the ln command is "create a symlink to the right place where you installed Steam".

**Comment by srelelele** [comment] 2015-09-02 17:27
oh.. nope.. thanks, fixed :)

**Comment by gdrewb-valve** [comment] 2015-09-02 17:28
The load error is fixed and this can be closed?

**Comment by srelelele** [comment] 2015-09-02 17:31
yes , thank you :)

**Comment by gdrewb-valve** [comment] 2015-09-02 17:31
Glad it worked, closing.

**Closed as completed by gdrewb-valve** 2015-09-02 17:31 UTC
Labels: reviewed
