### ISSUE TITLE
Player name containing Chinese text above health bar does not render

### ISSUE THREAD

**Issue by domxxxx** [ValveSoftware/Dota-2#672] opened 2015-12-08 12:42 UTC
Model：MacBook Pro (Retina, 13-inch, Early 2013)
OS：OS X 10.9.2 (13C64)

I suppose it's the exact issue with #457 Though the case is marked closed but the patch did not fix it for my client. 

My OS, Steam, and Dota 2 Reborn have their default languages set as English. When in game, Chinese texts displays well in all other scenarios, which includes but not limited to typed chats, player names on scoreboard, player names during loading screen, and player names during kill announcements. The player names above health bars however does not display any Chinese characters if there's any.

Please kindly review and advise. @danginsburg Thank you very much.

PS: I'm from SEA region so occasionally we communicate in Mandarin but I personally prefer my client to be in English, hence suffering from this teeny issue. I know it's not obstructive to gameplay but would really appreciate it being looked into. Once again, thanks!

Edit: By the way, after one of the recent updates, the Mac applications dock remains in view and obstructs the chat box and "PLAY DOTA" button upon launching Dota 2 in fullscreen mode. It goes away after switching back and forth between open applications (swiping with 4 fingers). I didn't have this issue even back in beta, and have not touched any settings since then.

**Comment by danginsburg** [comment] 2015-12-08 19:10
I can confirm this occurs on OSX and not on Windows, I will look into it.  It looks like an issue rendering chinese fonts when English is the chosen language.

**Comment by domxxxx** [comment] 2015-12-09 06:30
Thanks, not sure if this helps but back in source one, it was similar but slightly different. As in, during source one replays, professional player names such as "VG.iceiceice.天喔“ renders well above health bars whereas normal player names containing Chinese characters would have the Chinese characters overlap on each other resulting in a block of mess blocking the 50% of the top of the health bar.

During game plays in source one, it was an issue as if player names are lengthy and in Chinese, the health bar is basically fully blocked. In reborn, the Chinese names simply does not render as stated in the comment above. I've tried watching some professional matches like CDEC master and the player names with Chinese characters doesn't render as well.

As you have mentioned, the issue only haunts OSX as replays on Youtube displays well. Once again, thank you for looking into this and hope this helps.

**Comment by danginsburg** [comment] 2015-12-15 14:25
I have fixed this issue.  It will be in a future Dota 2 update.

**Comment by danginsburg** [comment] 2015-12-17 12:55
Fixed in Dec. 16th update.

**Closed as completed by danginsburg** 2015-12-17 12:55 UTC
Labels: reviewed
