### ISSUE TITLE
Courir Bug

### ISSUE THREAD

**Issue by chrissisura** [ValveSoftware/Dota-2#919] opened 2016-06-22 21:49 UTC
I just now played a game where i had massive lag everytime i used the courir. A friend of mine complainted about the same issue in the same game. Just wanted to let you know. If it goes on, i will give more information. Playing on OS X El Capitan

**Comment by Tele42** [comment] 2016-06-22 22:14
Possible duplicate of #863.

**Comment by gdrewb-valve** [comment] 2016-06-23 01:04
What type of courier was it?  Do you have a match ID or anything to look at?

We'll also need more specific system information, particularly RAM and GPU information.

**Comment by gdrewb-valve** [comment] 2016-06-24 21:37
Closing until we get enough information to investigate.

**Closed as completed by gdrewb-valve** 2016-06-24 21:37 UTC
Labels: reviewed
