### ISSUE TITLE
High CPU usage when in menu

### ISSUE THREAD

**Issue by engywook** [ValveSoftware/Dota-2#307] opened 2015-08-12 20:11 UTC
Hello,

After starting Dota2(both versions) I get ~130% CPU usage. That is without doing anything at all. In windows 7 CPU usage is like 8%  but that is not for reborn, haven't tried reborn in windows for a while...

 It looks like a busy wait somewhere:
[strace Dota 2 Reborn](https://gist.github.com/engywook/4c66b0b2a12d2da579e6#file-gistfile1-txt)

[strace dota_linux](https://gist.github.com/engywook/808c3d2bb6fb4eeefa3f#file-gistfile1-txt)

[Sys. Inf.](https://gist.github.com/engywook/7679f344473b2095ce2d#file-gistfile1-txt)

Maybe related to #7

**Comment by engywook** [comment] 2015-08-13 15:07
Today I "only" have ~70% CPU usage in menu. The only difference from yesterday is that I installed the ttf-liberation font to get names etc showing ingame. Maybe I'm missing something else, I have a pretty slim Archlinux install without Gnome/KDE/"What SteamOS uses".

[strace reborn](https://gist.github.com/engywook/eb96a268edd5beaf9442#file-gistfile1-txt)

EDIT: Disregard that, after restarting reborn it's ~160%

**Comment by computerquip** [comment] 2015-08-13 15:16
Have you tried turning vsync on to limit framerate? Or is the menu frame limited already?

**Comment by engywook** [comment] 2015-08-13 17:39
vsync makes it worse, ~230%. Could be a G-Sync issue I suppose.

**Comment by gdrewb-valve** [comment] 2015-08-14 21:57
Background info:  it's expected that the menu will take non-trivial CPU since it's animating and doing quite a few things even without user interaction.  On Windows GL mode takes about twice the CPU of DX9 (the default on Windows) because of variation in the drivers and calling patterns.  Then throwing in the fact that Windows splits 100% CPU usage among all processors and 8% DX9 CPU usage would equate to about 64% CPU usage on a quad-core machine in Linux and GL (although it is difficult to make straight-across comparisons between platforms).  Your 130% figure is high but not impossible.

This isn't going to change in the near term but leaving this open for future optimization possibilities.

**Comment by gdrewb-valve** [comment] 2015-10-23 19:22
How are things looking nowadays?  We've done a few optimization passes so the really bad cases should be fixed.  There'll always be room to make things better in the future but we'll close this out unless there a specific problem areas.

**Comment by gdrewb-valve** [comment] 2015-10-26 19:50
Closing pending more info.

**Closed as completed by gdrewb-valve** 2015-10-26 19:50 UTC
Labels: reviewed

**Comment by engywook** [comment] 2015-11-03 17:26
Hasn't really improved, I just started it now and it's at 70% accross all four cores.

After getting a game It's really weird though, if I change workspace the load is only 5% and I get disconnected if I don't change back. This is while running fullscreen.

**Comment by gdrewb-valve** [comment] 2015-11-03 20:33
70% is a pretty reasonable figure, that's about what we would expect.

**Comment by engywook** [comment] 2015-11-04 21:30
On four cores while not playing? Sounds like a lot to me. "Unfortunately" dota works pretty well so I haven't booted Windows in a few weeks. =) 
I don't know what I would get there. Doesn't really matter though,  I mostly have 100+fps while playing so cheers porting it to Linux.

What about the workspace switching, should I make an issue for it disconnecting or are you unlikely to look at it since I'm running a tiling wm?

**Comment by engywook** [comment] 2015-11-05 11:29
I guess I used across poorly, sorry. Each core has 70% load.

**Comment by gdrewb-valve** [comment] 2015-11-05 18:19
How are you getting the load numbers, are you looking at top output or something else?

For the workspace switching have you looked at issue #360?  I would guess it's the same underlying problem.  If no go ahead and open a separate issue.

**Comment by engywook** [comment] 2015-11-05 21:27
Yeah, I used htop.

#360 looks like my issue yeah, hadn't bothered to look at other issues yet. SDL fullscreen sounds about right. I used to play in borderless window(#555) but now I need to play fullscreen so I hadn't noticed this before.

**Comment by gdrewb-valve** [comment] 2015-11-05 22:54
Your numbers seem pretty high.  I just ran on my Linux system and the total CPU usage of Reborn across all threads was 103% (the new Haunted Colosseum theme seems to be taking a bit more than before).  The main menu is definitely expected to be using resources as it has a lot of animation, movies playing, web data retrieval and so on.  Yours seem out of line but short of building a duplicate of your box I couldn't say why.  It doesn't seem like a universal thing.
