### ISSUE TITLE
[Linux] Trying to Ping with ALT makes borderless windows to be moved

### ISSUE THREAD

**Issue by grasdaggel** [ValveSoftware/Dota-2#171] opened 2015-06-29 18:54 UTC
Problem is in title. If I start a new game and want to ping from time to time the window gets moved, instead of a ping. Reproduceable if you can see the drag-cursor ingame.

**Comment by gdrewb-valve** [comment] 2015-06-29 19:04
Is this a duplicate of #119?

**Comment by kingalca** [comment] 2015-06-29 20:02
Yes! can be closed. You're a issue hero, Drew!

**Closed as completed** 2015-06-29 20:03 UTC
Labels: reviewed
