### ISSUE TITLE
[Ubuntu] Bad text and number.

### ISSUE THREAD

**Issue by thegunner2401** [ValveSoftware/Dota-2#539] opened 2015-10-07 14:42 UTC
http://imgur.com/hvzeQq4
http://imgur.com/mc2k4pe
I've tried to reinstall ubuntu and dota 2 but the problem still persists.

**Comment by danginsburg** [comment] 2015-10-07 15:07
Please post Steam -> Help -> System Information.  This looks exactly like a known bug in mesa that will be fixed by updating to a newer version of mesa.

**Comment by danginsburg** [comment] 2015-10-07 15:08
Duplicate of #417.

**Closed as completed** 2015-10-12 19:50 UTC
Labels: duplicate, reviewed, drivers
