### ISSUE TITLE
dev.dota2.com authentication is broken! Even for new accounts!

### ISSUE THREAD

**Issue by TimZaman** [ValveSoftware/Dota-2#1522] opened 2018-11-26 22:02 UTC
Please fellow Valve devs, fix this issue:

I created an new account to get access to dev.dota2.com, but this failed with Auth failed - Missing key:
![image](https://user-images.githubusercontent.com/7721540/49044781-a8cfca80-f183-11e8-8486-2efa446bcbe2.png)

You can create a new forum account, but you cannot link it to your steam account, so you can't do anything in the fora.

**Comment by kisak-valve** [comment] 2018-11-26 22:10
Duplicate of #1516.

**Closed as completed by kisak-valve** 2018-11-26 22:10 UTC

**Comment by TimZaman** [comment] 2018-11-26 22:22
Thanks mate. I'd love to report the issues on the fora but (to my knowledge) no one can participate without this being fixed).

**Comment by valeologist** [comment] 2019-03-25 16:34
![Снимок экрана (2)](https://user-images.githubusercontent.com/44038528/54936912-25a16400-4f2c-11e9-9a68-681d45df8ac8.png)  
And when will it be fixed ?? And why does VALVE ignore everyone, and close the topic, when the error has not yet been fixed ??? WHAT are you for the developers that you do not want to correct? You show your navlivatelno attitude towards us all !!!
