### ISSUE TITLE
[LINUX] Graphics glitch on map edge in hero demo

### ISSUE THREAD

**Issue by gdmsl** [ValveSoftware/Dota-2#40] opened 2015-06-23 13:04 UTC
When scrolling past the edge of the map in the "hero demo" mode the render fails. An example of this bug is shown in the image below. The edge of the playable map is repeated several times in place of the dark zone.

I am running Dota 2 Reborn on a laptop with a nVidia card using `optirun -b primus %command%` to start the game

![Image of the glitch dring hero demo](http://i.imgur.com/iITd1X8.png)

**Comment by ace13** [comment] 2015-06-23 13:08
Seems like the same as #39
Which Nvidia driver are you running? Blob? Mesa? Version?

**Comment by danginsburg** [comment] 2015-06-23 17:59
Duplicate of #39

**Comment by gdrewb-valve** [comment] 2015-06-23 19:27
Closing duplicate.

**Closed as completed by gdrewb-valve** 2015-06-23 19:27 UTC
Labels: duplicate, reviewed
