### ISSUE TITLE
[MAC] Dota2 bug

### ISSUE THREAD

**Issue by shadowlzd** [ValveSoftware/Dota-2#685] opened 2015-12-17 07:34 UTC
i have a bug running dota2 reborn on my mac. It dont show the animated portraits in the "last game" interface of the homepage. and when i move the mouse to the heros displayed in my profiles, it dont show anything either. but these problems dont happen on my pc. plz tell me how to deal with this. Thx!

**Comment by Tele42** [comment] 2015-12-17 15:39
Duplicate of #54.

**Comment by gdrewb-valve** [comment] 2015-12-19 03:31
Closing duplicate.

**Closed as completed by gdrewb-valve** 2015-12-19 03:31 UTC
Labels: duplicate, reviewed
