### ISSUE TITLE
[OSX] Game randomly closes

### ISSUE THREAD

**Issue by michaelkclements** [ValveSoftware/Dota-2#806] opened 2016-03-25 10:38 UTC
I've tried to play a game of 10v10 as Pugna and the game has closed randomly around about 8 times so far. No error logs, just closes.

14 times now.

Edit: Tried watching pro games too and it closes as well.

**Comment by michaelkclements** [comment] 2016-03-25 10:41
Model Name:   iMac
  Model Identifier: iMac13,2
  Processor Name:   Intel Core i7
  Processor Speed:  3.4 GHz

**Comment by zanderzhng** [comment] 2016-03-25 11:41
Check temp fix at #794 .

**Comment by danginsburg** [comment] 2016-03-25 13:20
Likely duplicate of #794.  We are working on a fix.

**Comment by danginsburg** [comment] 2016-03-25 14:04
A patch was just pushed to Steam. Would someone that can reproduce the problem without risking an abandon please try running without "-threads 0". If you still see a crash, please provide the following info:

Crash dump (as the original poster did)
Steam -> Help -> System Information
Ideally repro instructions if you can repro reliably

**Comment by michaelkclements** [comment] 2016-03-25 14:17
Still happened to me watching a pro game.

"Connected to the Dota 2 game coordinator, logging in..." took a really long time too.

**Comment by michaelkclements** [comment] 2016-03-25 14:51
Gone through a 10v10 game and not closed though. Fixed potentially?

**Comment by danginsburg** [comment] 2016-03-25 16:58
OK, thanks. Going to close out this issue. If anyone sees any more crashes, please open a new bug with:
- Crash dump
- Steam -> Help -> System Information
- Ideally repro instructions if you can repro reliably

**Closed as completed by danginsburg** 2016-03-25 16:58 UTC
Labels: duplicate, reviewed
