### ISSUE TITLE
[Mac] Fonts are blocky, lots of yellow boxes and very low FPS

### ISSUE THREAD

**Issue by jmmL** [ValveSoftware/Dota-2#77] opened 2015-06-24 23:58 UTC
I hope this isn't a duplicate, but Reborn on Mac has extremely blocky fonts in-game (except for player names above heroes, which seem fine). There are also lots of yellow boxes where there ought to be hero portraits and spell icons etc. See another user's screenshot: https://i.imgur.com/dUpJYFd.png

Additionally, I get very low fps, maybe 3-5. The audio seems to play fine.

OS X 10.10.3 Yosemite, 13" MBP (early 2015): http://i.imgur.com/FNBS1y4.png

**Comment by jackyak** [comment] 2015-06-25 00:56
I'm having the exact same issues as jmmL, even after today's patch. The main Dota client works fine for me.

Thanks for all your hard work, Valve!

MacBook Air (11-inch, Mid 2012)
2 Ghz Intel Core i7
8 GB 1600 Mhz DDR3
Intel HD Graphics 4000 (1024 MB)
OSX Yosemite 10.10.3

**Comment by gdrewb-valve** [comment] 2015-06-25 01:13
Duplicate of #4.

**Closed as completed by gdrewb-valve** 2015-06-25 01:13 UTC
Labels: duplicate, reviewed
