### ISSUE TITLE
GL API Errors on AMD FOSS drivers

### ISSUE THREAD

**Issue by sarnex** [ValveSoftware/Dota-2#1] opened 2015-06-23 01:23 UTC
Hi guys. 

When I try the Dota 2 Reborn beta, there are constantly these errors:
Mesa: User error: GL_INVALID_VALUE in glScissor
Mesa: User error: GL_INVALID_OPERATION in glUseProgramStages(program not linked)

Here is my complete steam log
https://gist.github.com/sarnex/554f58fb28ce991c19b9#file-dota-2-reborn

My system info:
Radeon 7950, Mesa git, Kernel 4.1.0, Gentoo Linux

Let me know if you need more infromation.

Thanks,
sarnex

**Comment by sarnex** [comment] 2015-06-23 01:26
The menu graphics are also very glitchy, sometimes they don't appear or are flickering. I don't know if it's related.

**Comment by Plagman** [comment] 2015-06-23 01:58
Looks like we use a few extensions that are not supported by the radeonsi yet. We could do a better job of detecting that and failing to start, but I would let the Mesa people know about this regardless.

**Comment by imirkin** [comment] 2015-06-23 02:09
glScissor returning INVALID_VALUE means that negative width/height are being passed in. Mesa should support ARB_sso on all drivers, but it's one of the less-tested extensions (or rather, one of the ones with the biggest test surface), so the glUseProgramStages thing could happen for a million different reasons.

**Comment by imirkin** [comment] 2015-06-23 02:19
FWIW this is the code that generates the sso error. I'm in the process of getting the game, so I can't tell if these conditions are actually met and it's correctly returning that error or not.

      /* Section 2.11.4 (Program Pipeline Objects) of the OpenGL 4.1 spec
       * says:
       *
       *     "If the program object named by program was linked without the
       *     PROGRAM_SEPARABLE parameter set, or was not linked successfully,
       *     the error INVALID_OPERATION is generated and the corresponding
       *     shader stages in the pipeline program pipeline object are not
       *     modified."
       */
      if (!shProg->LinkStatus) {
         _mesa_error(ctx, GL_INVALID_OPERATION,
                     "glUseProgramStages(program not linked)");
         return;
      }

**Comment by Plagman** [comment] 2015-06-23 02:20
I don't have a setup that can reproduce this, but if you find any problems with the engine's use of ARB_sso let us know!

**Comment by sarnex** [comment] 2015-06-23 03:38
I've created an apitrace for anyone interested

https://idontevenlift.no-ip.org/dota2.trace.xz

Thanks,
sarnex

**Comment by imirkin** [comment] 2015-06-23 04:30
OK, so the sso failures were mesa's bad. Patch available at http://patchwork.freedesktop.org/patch/52603/ . Will merge soonish unless people point out some issue.

However the glScissor errors are pretty unambigiously Dota 2 Reborn's bad. You can see this yourself in the trace... just a few examples below, but there are tons:

    764104 @1 glScissor(x = 1, y = 0, width = -1, height = 65573)
    748602 @1 glScissor(x = -16313741, y = -16313738, width = -16313741, height = -1643902141)
    742166 @1 glScissor(x = 48, y = 53, width = -1, height = 65589)
    724556 @1 glScissor(x = -16313741, y = -16313738, width = -16313741, height = -1643902141)

These happen a ton in the trace, and either width or height being negative is illegal in GL.

**Comment by imirkin** [comment] 2015-06-23 04:37
One thing to note is that the radeonsi driver doesn't support ARB_viewport_arrays, and you're querying MAX_VIEWPORTS and getting 0 back, so perhaps you're looping over # of viewports somewhere and so you end up not setting anything? Just a guess based on an observation airlied made on IRC.

**Comment by gdrewb-valve** [comment] 2015-06-23 04:49
Yes, the viewport array issue is exactly what you describe, we are not checking for the presence of the extension.

**Comment by danginsburg** [comment] 2015-06-23 11:16
I've checked in a fix for the GL_ARB_viewport_array issue and confirmed it can cause uninitialized scissor values (as well as viewport values).  The fix will be in the next update.

**Comment by gdrewb-valve** [comment] 2015-06-24 23:11
The viewport errors should be resolved in the 6/25 update.

**Closed as completed by gdrewb-valve** 2015-06-24 23:11 UTC
Labels: reviewed
