### ISSUE TITLE
[Linux] Game crashes with Silencer games because of dota+ quest

### ISSUE THREAD

**Issue by LDD19** [ValveSoftware/Dota-2#1430] opened 2018-03-28 18:31 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/LDD19/2cc49628f131628d12da5b100c0fc3b4
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? No
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
My game crashed 2 times in a row while playing Silencer with the get 3/6/9 assists before the game timer reaches 15:00 quest. The game will crash at 15:00 flat then some random crashes will happen afterwards during teamfights so I'd assume that it's related to the assist counter. 

#### Steps for reproducing this issue:

1. Pick Silencer 
2. Pick the "get 3/6/9 assists before the game timer reaches 15:00" quest on Dota+ 
3. The game will always crash at 15:00

**Comment by gdrewb-valve** [comment] 2018-03-28 19:55
Duplicate of the other issues here but I'll hold it open for a bit.

**Comment by gdrewb-valve** [comment] 2018-04-04 22:24
The April 3 update should help with this.

**Comment by gdrewb-valve** [comment] 2018-04-07 23:06
Closing as this appears to be fixed.

**Closed as completed by gdrewb-valve** 2018-04-07 23:06 UTC
Labels: reviewed
