### ISSUE TITLE
[Linux] Fullscreen missing after 6/30 update?

### ISSUE THREAD

**Issue by kon14** [ValveSoftware/Dota-2#178] opened 2015-07-01 07:14 UTC
I'm pretty sure it was there last time I launched the reborn client.

http://i.imgur.com/0K4MMN2.jpg

**Comment by presianbg** [comment] 2015-07-01 07:24
I believe they removed it for some reason:
https://github.com/ValveSoftware/Dota-2-Reborn/issues/101

Duplicate of #101

**Comment by budimanjojo** [comment] 2015-07-01 09:48
It was missing from 6/26 update. Now "use monitor settings" is fullscreen with your video card resolution set.

**Comment by kon14** [comment] 2015-07-01 14:06
There was indeed a change referenced in #101, though there's no clarification about whether the "Use my monitor's current resolution" setting is creating a borderless window or fullscreen.

The game is locking the keyboard even on borderless window (no alt+dragging) and there doesn't seem to be any noticeable performance difference on my part so I couldn't find out what the case is.

Is it essentially fullscreen with a fancy name or am I running a native res borderless window?

**Comment by gdrewb-valve** [comment] 2015-07-01 15:26
It's a monitor resolution borderless window (SDL's FULLSCREEN_DESKTOP mode).

**Closed as completed** 2015-07-01 15:26 UTC
Labels: reviewed
