### ISSUE TITLE
[OSX] Game crashes after hero selection

### ISSUE THREAD

**Issue by nlIthi** [ValveSoftware/Dota-2#451] opened 2015-09-15 22:40 UTC
After the Reborn patch my girlfriend has been unable to enter a DOTA match. The dashboard loads fine, and after the loading screen the hero selection all works as predicted. But after clicking on the enter match button, the computer totally freezes. Tabbing out does not work, but the cursor keeps reacting. The sound continues as if I was in the game itself.

The things I tried:
- Reset video config

---- System info ----
Processorgegevens:
    Model: iMac7,1
    Leverancier: GenuineIntel
    CPU-soort: 0x6
    CPU-model: 0xf
    CPU Stepping: 0xa
    CPU-type: 0x0
    Snelheid: 2800 Mhz
    2 logische processoren
    2 fysieke processoren
    HyperThreading:  Niet ondersteund
    FCMOV:  Ondersteund
    SSE2:  Ondersteund
    SSE3:  Ondersteund
    SSSE3:  Ondersteund
    SSE4a:  Niet ondersteund
    SSE41:  Niet ondersteund
    SSE42:  Niet ondersteund

Netwerkgegevens:
    Netwerksnelheid:  

Versie van besturingssysteem:
    MacOS 10.10.5 (64 bits)

Videokaart:
    :  ATI,RadeonHD2600

```
Versie stuurprogramma:  1.2
Datum stuurprogramma: 0  0
OpenGL-versie: 2.1
Kleurdiepte bureaublad: 32 bits per pixel
Vernieuwingsfrequentie monitor: 0 Hz
Leverancier-id:  0x1002
Apparaat-id:  0x9583
Aantal monitoren:  1
Aantal logische videokaarten: 1
Resolutie primaire beeldscherm:  1920 x 1200
Bureaubladresolutie: 1920 x 1200
Grootte primaire beeldscherm: 20.39" x 12.60"  (23.94" diag)
                                        51.8cm x 32.0cm  (60.8cm diag)
Primaire VRAM: 256 MB
```

Geheugen:
    RAM:  2048 MB

Overige:
    Taal gebruikersinterface: Nederlands
    Microfoon:  Not set
    Type media: Dvd
    Totale beschikbare ruimte op vaste schijf:  2020894 Mb
    Grootste vrije blok op vaste schijf:  438805 Mb

Geïnstalleerde software:
    Aangifte inkomstenbelasting voor ondernemers 2013
    Acrobat Distiller
    Adobe Acrobat Pro
    Adobe Bridge CC
    Adobe Bridge CS6
    Adobe Content Viewer
    Adobe Digital Editions 2.0
    Adobe Edge Animate CC 2014
    Adobe Edge Code CC
    Adobe Edge Reflow CC
    Adobe Encore CS6
    Adobe Extension Manager CC
    Adobe Extension Manager CS6
    Adobe Fireworks CS6
    Adobe Illustrator CC 2014
    Adobe Illustrator CS4
    Adobe InCopy CC 2014
    Adobe InDesign CC 2014
    Adobe InDesign CS6
    Adobe Media Encoder CC 2014
    Adobe Muse CC 2014
    Adobe Photoshop CC 2014
    Agenda
    Analyze Documents
    App Store
    ATFViewer
    Audiobook Builder
    Automator
    Berichten
    blender
    blenderplayer
    CleanMyMac 3
    Contact Sheets
    Contacten
    DivX Converter
    DivX Player
    DivX Preferences
    Dota 2
    DPS App Builder
    Export Flash Animation
    ExtendScript Toolkit
    FaceTime
    FormsCentral For Acrobat
    Foto's
    Fotolader
    Game Center
    Gmail
    Google Chrome
    Google Drive
    Google Search
    Herinneringen
    iBooks
    Install AwayBuilder
    Kaarten
    Launchpad
    Make Calendar
    Microsoft Alerts Daemon
    Microsoft Chart Converter
    Microsoft Clipgalerie
    Microsoft Database Daemon
    Microsoft Database Utility
    Microsoft Document Connection
    Microsoft Excel
    Microsoft Graph
    Microsoft Office-configuratieassistent
    Microsoft Office-meldingen
    Microsoft Outlook
    Microsoft PowerPoint
    Microsoft Query
    Microsoft Upload Center
    Microsoft Word
    Mission Control
    Mumble
    My Day
    naib
    Needle Works
    Notities
    Office365Service
    Open XML for Excel
    org.eclipse.equinox
    Plaknotities
    RAR Extractor Free
    Scribus
    Skype
    Solver
    Steam
    SyncServicesAgent
    TeamViewer
    Template
    Transmission
    Uninstall DivX for Mac
    Verbinding met extern bureaublad
    Vergelijkingseditor
    VLC
    Web Gallery
    YouTube

**Comment by danginsburg** [comment] 2015-09-15 23:52
This appears to be a duplicate of #345.  The problem appears to be impacting Macs with HD 2400/2600.  I'm closing because I believe it's the same issue and we are still looking into it.

**Closed as completed by danginsburg** 2015-09-15 23:52 UTC
Labels: duplicate, reviewed

**Comment by nlIthi** [comment] 2015-09-16 07:52
It looks like it is a duplicate. On the other hand, my game does not load at all; i don't see the map, can not proceed to my lane.
