### ISSUE TITLE
[OSX] Graphics Failure In-Game and Hero Browser

### ISSUE THREAD

**Issue by blakeb155** [ValveSoftware/Dota-2#262] opened 2015-07-23 15:03 UTC
My client appears to run fine, however trying to play a game or browse heroes causes horrific graphics errors. (see photos)

I'm on an older machine that was top of the line at the time - Source 1 client works fine me.

Please help
![screen shot 2015-06-29 at 8 08 02 pm](https://cloud.githubusercontent.com/assets/13469795/8853437/f77aa0dc-319d-11e5-95be-07f8bcfc3a64.png)
![screen shot 2015-06-23 at 2 14 10 pm](https://cloud.githubusercontent.com/assets/13469795/8853743/8b791696-319f-11e5-9ec1-908f588f5208.png)

Specs:

iMac (27-inch, Late 2009)
2.8 Ghz Intel Core i7
8GB  DDR 3 RAM
Ati Radeon HD 4850 512 MB
Running latest OS X (Yosemite)

**Comment by bklooster** [comment] 2015-07-24 02:15
Might be similar to problem #24. It appears you're using all using the same AMD/ATI cards that have the same level of OpenGL compatibility.

**Comment by blakeb155** [comment] 2015-07-24 03:06
Ah yes, you are correct @bklooster that's definitely my issue (#24)

Sorry for the repost.

Valve team - let me know if I can provide any more info to support

**Comment by danginsburg** [comment] 2015-07-24 14:36
This is a duplicate of #24.  I have filed a Radar with Apple and am in contact with AMD.  I will post progress if there is any.

**Comment by danginsburg** [comment] 2015-08-19 14:17
Closing as duplicate of #24, we will track any updates we have there.

**Closed as completed by danginsburg** 2015-08-19 14:17 UTC
Labels: duplicate, reviewed, drivers
