### ISSUE TITLE
[macOS] Low FPS after 7.07

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1354] opened 2017-11-27 06:51 UTC
My config is i7-7700K | 32 GB DDR4 | GTX 970 | 4K display.

Before 7.07 I've played on ~60 FPS on middle|high graphics settings with lags in complex scenes (see my previous issues).

Now FPS is about 30-40 on ANY, ultra-low or ultra-high settings.

**Comment by oxycoder** [comment] 2017-11-27 16:28
Same here.
Macbook Pro with eGPU RX 580 8GB, cant pass 40 fps on 4K
I also try with Asus Strix 970, FPS can't pass 35.
On Bootcamp, I can get 60 FPS+ with both card above

**Comment by gdrewb-valve** [comment] 2017-11-27 18:23
Duplicate of #1339.

**Closed as completed by gdrewb-valve** 2017-11-27 18:23 UTC
