### ISSUE TITLE
[LINUX+VULKAN] steam overlay friend chat not working when use vulkan

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1140] opened 2016-12-27 08:07 UTC
ingame chat works to chat with friends out of game but when use steam overlay it does not work. can not input text. i did not notice any other issues with the overlay yet.

 kubuntu 16.04 | 4.4.0-57-generic #78-Ubuntu | plasma 5. i disabled fullscreen desktop effects already for another fix with the plasma 5 panel messing with edge panning and the window spread also messing with it. so im sure that is not the issue.

nvidia geforce 730m 2gb with recent 375.26 drivers.

**Comment by kisak-valve** [comment] 2016-12-27 13:18
Closing as a duplicate of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/11.

**Closed as completed by kisak-valve** 2016-12-27 13:18 UTC
Labels: duplicate
