### ISSUE TITLE
[Linux] [Reborn] No brightness slider

### ISSUE THREAD

**Issue by e1usion** [ValveSoftware/Dota-2#428] opened 2015-09-12 20:55 UTC
In Windows, upon choosing "Exclusive fullscreen" option in Video tab, brightness slider appear.
There is no "Exclusive fullscreen" option in Linux client, thus there is no brightness slider. Choosing any other video option doesn't solve that problem.

OS: Archlinux x86-64
GPU: Nvidia GTX 750

**Comment by gdrewb-valve** [comment] 2015-10-12 17:04
Duplicate of #63.

**Closed as completed by gdrewb-valve** 2015-10-12 17:04 UTC
Labels: enhancement, reviewed
