### ISSUE TITLE
Weird video bug that renders the game unplayable on Mac

### ISSUE THREAD

**Issue by vassil-stoimenov** [ValveSoftware/Dota-2#2445] opened 2023-09-01 01:42 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Since yesterday morning, after an update, I have not been able to play because once a match starts, the screen consists of sporadically flashing colors. Somehow the minimap, the shop, and all other stuff on the bottom looks relatively normal. Please see linked screenshots. 

Everything only looks normal on hero demo mode.

I have a MacBook Pro (Retina, 15-inch, Late 2013)

I'm afraid yesterday's update rendered my computer obsolete.

Would greatly appreciate any help.

Game bug screenshot 1 - https://ibb.co/zZfJH0r
Game bug screenshot 2 https://ibb.co/c8FPRzL

Specs:
- Processor:    2 GHz Quad-Core Intel Core i7
- RAM:             16 GB 1600 MHz DDR3
- Graphics:      Intel Iris Pro 1536 MB

I even tried updating to lastest version of iOS but that didn't help either.

**Comment by dotagoat** [comment] 2023-09-01 03:22
same problem, really awful mac QA department there. They literally fixed a bug where the game wouldnt launch this morning, and didnt even bother to see if a game would work. Screen looks like its been cracked.

**Comment by dotagoat** [comment] 2023-09-01 03:26
I found a fix if you're interested. Right click Dota2 in steam library, click propeties, under launch options type "-gl" without the quotes. Game works fine now. Pretty sure these guys accidnetly deleted the GL option for mac, it only shows vulkan now in default.

**Comment by dotagoat** [comment] 2023-09-01 03:29
Some slight weird graphics stuff still..but its playable

**Comment by dotagoat** [comment] 2023-09-01 04:50
I lied its unplayable. Please fix.

**Comment by vassil-stoimenov** [comment] 2023-09-01 05:27
It’s real terrible, what am I to do with my addiction now??

**Comment by Talgoo** [comment] 2023-09-01 09:46
Same thing here!!! unplayable!
I think this started when Vulkan was forced on all of us.

**Comment by b10nde1** [comment] 2023-09-01 15:32
Hello guys, I use an Old but gold MBP mid 2014 (i7 16Gb Ram) and I got this issue every time after major update (new battle pass or new fancy bundle of skins)...

So far and for sure they don't really care abt us (mac user xd)... but based on what I see this is always related with major update.

To go more in the tech stuff, it's due to the .vpk files with the update (used by developer for map, hero modelling mean also new skin and animation with new battle pass).

What I usually do is renaming all vpk file (if before "dashboard.vpk" rename it into "dashbaord_01.vpk" inside below path and then restart steam client and run dota 2

```/Users/[YourUserNameHere]/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/maps/scenes/dashboard_background```

Or open it from steam 
_ go to Dota 2 Properties using the wheel icon “Manage”
_ got o LOCAL FILES and click on browse
_ go to to game > dota > maps > scenes > dashboard_background
_ and rename all .vpk file 

The purpose of renaming all .vpk file is to avoid your dota2 client to load many unnecessary fancy animation in the background (welcome dashboard etc...)... For me so far, what I want is just playing even some hereos looks like naked on the map

Moreover... keep in mind this is not a permanent solution since I always need to re-do the same process after **major update**

Hope above can help / fix until DOTA2 @ValveSoftware  push a permanent fix on there release branch

![image](https://github.com/ValveSoftware/Dota-2/assets/20561039/afe53efd-eea3-4ec8-8929-c7317086383e)

**Comment by Talgoo** [comment] 2023-09-01 19:08
From my test with local bots that seems to work. 

Here is a script that renames all the .vpk files in the folder, it will add to them `_render_bug` at the end of the name as @b10nde1 suggested <3.

```bash

#!/bin/bash

# Check if a directory path is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

# Get the directory path from the argument
directory="$1"

# Check if the directory exists
if [ -d "$directory" ]; then
    cd "$directory" || exit 1

    # Loop through all .vpk files in the directory
    for file in *.vpk; do
        if [ -e "$file" ]; then
            # Extract the file name without the extension
            filename="${file%.*}"

            # Append "_render_bug" to the filename
            new_filename="${filename}_render_bug.vpk"

            # Rename the file
            mv "$file" "$new_filename"
            echo "Renamed: $file -> $new_filename"
        fi
    done

    echo "All .vpk files in '$directory' renamed with '_render_bug' suffix."
else
    echo "Directory not found: $directory"
fi
```


you can use it like that (in case you saved the script under the name `rename_vpk.sh`: 
`./rename_vpk.sh /path/to/your/directory`

Replace "/path/to/your/directory" with the actual directory path where your .vpk files are located.

---- UPDATE ----
renaming the files isn't working 😢

**Comment by dotagoat** [comment] 2023-09-02 03:03
lmao 3 days volvo cant even fix such a simple error. No QA team? 13 billion dollars in revenue and can't dedicate a few heads to QA'ing the mac versions. typical american corporate mindset

**Comment by dotagoat** [comment] 2023-09-02 04:08
gg

![Screen Shot 2023-09-01 at 9 08 10 PM](https://github.com/ValveSoftware/Dota-2/assets/131418802/c439ab24-6809-4007-aea9-208a64634596)

![Screen Shot 2023-09-01 at 9 09 23 PM](https://github.com/ValveSoftware/Dota-2/assets/131418802/417e08c9-4334-4e24-b53d-ba03daed49b9)

**Comment by Praphin** [comment] 2023-09-02 05:26
Same here. Guys Any fix?

**Comment by Talgoo** [comment] 2023-09-02 09:17
Gotta buy and switch to windows 🥲

**Comment by GenaTkach** [comment] 2023-09-02 10:28
Same problem

**Comment by rizadwiandhika** [comment] 2023-09-02 17:48
None of valve team review this **major issue**? what a shame

**Comment by vassil-stoimenov** [comment] 2023-09-02 19:40
> Replying to https://github.com/ValveSoftware/Dota-2/issues/2445#issuecomment-1702939554

I tried this, in fact renamed all files, but nothing changed unfortunately.

**Comment by dotagoat** [comment] 2023-09-02 20:24
WCYD. Mac OS users are second class citizens when it comes to games. You'd think by now this would be resolved

**Comment by dotagoat** [comment] 2023-09-02 20:27
volvo please fix. what the fuck do we spend money on this game for if we cant even access it. i'll give you guys until midday and then its scorched earth tactics via my followers. gluck

**Comment by vassil-stoimenov** [comment] 2023-09-02 20:30
Haha straight Les Grossman on em

**Comment by dotagoat** [comment] 2023-09-02 20:35
its even funnier becuase I think they tried. But didnt finish the job. There's been a few patch updates since this thread was created. Each time, the amount of map space with fucked up pixels shrinks. But it's still there primarily near river. Looks they started at the bases but they forgot to check the middle of the map. I'm pretty sure its related to their trees...fucking animals so fuckign lazy

**Comment by 4erepaxen** [comment] 2023-09-02 23:36
#2452

**Comment by DenisMoskalkov** [comment] 2023-09-02 23:40
The same issue. Mac pro with Intel Iris. Unplayable!
But when i starts game  with the  bots  issue is not reproduced.

**Comment by 4erepaxen** [comment] 2023-09-02 23:42
Hi @DenisMoskalkov
Try more that 1 time if not, move the camera around the map in some places there will be a problem
if everything is ok then i'm happy for you

**Comment by 4erepaxen** [comment] 2023-09-02 23:48
<details><summary>Your system information</summary>

System information from steam (Steam -> Help -> System Information) in a [gist](https://gist.github.com/):

```
Computer Information:
Manufacturer: Apple
Model: MacBookAir7,2
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
CPU Family: 0x6
CPU Model: 0x3d
CPU Stepping: 0x4
CPU Type: 0x0
Speed: 1600 MHz
4 logical processors
2 physical processors
Hyper-threading: Supported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
MacOS 12.5.1 (64 bit)
Video Card:
Driver: Intel HD Graphics 6000
Driver Version Not Detected
OpenGL Version: 4.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID: 0x8086
DeviceID: 0x1626
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 11.22" x 7.01" (13.23" diag), 28.5cm x 17.8cm (33.6cm diag)
Primary VRAM: 1536 MB
Memory:
RAM: 8192 Mb
```

</details>

Have you checked for system updates?: Yes

Are you using the latest stable video driver available for your system? Yes

Have you verified the game files?: Yes

Please describe your issue in as much detail as possible:

No bugs with render map.

Steps for reproducing this issue:

Always reproduce

Start Allpick - any
Usually the problem is immediately visible,
if not, move the camera around the map
In some places there will be a problem


![Снимок экрана 2023-09-03 в 02 30 19](https://github.com/ValveSoftware/Dota-2/assets/112718720/c2235584-2b03-477d-9448-467f3dfce7da)
![Снимок экрана 2023-09-03 в 02 30 38](https://github.com/ValveSoftware/Dota-2/assets/112718720/d42257cf-4ac4-4779-8b85-1979ee84a396)
![Снимок экрана 2023-09-03 в 02 30 45](https://github.com/ValveSoftware/Dota-2/assets/112718720/369bd349-d311-448a-beac-5c118113a57f)
![Снимок экрана 2023-08-31 в 19 58 52](https://github.com/ValveSoftware/Dota-2/assets/112718720/d76dbfd0-f416-467d-9c52-2fb90b267145)
![Снимок экрана 2023-08-31 в 19 59 02](https://github.com/ValveSoftware/Dota-2/assets/112718720/2fbcef0d-d1b4-43f1-9e75-36e17656c751)
![Снимок экрана 2023-08-31 в 19 59 12](https://github.com/ValveSoftware/Dota-2/assets/112718720/fac3caf7-28db-439f-9d60-a64d9af077b6)
![Снимок экрана 2023-08-31 в 20 44 08](https://github.com/ValveSoftware/Dota-2/assets/112718720/e1607945-e63f-4ac9-8a6c-886827f6590e)

**Comment by rizadwiandhika** [comment] 2023-09-02 23:54
It was solved guys ([check this out](https://github.com/ValveSoftware/Dota2-Gameplay/issues/11361#issuecomment-1703915017)). Not 100% solved but it becomes playable at least

**Comment by 4erepaxen** [comment] 2023-09-03 00:04
Thx @rizadwiandhika

**Comment by dotagoat** [comment] 2023-09-03 02:23
does it work?

**Comment by vassil-stoimenov** [comment] 2023-09-03 04:12
Yes, it seems like it does

**Comment by naner-code** [comment] 2023-09-03 16:43
> It was solved guys ([check this out](https://github.com/ValveSoftware/Dota2-Gameplay/issues/11361#issuecomment-1703915017)). Not 100% solved but it becomes playable at least

It really works but also make the game crash all the time. Sad times to mac users

**Comment by danginsburg** [comment] 2023-09-05 18:08
A fix for this will be in the next Dota 2 client update.

**Comment by kisak-valve** [comment] 2023-10-07 02:00
Closing per the last comment.

**Comment by m-irfan** [comment] 2023-10-09 00:06
Still not fixed BTW:

Installed and played today on MacOS 14.0
Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB

<img width="1680" alt="Screenshot 2023-10-09 at 3 01 44 AM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/16814075/00821f6b-e0af-4736-934a-152f4ba318d5">
<img width="1680" alt="Screenshot 2023-10-09 at 3 19 14 AM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/16814075/28f38933-dd32-4d12-ab81-0b06e7141db7">

**Comment by m-irfan** [comment] 2023-10-09 00:07
Reopen this issue please

**Comment by m-irfan** [comment] 2023-10-09 00:36
Thank you for quick response!
You can close this issue.

I have reported my issue here
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7519, which is still open and seems more appropriate to my issue.

But there is no assignee, can you please also assign that issue to someone?

**Closed as completed** 2023-10-09 01:06 UTC

**Comment by xxtochoxx** [comment] 2024-02-10 16:09
-sw works
<img width="285" alt="mac" src="https://github.com/ValveSoftware/Dota-2/assets/7839541/9117816a-1bec-41c2-b79d-5ebe9cde1bd1">
