### ISSUE TITLE
[Linux] broken rendering in-game after monitor resolution change

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#131] opened 2015-06-27 05:54 UTC
This issue stems from https://github.com/ValveSoftware/Dota-2-Reborn/issues/130 where Dota launches on the wrong monitor for me, and I have to move it to my main monitor. Regardless, the game should handle resolution changes as the Source 1 version did without issues.

When the game launches on my small monitor, everything looks ok:

![2015-06-27_00001](https://cloud.githubusercontent.com/assets/110988/8390667/c3818ba6-1ce4-11e5-92ea-ed00c7bae6a9.jpg)

But after I move it to the bigger one, there is corruption in the inventory area:

![2015-06-27_00002](https://cloud.githubusercontent.com/assets/110988/8390668/cd044a9c-1ce4-11e5-9aff-3c35b7b6e67e.jpg)

**Comment by Turmfalke2** [comment] 2015-06-27 15:19
I experienced something similar when I used my window managers key binding to bring reborn into windowed mode and back again to full screen.

**Comment by Kirov123** [comment] 2015-06-28 19:47
I feel that it would be best to be able to choose what monitor to use with a simple drop-down.

**Comment by danginsburg** [comment] 2015-08-22 19:04
Can you guys try using the command-line parameter -sdl_displayindex N (where N=0,1,etc. for the number of the display).  This will control which monitor the window appears on.  Please report back if this resolves your issue.  I have tried using this on a dual display with primary 1920x1080 and secondary 2560x1440 and I can switch resolutions fine on both using -sdl_displayindex.

**Comment by danginsburg** [comment] 2015-08-24 20:07
I believe this is a duplicate of #2 and that bug has been resolved.  From my testing, I believe this works properly using -sdl_displayindex.  Please reopen if this still happens with the latest client and post repro instructions.

**Closed as completed by danginsburg** 2015-08-24 20:07 UTC
Labels: reviewed
