### ISSUE TITLE
DOTA2 doesn't start on linux

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#1622] opened 2019-06-16 20:12 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Pharmasolin/e22f60b19bc4d2d5c3c1041460266a0b): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes 430.26]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Game wouldn't start. It says Running and then process crashes with no error.
Tried with -opengl tag (default in settings were vulkan), tried to go back to regular steam client version, same issue as on steam beta.

#### Steps for reproducing this issue:

1. Download game
2. Press play
3. ???

**Comment by kisak-valve** [comment] 2019-06-16 20:25
Hello @Pharmasolin, please try `-vulkan_disable_steam_shader_cache` or `-gl` in the game's launch options. This should be a duplicate of the issue being tracked at #1619 / https://github.com/ValveSoftware/Dota-2-Vulkan/issues/311.

**Comment by Pharmasolin** [comment] 2019-06-16 20:30
@kisak-valve Hi, thanks for the info, I googled dota2 github and didn't scroll page a bit to see dota2 vulkan rep.

Your suggestion works for me.

**Comment by kisak-valve** [comment] 2019-06-16 20:36
Thanks, closing as a duplicate.

**Closed as completed by kisak-valve** 2019-06-16 20:36 UTC
Labels: duplicate, reviewed
