### ISSUE TITLE
[Linux] 'Rainy' audio in Manjaro Linux x86_64 (Valve's runtime) after the 26/06 update

### ISSUE THREAD

**Issue by EPadronU** [ValveSoftware/Dota-2#126] opened 2015-06-27 04:36 UTC
### Description

As the title says, I'm experiencing a audio problem and the best way I can describe it is that it's like rain... This is happening after the 26/06 update.
### Machine's specs

`uname -a`

```
Linux sophy 3.19.8.1-1-MANJARO #1 SMP PREEMPT Sat May 30 07:43:25 UTC 2015 x86_64 GNU/Linux
```

`lspci -vv`

```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
        DeviceName:  Onboard IGD
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 10c0
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 26
        Region 0: Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
        Region 2: Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Region 4: I/O ports at f000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915
```

`mhwd -lh -d`

```
08: PCI 02.0: 0300 VGA compatible controller (VGA)
  SysFS ID: /devices/pci0000:00/0000:00:02.0
  SysFS BusID: 0000:00:02.0
  Hardware Class: graphics card
  Device Name: "Onboard IGD"
  Model: "Intel 3rd Gen Core processor Graphics Controller"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x0166 "3rd Gen Core processor Graphics Controller"
  SubVendor: pci 0x1462 "Micro-Star International Co., Ltd."
  SubDevice: pci 0x10c0 
  Revision: 0x09
  Driver: "i915"
  Driver Modules: "drm"
  Memory Range: 0xf7800000-0xf7bfffff (rw,non-prefetchable)
  Memory Range: 0xe0000000-0xefffffff (ro,non-prefetchable)
  I/O Ports: 0xf000-0xf03f (rw)
  IRQ: 26 (2273976 events)
  I/O Ports: 0x3c0-0x3df (rw)
  Module Alias: "pci:v00008086d00000166sv00001462sd000010C0bc03sc00i00"
  Driver Info #0:
    Driver Status: i915 is active
    Driver Activation Cmd: "modprobe i915"
```

`Help -> System Information`

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.8.1-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Enlightenment
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.5.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 12.17" x 6.85"  (13.94" diag)
                                            30.9cm x 17.4cm  (35.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3854 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  272848 Mb
    Largest Free Hard Disk Block:  176951 Mb

Installed software:

Recent Failure Reports:

```

**Comment by liquex** [comment] 2015-06-27 08:53
I don't know @EPadronU means the same, but ever since the 26/06 update I've got audio skipping on Linux.

**Comment by chaserhkj** [comment] 2015-06-27 09:33
Same issue here.

My system info is described in #136

**Comment by DarkDefender** [comment] 2015-06-27 09:52
I also have problems that the audio crackles constantly after the update.

**Comment by LMG** [comment] 2015-06-27 10:00
Same issue here, Ubuntu 15.04. Can add info if needed.

**Comment by Turmfalke2** [comment] 2015-06-27 11:50
hi,
I also noticed sound issues today. It is some kind permanently buzzing in the background music and skipping in the hero lines.
I am using pure alsa, no pulse audio or such. Toggling the check box for high quality audio did nothing, even after restarting the client.

If you need any additional information please let me know what you need and I will provide it.

**Comment by gensss** [comment] 2015-06-27 13:14
i fixed this by going around libalsa resampling by giving dota full control over the sound card
by making a .soundrc containing

pcm.!default{
type hw
card 0
}
ctl.!default{
type hw
card 0
}


a look at /proc/asound/card0/pcm0p/sub0/hw_params shows following

access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 4096
buffer_size: 8192

my guess is that dota fills the period too late not giving speex (the default alsa resampler) enough time to resample before having to send it to the card

fwiw i think 3 periods of 1024 frames would be perfect
1024 frames of 16bit stereo gives a 4kB period, that is 1 default sized page of memory
and its ~22ms delay per period so thats not bad either

**Comment by chaserhkj** [comment] 2015-06-28 04:59
I fixed this issue by specifying the following lines in my `.asoundrc`

```
pcm.hwmix {
    type dmix
    ipc_key 1001
    slave {
        pcm cardhw
        rate 44100
        period_time 0
        period_size 1024
        buffer_size 4096
    }
}
```

It seems that this is now an issue with period sizes, but an issue with sampling rates.

Before I specify the `rate` directive in my `.asoundrc`, the following command yields:

`cat  /proc/asound/card1/pcm0p/sub0/hw_params`

```
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 1024
buffer_size: 4096
```
It shows that Reborn is operating on my sound card with a 48k sampling rate and it's creating noises in this state.

But after I changed my `.asoundrc` to specify a 44.1k sampling rate, ` cat  /proc/asound/card1/pcm0p/sub0/hw_params` gives

```
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 1024
buffer_size: 4096
```

And all audio is working well.

**Comment by presianbg** [comment] 2015-06-28 07:26
Same problem here in Fedora 22 x64 all up to date. None of the workarounds working here.

**Comment by gensss** [comment] 2015-06-28 09:00
@chaserhkj 

48kHz is the default libalsa sampling rate, dota sends 44.1kHz PCM
you changed it to 44.1kHz so there is no resampling happening

periods have to do with buffer timings, since they are periods in a ring buffer

**Comment by chaserhkj** [comment] 2015-06-28 09:06
So... it's still a resampling issue happening here then...

**Comment by ajrs** [comment] 2015-06-28 13:33
I don't want to make everything else sound crap just for dota...

**Comment by gensss** [comment] 2015-06-28 17:26
@chaserhkj

that's kind of my guess
but it could easily be something else so speculating here won't be of much help to devs

**Comment by sylware** [comment] 2015-06-28 21:06
Seem I have the same issue (no kludgeaudio on my system).
In the log, I get tons of ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
I get the same thing with dota 2 source 1, but snd_restart 1 in the console fixes it (linux reborn console does not work).

**Comment by sphexing** [comment] 2015-06-29 02:37
Since the 06/06, I got some crackling and skipping sounds.

System info:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2668 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,98" x 12,28"  (24,29" diag)
                                            53,3cm x 31,2cm  (61,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1200
    
Memory:
    RAM:  5958 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  100564 Mb
    Largest Free Hard Disk Block:  26669 Mb
    
Installed software:
    
Recent Failure Reports:
```

**Comment by davidw-valve** [comment] 2015-06-29 17:23
You can try increasing the value of the snd_mixahead convar to mitigate this.

We are working on a fix for the next update.

**Comment by gensss** [comment] 2015-06-29 19:12
snd_mixahead unfortunately does not help


for those in need of a quick fix, a full .asoundrc
(thx valve for making me play with the alsa programming language:)

pcm.ossmix {
    type dmix
    ipc_key 1024 # must be unique!
#   ipc_key_add_uid false   # let multiple users share
#   ipc_perm 0666           # IPC permissions for multi-user sharing (octal, default 0600)
    slave {
        pcm "hw:0,0"      # you cannot use a "plug" device here, darn.
        period_time 0
        period_size 1024 # must be power of 2
        buffer_size 4096  # dito. It
       #format "S32_LE"
       #periods 128 # dito.
       rate 44100 # with rate 8000 you *will* hear,
       # if ossmix is used :)
    }
    # bindings are cool. This says, that only the first
    # two channels are to be used by dmix, which is
    # enough for (most) oss apps and also lets 
    # multichannel chios work much faster:
    bindings {
        0 0 # from 0 => to 0
        1 1 # from 1 => to 1
    }
}
pcm.dsp0 {
    type plug
    slave.pcm "ossmix" # use our new PCM here
}
# mixer0 like above
ctl.mixer0 {
    type hw
    card 0
}

# You may want to make your new ossmix the default for alsa.
# If your alsa programs are complaining that they can't open
# your sound devices, try uncommenting this next line
pcm.default pcm.dsp0

most of the things here are not needed
as most of the audio played on my computer is 44.1kHz, i'l keep this
added benefit is it uses MMAP_INTERLEAVED instead of sockets, so yay

sry for lowering signal to noise ratio on this bug

**Comment by davidw-valve** [comment] 2015-07-01 00:01
Should be fixed in latest release.

**Comment by EPadronU** [comment] 2015-07-01 00:30
Well... The problem persist in my side...

**Comment by Turmfalke2** [comment] 2015-07-01 00:49
Yes, can confirm that issue still exists.

**Comment by davidw-valve** [comment] 2015-07-01 01:02
Are you sure you had the update when you still experienced this? What is your snd_mixahead set to?

**Comment by Turmfalke2** [comment] 2015-07-01 01:37
Yes, I am sure that I have update. I downloaded it and started reborn to test whether this bug got fixed.
] snd_mixahead
snd_mixahead = 0.100000

**Comment by EPadronU** [comment] 2015-07-01 02:23
Yeah, I'm pretty sure about the update. snd_mixahead == 0.05

**Comment by presianbg** [comment] 2015-07-01 04:47
latest update + snd_mixahead = 0.1 results in no sound problems here. (Fedora 22 x64, bumblebee, mesa 10.6.1 + nvidia-352).

**Comment by davidw-valve** [comment] 2015-07-01 06:24
@preslanbg: if you set snd_mixahead very low (0.001) do you still have no problems?

@Turmfalke2 / EPadronU: If you set snd_mixahead lower (0.001) does the problem get worse?

**Comment by presianbg** [comment] 2015-07-01 07:13
@davidw-valve: Even with snd_mixahead set to 0.001 there is no sound problems (at least in the HUD).

**Comment by Turmfalke2** [comment] 2015-07-01 07:24
@davidw-valve From what I can tell setting snd_mixahead to a lower value changes nothing. It is pretty bad to begin with, so it might be difficult to tell.
Just to summarize my situation:
I had no sound issues prior to the 26.6 update and I get no static noise if I tinker with .asoundrc:
pcm.!default{
type hw
card 0
}
ctl.!default{
type hw
card 0
}

**Comment by DarkDefender** [comment] 2015-07-01 09:02
I can confirm, the update didn't fix the sound issue for me either. Even with snd_mixahead set to 0.001.

**Comment by nixi-awoo** [comment] 2015-07-01 13:07
I can confirm this as well.

**Comment by sylware** [comment] 2015-07-01 14:37
the alsa sound issue is persisting on my system too.

**Comment by sinatosk** [comment] 2015-07-01 15:08
issue still exists with me

**Comment by EPadronU** [comment] 2015-07-01 15:42
Just in case: I don't use pulseaudio at all and my `asoundrc` is as follow:

```
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "plug:dmix";
}
pcm.!default {
  type plug;
  slave.pcm plugequal;
}
```

**Comment by davidw-valve** [comment] 2015-07-01 18:34
I have managed to reproduce the problem by removing pulseaudio from my system and using ALSA. Will work on a fix. Thank you for your patience.

In the meantime, the sound does work well if you use pulseaudio, though I understand that if you are not using it already it is probably your preference not to use it.

**Comment by davidw-valve** [comment] 2015-07-01 19:38
We have a fix for this. Please expect it to be resolved in the next update.

**Comment by EPadronU** [comment] 2015-07-01 20:58
Thanks a lot @davidw-valve. You're awesome!

**Comment by davidw-valve** [comment] 2015-07-02 23:12
This should be fixed in the latest update. If someone who was experiencing this issue can try it and let me know that would be appreciated.

**Comment by sinatosk** [comment] 2015-07-02 23:29
fixed for me

**Comment by Turmfalke2** [comment] 2015-07-03 00:00
thank you @davidw-valve, the patch fixed it for me.

**Comment by weirddan455** [comment] 2015-07-03 00:01
Fixed for me as well.

**Comment by sylware** [comment] 2015-07-03 00:02
:( Only partial for me.
I started to watch a live game, it was ok for a little while, then I got in the log the alsa underrun messages and the rainy audio.

**Comment by EPadronU** [comment] 2015-07-03 00:21
Fixed for me as well. Even though more testing is required

**Comment by davidw-valve** [comment] 2015-07-06 17:33
@sylware: Is this still occurring for you? What do you have snd_mixahead set to?

For anyone else who was experiencing this can you please try setting snd_mixahead to 0 and tell me if the issue is still resolved? The aim of the audio design is to be able to set snd_mixahead super low and enjoy very low latency audio.

**Comment by EPadronU** [comment] 2015-07-06 17:40
Hi, @davidw-valve. I just set `snd_mixahead` to 0 as you requested and everything is OK. Cheers.

**Comment by DarkDefender** [comment] 2015-07-06 23:43
@davidw-valve same as @EPadronU, the sound still seems to be fine with snd_mixahead set to 0

**Comment by sylware** [comment] 2015-07-07 16:00
Good news: I'm unable to reproduce the sound issue, with snd_mixahead of 0.1 or 0.
I got only one alsa message underrun, but a benign standalone one since the sound stayed perfect.

(could you backport the fix in dota2 source 1/portal 2/portal2 MEL/CS GO/Team Fortress 2? Thanks a million).

**Comment by davidw-valve** [comment] 2015-07-09 19:34
@sylware: what issue exactly do you get in the source 1 games? Dota2 Reborn uses a fairly different audio system to Source 1 games so simply porting back this fix isn't easy. However, if you can file a bug report or point me to an existing one in the appropriate repositories for these games I would be happy to look into it.

**Closed as completed by davidw-valve** 2015-07-09 19:34 UTC
Labels: reviewed

**Comment by sylware** [comment] 2015-07-10 12:43
On Thu, Jul 09, 2015 at 12:34:41PM -0700, davidw-valve wrote:

> @sylware: what issue exactly do you get in the source 1 games? Dota2 Reborn
> uses a fairly different audio system to Source 1 games so simply porting back
> this fix isn't easy. However, if you can file a bug report or point me to an
> existing one in the appropriate repositories for these games I would be happy
> to look into it.

I get randomly, but nearly surely, an alsa pcm underrun then rainy audio in
dota2 source 1. I fix this with the "snd_restart 1" console command. Since I'm
going to switch slowly to reborn client, don't bother, and I don't really
recall getting this sound issue in portal 2/CS GO/TF2 (I get mainly annoying
graphical glitches).
If I get the sound bug with other source 1 games, I'll open an issue and refer
to this one.
