### ISSUE TITLE
Game crash at "Watch" tab

### ISSUE THREAD

**Issue by Leproide** [ValveSoftware/Dota-2#563] opened 2015-10-13 18:10 UTC
Game crash at "Watch" tab

OS: Fedora 22
WM: GNOME Shell
Kernel: x86_64 Linux 4.1.10-200.fc22.x86_64
CPU: Intel Core i7-2600K CPU @ 3.8GHz
GPU: AMD/ATI Barts XT [Radeon HD 6870]

Console log when the client starts:
http://leprechaun.tk/zerobin/?8448452ad4484a3a#lfHx7Rw73bY+A8jb47EWfW+u1dpuMgxJmmc303W9MI4=

lsusb (only pertinent):
Logitech, Inc. G930
ROCCAT Kone+ Mouse
Genesys Logic, Inc. Logitech G110 Hub
Logitech, Inc. Gaming Keyboard G110 G-keys
Logitech, Inc. Gaming Keyboard G110

**Comment by gdrewb-valve** [comment] 2015-10-13 18:44
Duplicate of #561.

**Closed as completed by gdrewb-valve** 2015-10-13 18:44 UTC
Labels: duplicate, reviewed
