### ISSUE TITLE
[Linux] Graphic Issue AMD RV730 Mesa 11.1.0-devel git-443d3bf

### ISSUE THREAD

**Issue by l3th3x** [ValveSoftware/Dota-2#537] opened 2015-10-06 22:51 UTC
Hi

I have some problems with the graphics. Please help to fix

Operating System Version:

```
Linux Mint 17.2 Rafaela (64 bit)
Kernel Name:  Linux
Kernel Version:  3.19.0-30-generic
X Server Vendor:  The X.Org Foundation
X Server Release:  11501000
X Window Manager:  Mutter (Muffin)
Steam Runtime Version:  steam-runtime-release_2015-06-12
```

Video Card:

```
Driver:  X.Org Gallium 0.4 on AMD RV730 (DRM 2.40.0, LLVM 3.6.2)
Driver Version:  3.0 Mesa 11.1.0-devel (git-443d3bf 2015-10-03 trusty-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9480
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 16,65" x 9,37"  (19,09" diag) 42,3cm x 23,8cm  (48,5cm diag)
Primary VRAM Not Detected
```

Sample Screenshots:

![ekran goruntusu - 2015-10-07 02 38 55](https://cloud.githubusercontent.com/assets/15005360/10325714/952abfc2-6c9c-11e5-9662-e43c239f6b4e.png)
![ekran goruntusu - 2015-10-07 01 47 33](https://cloud.githubusercontent.com/assets/15005360/10324866/c8bfce7e-6c95-11e5-82b6-4a85c16d2fbd.png)
![ekran goruntusu - 2015-10-07 02 11 03](https://cloud.githubusercontent.com/assets/15005360/10325286/c6de648c-6c98-11e5-919a-b4efe6b48f0e.png)

**Comment by danginsburg** [comment] 2015-10-06 23:58
This looks like it is most likely a regression on 11.1.0-devel.  Can you try using an earlier version of mesa?  mesa 10.5.9 is known good on AMD HD 7950.

**Comment by l3th3x** [comment] 2015-10-07 00:58
How can I do this? Sorry, I'm newbie on Linux

**Comment by l3th3x** [comment] 2015-10-07 11:20
Thanks for the reply but Linux Mint 17.x based on Ubuntu 14.04. Mesa 10.5.9 does not have in the store. This version available at Ubuntu 15.04. Is there another way to the solution?

**Comment by Tele42** [comment] 2015-10-07 15:12
@l3th3x This issue should also be reported to the Mesa devs if it has not been already.

**Comment by danginsburg** [comment] 2015-10-15 20:25
I'm going to close this out under the assumption it was a bug in 11.1.0-devel git-443d3bf unless I hear otherwise in which case I can reopen it.

@l3th3x I'm not sure the best way to install mesa on mint.  On Ubuntu there is xorg-edgers and of course you can always build from source too.

**Closed as completed by danginsburg** 2015-10-15 20:25 UTC
Labels: reviewed
