### ISSUE TITLE
[OSX] FPS drops when staying at fountain

### ISSUE THREAD

**Issue by NekR** [ValveSoftware/Dota-2#640] opened 2015-11-12 10:48 UTC
OS X El Capitan, Macbook Mid 2015, model MJLQ2LL/A

VSync is turned on. All the game is 59-60 fps, but when I am staying at a fountain it drops to 30 fps, when I leave it, fps is back again to 60. Noticed this on Radiant side, not sure about Dire yet.

**Comment by gdrewb-valve** [comment] 2015-11-12 18:30
I believe this is already reported in an existing issue, but only in comments.

**Comment by danginsburg** [comment] 2015-11-13 12:53
Assuming you have the Intel Iris Pro GPU, this is a duplicate of #538.  We are aware of performance issues on Intel 5000/6100/Iris/Iris Pro on OSX.  We have a Radar filed with Apple which was opened on September 24, 2015.

**Closed as completed** 2015-11-13 12:54 UTC
Labels: duplicate, reviewed

**Comment by NekR** [comment] 2015-11-13 15:44
@danginsburg I understand, thanks for the info!

Btw, performance of my Macbook is great, it's 60fps with VSync and 120fps without it. I didn't saw any performance issue except of fountain problem, but if you say that it's general probably with Intel cards on Mac then okay.

**Comment by zkzipoo** [comment] 2015-11-20 02:30
@NekR hey Paul, which system version are you currently using?

**Comment by Tele42** [comment] 2015-11-20 02:38
"El Capitan" is 10.11

**Comment by zkzipoo** [comment] 2015-11-20 02:41
any specific parameters for the startup console? I got a late 2014 model which perform much more worse. It can barely hit 30 fps just with low to medium settings

**Comment by NekR** [comment] 2015-11-20 12:59
@zkzipoo I do not use any specific params. I have had 60fps even on high quality (all settings on), but it overheats my macbook very fast, so I just play on low quality.
