### ISSUE TITLE
Hero screen is freaking out

### ISSUE THREAD

**Issue by MeioJo** [ValveSoftware/Dota-2#689] opened 2015-12-18 15:50 UTC
Hero screen is scrolling thru heros non-stop both in the hero screen and the customize hero (single hero) screen..

I can't look at any heros...

perma next on the heros and it looks random too...

**Comment by MeioJo** [comment] 2015-12-18 17:10
https://www.youtube.com/watch?v=C6NVSckEGnk

**Comment by Tele42** [comment] 2015-12-18 19:22
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information, in particular, any controllers that might be connected. This looks like a game controller is connected and has an uncalibrated analog stick.

**Comment by MeioJo** [comment] 2015-12-18 19:40
Ya sorry .. home for the holidays so it's my Moms computer ;)

os x 10.9.5.

3.2g i5

8gb ram ddr3

**Comment by MeioJo** [comment] 2015-12-18 19:53
Oh ya I have a G13 but the analog stick is set to f1, y, g, alt

**Comment by MeioJo** [comment] 2015-12-18 19:57
The Logitech G13 soft/version is 8.60.313

**Comment by MeioJo** [comment] 2015-12-18 19:59
Unplugged the g13 > start DotA and it still is happening...

**Comment by vadi2** [comment] 2015-12-18 22:20
Switch to the grid mode, allows you to pick a hero. I get it every now and then as well playing on Ubuntu with mouse and keyboard.

**Comment by MeioJo** [comment] 2015-12-19 01:02
@ vadi2  Did you watch the video?

Already in grid mode.. or am i missing something?

**Comment by gdrewb-valve** [comment] 2015-12-19 03:38
Seems like a duplicate of #174, did you see that one?  It also involves bad input with a G13.

**Comment by MeioJo** [comment] 2015-12-19 12:39
Yes I would have to say it is a match :)

however unplugging the G13 and then starting Reborn does not stop the issue from happening.

**Comment by gdrewb-valve** [comment] 2015-12-19 14:36
Closing in favor of #174.

**Closed as completed by gdrewb-valve** 2015-12-19 14:36 UTC
Labels: reviewed
