### ISSUE TITLE
[macOS] FPS Drop to 10 randomly

### ISSUE THREAD

**Issue by wahmbulance** [ValveSoftware/Dota-2#1138] opened 2016-12-23 09:25 UTC
I have an iMac 5k 27 inch late 2015 with i5 + amd r9 390x 16 gb ddr3 ram. 

pre 7.0 i could at 80-100 fps. now i run around 60-80. however. sometimes the fps will drop to 10-13. in order for me to fix it. i have to command tab out (desktop friendly mode) then re enter game. it sorta fixes it. dota also runs above 95% cpu usage. and also i think the "show cast range finder" option may have something to do with this bug. please fix dota for us Mr Developer. thanks for reading this

**Comment by kisak-valve** [comment] 2016-12-23 13:20
Hello @wahmbulance, the performance regression since the 7.00 update is being tracked at #1101.

**Comment by gdrewb-valve** [comment] 2016-12-23 17:45
Closing in favor of 1101.

**Closed as completed by gdrewb-valve** 2016-12-23 17:45 UTC
