### ISSUE TITLE
[osx] screenshots taken on "desktop-friendly fullscreen" are messed up

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#523] opened 2015-10-03 21:13 UTC
it might have something to do with game resolution being lower than actual monitor resolution (1280x800 vs 1920x1200)

![2015-10-03_00001](https://cloud.githubusercontent.com/assets/9968388/10265148/281e18ea-6a24-11e5-9b2f-5d3525c8093d.jpg)
![2015-10-03_00002](https://cloud.githubusercontent.com/assets/9968388/10265149/282031e8-6a24-11e5-9d27-ef1f58317fa1.jpg)
![2015-10-03_00003](https://cloud.githubusercontent.com/assets/9968388/10265150/28296894-6a24-11e5-87e1-a45fd4dc095f.jpg)

in comparison, one of a "exclusive fullscreen":
![2015-10-03_00004](https://cloud.githubusercontent.com/assets/9968388/10265152/4895016a-6a24-11e5-9357-63ded1ae06ec.jpg)

**Comment by danginsburg** [comment] 2015-10-05 12:35
Can you please post Steam -> Help -> System Information to help us isolate the issue here?

**Comment by danginsburg** [comment] 2015-10-05 14:22
Actually, I'm all set, I have this repro'd.

**Comment by danginsburg** [comment] 2015-10-05 20:09
This has been fixed and will be in a future release of Steam.  It was caused by the steam overlay not disabling scissor test.  I'm going to close this out here since it is not actually a Dota 2 issue.

**Closed as completed by danginsburg** 2015-10-05 20:09 UTC
Labels: reviewed
