### ISSUE TITLE
Dota 2 doesn't work on NTFS anymore after 7.00

### ISSUE THREAD

**Issue by sethdusek** [ValveSoftware/Dota-2#1136] opened 2016-12-19 21:32 UTC
So, whenever you try and update dota to the 7.00 version, Steam will tell you you have corrupt update files, and restart the download. It is happening to a lot of people including me, and it apparently happens if you're storing dota on an NTFS filesystem.

[Steam discussion](http://steamcommunity.com/app/570/discussions/0/1843493219432308676)

**Comment by kisak-valve** [comment] 2016-12-19 22:08
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4752.

**Closed as completed by kisak-valve** 2016-12-19 22:08 UTC
