### ISSUE TITLE
Wrong dowload size and play button not working

### ISSUE THREAD

**Issue by wubwoofwolf** [ValveSoftware/Dota-2#1528] opened 2018-12-04 13:22 UTC
#### Your system information

* System information: 
Mac osX 10.9.5 (Mavericks)
Intel Core i7 4 GHz
16 GB 2400 MHz DDR3
Nvidia GeForce GT 640 2048 MB
  
 Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
When I try to download the game the space required is about 15 GB but then it only dowloads 9 GB. Then, as mentioned in issues #1518 and #1473 the play button greys out, can´t watch any game, and the game can´t find pings. Tried reinstalling both steam and dota, opting in and out of the beta, etc.
![captura de pantalla 2018-12-04 a la s 10 04 49](https://user-images.githubusercontent.com/45549431/49444446-f8c71680-f7ad-11e8-9e96-176148d12a41.png)

 
#### Steps for reproducing this issue:

1. Open Dota 
2. Click the "Find Match" button
3. Button is greyed out

**Comment by kisak-valve** [comment] 2018-12-04 13:42
Hello @wubwoofwolf, the space required for steam to install a game may be a bit larger than the download size because some extra space is temporarily used when copying the newly downloaded content to the Steam Library. This is not an indication that there is missing content from the game.

Closing as a duplicate of #1518.

**Closed as completed by kisak-valve** 2018-12-04 13:42 UTC

**Comment by wubwoofwolf** [comment] 2018-12-04 14:39
But how come when I installed it on another computer it did download all the 15 Gb? I just wanna play dota  :(
