### ISSUE TITLE
Mac: Crashes while watching replays/spectating in game.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#506] opened 2015-09-29 21:36 UTC
Game just crashes randomly when spectating/watching replays, this is the error I get https://i.imgur.com/XZELcV7.png after which I have to terminate the application. This isn't new, happened in the last few patches as well I just didn't get the error, either I was too slow so I couldn't clip it or it didn't show . iMac OSX , late 2012.

**Comment by Tele42** [comment] 2015-09-29 22:05
Possibly related to #490.

**Comment by danginsburg** [comment] 2015-09-29 23:39
This is a duplicate of #490.  Could you get us a match ID where this occurred?  We are still working to repro this.

**Comment by Vuccappella** [comment] 2015-09-30 08:23
Sure, Match 1830314782

**Comment by danginsburg** [comment] 2015-09-30 13:03
Thanks, attempting to repro now on the replay.  We are definitely looking into this and know it is an issue.

**Comment by gdrewb-valve** [comment] 2015-10-12 18:57
This isn't platform-specific and won't be tracked here, but the larger team believes this has been fixed.

**Closed as completed by gdrewb-valve** 2015-10-12 18:57 UTC
Labels: duplicate, reviewed
