### ISSUE TITLE
Dota 2 crashes for some custom maps since today.

### ISSUE THREAD

**Issue by migrome** [ValveSoftware/Dota-2#1158] opened 2017-01-21 11:11 UTC
Some custom maps crash at random times. Usually it crashes pretty soon (couple of minutes after game starts, or even sooner). It worked fine until today.

1. Some custom maps work well (Epic Boss Fight, Vampirism). Some custom maps crash (Guarding Athena, Zhu Xian). Regular dota map doesn't crash.
2. The only thing that changed between yesterday and today that I can think of is the most recent Dota update (UI changes mostly, as written in changelog).
3. It seems it works for majority of people. So the thing that I'm on Linux might be relevant thing. (Archlinux, "Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux"). It crashes both for steam-runtime (regular one) and [steam-native](https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/).

```
>>> Adding process 11940 for game ID 570
>>> Adding process 11942 for game ID 570
Playing WAVE '/home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/sounds/ui/stingers/match_ready_no_focus.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
>>> Adding process 13274 for game ID 570
crash_20170121192712_1.dmp[13291]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170121192712_1.dmp
>>> Adding process 13280 for game ID 570
crash_20170121192712_1.dmp[13291]: Finished uploading minidump (out-of-process): success = yes
crash_20170121192712_1.dmp[13291]: response: Discarded=1
crash_20170121192712_1.dmp[13291]: file ''/tmp/dumps/crash_20170121192712_1.dmp'', upload yes: ''Discarded=1''
pid 13291 != 13280, skipping destruction (fork without exec?)
/home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104: 11696 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 11696 
No cached sticky mapping in ActivateActionSet.
```

**Comment by kisak-valve** [comment] 2017-01-21 13:22
Hello @migrome, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Additionally, please include any CrashIDs or minidumps related to this issue. Minidumps can be compressed and drag-and-dropped into the comment section.

**Comment by migrome** [comment] 2017-01-21 16:01
@kisak-valve , 

1. [System information.](https://gist.github.com/migrome/70e87f22ce751b771db0073e4ec03c1c)
2. CrashID=**bp-211aaa37-f8ba-4e11-9733-83e122170121** ([crash_20170122012555_1.dmp.gz](https://github.com/ValveSoftware/Dota-2/files/721262/crash_20170122012555_1.dmp.gz)).

**Comment by kisak-valve** [comment] 2017-01-21 18:18
For reference, the attached minidump is a SIGSEGV in libclient.so (in Dota 2).

**Comment by gdrewb-valve** [comment] 2017-01-23 20:53
We've found the cause of this crash and a fix will be in the next update.

**Comment by gdrewb-valve** [comment] 2017-01-24 02:58
The Jan. 23rd update should have fixed this, are you still seeing problems?

**Comment by migrome** [comment] 2017-01-24 08:58
No, works fine for me. Thank you.

**Comment by kisak-valve** [comment] 2017-01-24 13:40
Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2017-01-24 13:40 UTC
Labels: reviewed
