### ISSUE TITLE
[Linux] Ingame-UI/Hero-Pick-UI almost not rendered - nVidia

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#48] opened 2015-06-23 17:11 UTC
Ubuntu 14.04LTS (standard, with Unity)
`3.15.0-6-generic #11-Ubuntu SMP Thu Jun 12 00:40:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
GTX760 4GiB (MSI)
proprietary driver 331.113-0ubuntu0.0.4

fullscreen or borderless

![hero_pick](https://cloud.githubusercontent.com/assets/5393579/8312119/35f30e60-19db-11e5-861e-67bf4a3b5fbe.png)

**update:**
Newer driver changes things. What works correctly:
Ubuntu 15.04
nVidia 340.76-0ubuntu2
`3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by abobier** [comment] 2015-06-23 17:36
Same problem with proprietary driver 331.113 BUT not with proprietary driver 352.21 (from xorg-edgers PPA).

System: Ubuntu 14.04 LTS 64bits + NVIDIA GeForce GTX 650

**Comment by ChipmunkV** [comment] 2015-06-23 20:33
340.76-0ubuntu2 works okay.

**Comment by vadi2** [comment] 2015-06-24 08:17
Confirmed 352.21 works better - still has bugs though:

![screenshot from 2015-06-24 18 08 38](https://cloud.githubusercontent.com/assets/110988/8325465/509f03e6-1a9d-11e5-9e86-6074af3bfc94.png)

![screenshot from 2015-06-24 18 08 00](https://cloud.githubusercontent.com/assets/110988/8325466/53304e3a-1a9d-11e5-8eb5-c3d714a02755.png)

**Comment by dhiru1602** [comment] 2015-06-24 08:57
Got the same issue at my end.

Arch Linux (x86_64) with Nvidia 340.76-9. I can't upgrade to any newer nvidia releases since my 9600GT GPU is only supported by 340xx legacy driver.

![11649369_10206449910582721_56741886_o](https://cloud.githubusercontent.com/assets/1326273/8326183/636c9a24-1a70-11e5-9cfc-ca36199ecdd4.jpg)

**Comment by hrzhu** [comment] 2015-06-24 09:47
I have the same problem. Xubuntu 14.04 GT 630 Nvidia-331 driver
![2015-06-24_00001](https://cloud.githubusercontent.com/assets/2360542/8327145/be37dc20-1a98-11e5-93fd-9f7021dbdb8e.jpg)

**Comment by hrzhu** [comment] 2015-06-24 11:01
Upgrading to nvidia-352 solves the problem.

**Comment by mtbrandao** [comment] 2015-07-03 01:15
Will Dota 2 Reborn final version support nvidia 331?
This is the current version of the driver on latest Ubuntu LTS (Trusty).
All the updates comes from unofficial sources.

**Comment by danginsburg** [comment] 2015-07-03 14:00
You can workaround the problem on with NVIDIA 331 drivers by adding the following to your Launch Options:

```
-gl_disable_buffer_storage +gl_enable_vertex_attrib_binding 0
```

I'll look into adding some autodetect code to turn these on so that it at least works on 331, but I highly recommend latest NVIDIA drivers because these flags are just working around bugs in the NVIDIA 331 driver.

**Comment by danginsburg** [comment] 2015-07-03 14:33
I checked in a fix that will auto detect NVIDIA 331 and disable GL_ARB_buffer_storage and GL_ARB_vertex_attrib_binding use since it is broken in this driver.  Fix will be in the next release.  For now, use the command-line options I mentioned to forcibly disable the use of those extensions which have bugs in the NVIDIA 331 driver.

**Closed as completed by danginsburg** 2015-07-03 14:33 UTC
Labels: reviewed, drivers

**Comment by mtbrandao** [comment] 2015-07-03 14:46
WOW, nice.
The workaround works perfect!
Thanks
