### ISSUE TITLE
[OSX] Command+Tab doesn't work

### ISSUE THREAD

**Issue by gluttonyGit** [ValveSoftware/Dota-2#632] opened 2015-11-04 12:30 UTC
I am unable to restore focus on desktop space using command+tab. But i can do this using cmd+H.
OS X 10.11.1
Intel HD Graphics 4000
Current on 4.11.2015

**Comment by gdrewb-valve** [comment] 2015-11-04 16:09
Duplicate of #546, possibly still active?

**Comment by Tele42** [comment] 2015-11-04 16:53
@gdrewb-valve, my understanding was that this is the correct behavior. If an issue report is closed and there is no response on the existing issue report, then open a new one.

**Comment by gdrewb-valve** [comment] 2015-11-04 16:58
Command+Tab doesn't work with exclusive fullscreen by design, but with desktop-friendly fullscreen it should work.  #546 fixed a problem with SDL that was preventing things from working properly so if there are still users with issues it might need to be reopened.

**Comment by Tele42** [comment] 2015-11-04 17:08
Sorry for the ambiguous reference, I was referring to the user's behavior, not the game's behavior.

**Comment by danginsburg** [comment] 2015-11-04 17:34
@gluttonyGit Can you clarify what mode you are in?  Is it Desktop Friendly Fullscreen or Exclusive Fullscreen?  It will not work in Exclusive Fullscreen by design.

**Comment by gluttonyGit** [comment] 2015-11-04 17:51
@danginsburg,  I used Exclusive Fullscreen. Sorry for invalid ticket.

**Comment by danginsburg** [comment] 2015-11-04 17:54
No problem, closing.

**Closed as completed by danginsburg** 2015-11-04 17:54 UTC
Labels: reviewed
