### ISSUE TITLE
[Linux] Dota2 Reborn start on the secondary screen

### ISSUE THREAD

**Issue by grasdaggel** [ValveSoftware/Dota-2#115] opened 2015-06-26 15:51 UTC
Hi guys,

Dota2 Reborn starts on the secondary screen, not on the primary one. This is unusual, because Dota2 always started on the first screen attached to the videocard.

It seems like there is no fix, switching to Windowed Mode and place it on the first screen, then selecting "Fullscreen" again does not fix the bug.

Using: Linux 14.04, Nvidia 352 drivers.

**Comment by gdrewb-valve** [comment] 2015-06-26 16:04
Duplicate of #13.

**Closed as completed by gdrewb-valve** 2015-06-26 16:04 UTC
Labels: duplicate, reviewed
