### ISSUE TITLE
[OSX] display does not update after actions

### ISSUE THREAD

**Issue by martenson** [ValveSoftware/Dota-2#639] opened 2015-11-12 03:32 UTC
Hello guys,

Since 3 days ago I experience this behavior that prevents me from playing. 

After starting the client I hear sound that I have entered the homepage but I do not see it. I am stuck at the loading logo instead. If I cmd-tab out and in again the view will update and I see the menus and everything. However whatever I click on I hear the sound of the action but do not see the effect of it unless I double cmd-tab again. This repeats multiple times.

It will eventually go away after multiple cmd-tab combos and I can navigate freely for few dozens of seconds but then the image will freeze again and I am back to cmd-tabing. I tried it in an empty game and it will also happen there.

Had no trouble before. I am using the lowest graphics settings.

Processor Information:
    Model:  MacBookAir6,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.1 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 5000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xa26
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.39" x 13.15"  (26.81" diag)
                                        59.4cm x 33.4cm  (68.1cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  8192 Mb

**Comment by danginsburg** [comment] 2015-11-13 16:11
I tried running this on a very similar Macbook Air 6,2 and have not been able to reproduce the problem (specs below).  The main differences seem to be that I have less RAM (4GB vs 8GB) and you are running at a higher resolution (1920x1080 whereas I am at 1440x900).  Does it help if you go to Desktop Friendly 1440x900?  I'm not sure what could be going on since I can't reproduce it.

Processor Information:
    Model:  MacBookAir6,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.1 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 5000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0xa26
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 11.22" x 7.01"  (13.23" diag)
                                        28.5cm x 17.8cm  (33.6cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  4096 Mb

**Comment by gdrewb-valve** [comment] 2016-02-25 22:57
Has this changed at all since November?

**Comment by gdrewb-valve** [comment] 2016-02-29 22:24
Closing pending more information.

**Closed as completed by gdrewb-valve** 2016-02-29 22:24 UTC
Labels: reviewed

**Comment by martenson** [comment] 2016-04-20 17:30
@gdrewb-valve It changed only for the worst; now it starts to happen even when the application is open. I have to minimize it multiple times to get the responsiveness back. So I basically stopped playing.
