### ISSUE TITLE
[OSX] Game will blackout/darken when the game is paused or when during death

### ISSUE THREAD

**Issue by adriantyw** [ValveSoftware/Dota-2#445] opened 2015-09-15 02:57 UTC
![screen shot 2015-09-14 at 5 20 14 pm](https://cloud.githubusercontent.com/assets/14286360/9866672/d5f29644-5b97-11e5-9fc6-afcf87009c3f.png)

Whenever i am dead or the game is paused the game visuals will be darken/blackout. As shown in the picture. 

Here is my specs
https://gist.github.com/adriantyw/f4c0f5c67212cabcd658

**Comment by danginsburg** [comment] 2015-09-15 11:52
Thanks, this is the same issue as #309.  You can workaround it for now by disabling anti-aliasing.  As I mentioned in the bug there, the problem is understood and I am working on a fix.  I'm going to close this as a duplicate.

**Closed as completed by danginsburg** 2015-09-15 11:52 UTC
Labels: duplicate, reviewed
