### ISSUE TITLE
[OSX] Getting low fps using desktop-friendly mode and even in Exclusive Fullscreen when plugged in external monitor

### ISSUE THREAD

**Issue by leonnardo** [ValveSoftware/Dota-2#762] opened 2016-02-16 23:55 UTC
I'm having some issues.. When I play with no external monitor and with exclusive fullscreen, i got 60fps and eventually 40fps in tfs..

But, using an external monitor, fps drops to 20 or less in any situation.

Using Macbook Pro Retina mid 2013, Geforce 650M.

**Comment by danginsburg** [comment] 2016-02-17 13:45
Duplicate of #662.

**Comment by danginsburg** [comment] 2016-02-17 14:55
Can you please provide some more details here?  First, post Steam -> Help -> System Information so I can see your full system config.  Then, can you describe your external monitor resolution as well as how you setup for an external display (i.e., mirroring, separate).  I am trying this here on a MBPr GT650M Mid 2012 OS X 10.11.3 with a 1920x1080 external monitor and I am unable to repro any fps  drop at all when the external display is hooked up.

**Comment by gdrewb-valve** [comment] 2016-12-13 21:35
Closing duplicate, plus #662 looks like a system issue.

**Closed as completed by gdrewb-valve** 2016-12-13 21:35 UTC
Labels: duplicate, reviewed
