### ISSUE TITLE
Minimap while choosing hero bug

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#304] opened 2015-08-10 16:31 UTC
Check video from 22 sec.

In "old" dota 2 there weren't this bug. Here i'm trying to tell teammates where i will stay in game, but here can be marked only "bot" forest, and it working very strange. On video i'm trying press on each cm on map. Don't know why it is still not reported, i think it is not OpenGL specific.

https://youtu.be/3NlWSt9k86Q?t=22

**Comment by gdrewb-valve** [comment] 2015-08-10 18:47
This is a duplicate of #300, isn't it?

**Comment by Pharmasolin** [comment] 2015-08-10 20:03
yes, closing

**Closed as completed** 2015-08-10 20:04 UTC
Labels: reviewed
