### ISSUE TITLE
[macos 10.14.3] Mouse won't respond

### ISSUE THREAD

**Issue by zoujyjs** [ValveSoftware/Dota-2#1564] opened 2019-02-08 14:45 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/zoujyjs/b42bf2578545afcee662fd33c76e57bf
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes] 
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
- click is hardly responsible, usually you need click for several times.
- mouse hovering will not highlighting the buttons.
- mouse will not fix inside the window when playing at window mode, and you will lose focus easily when click outside the window.

#### Steps for reproducing this issue:

1. upgrade to macos 10.13.4
2. start the client
3. try click any button

**Comment by kisak-valve** [comment] 2019-02-08 14:53
Possible duplicate of #1219.

**Comment by zoujyjs** [comment] 2019-02-08 14:59
> Possible duplicate of #1219.

Yes, seems like the same issue. Last for so many years. Any effective workaround?
BTW, by switching graphic APIs to GL or Vulkan doesn't change anything.

**Comment by kisak-valve** [comment] 2019-02-08 15:09
Thanks for confirming, I don't have any info on this issue. Closing in favor of the existing issue report.

**Closed as completed by kisak-valve** 2019-02-08 15:09 UTC
Labels: reviewed

**Comment by zoujyjs** [comment] 2019-02-08 15:28
Problem gone after several reboots.
