### ISSUE TITLE
[OSX] Steamoverlay FPS Drop

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#508] opened 2015-09-30 20:07 UTC
Previously it did not occur, even with 10.11 on board.

**Comment by danginsburg** [comment] 2015-10-02 16:59
Please post Steam -> Help -> System Information and provide more details on this bug.

**Comment by gxgani** [comment] 2015-10-02 17:14
Macbook Pro 13 2012
Intel i5 / HD4000
OSX 10.1@

**Comment by danginsburg** [comment] 2015-10-12 18:57
Can you please provide more information here.  You say you are running OS X 10.1@, did you mean OS X 10.11?  Do you have System Integrity Protection (SIP) disabled?  Exactly what FPS drop are you seeing and where are you in game?  We need more info to address this bug.

**Comment by gxgani** [comment] 2015-10-12 19:53
Yes, I am running 10.11 with SIP **partially** disabled, @ was a typo.
I recorded the whole experience here: https://cobalt60.xyz/shared/Screen-Recording-2015-10-13-01-19-52.mp4 

Video might not be suffice enough to prove that the stuttering is real bad sometimes.

**Comment by danginsburg** [comment] 2015-10-12 20:21
Thanks for the video.  It isn't clear to me though what the issue is from watching it.  The framerate counter disappears when you bring up the overlay so it was hard to tell.  I tried running on my Macbook Pro 2012 with HD 4000 and the perf seemed reasonable.  I'm going to close this, if you find a more reproducible instance of slowdown that looks like a bug post it here.

**Closed as completed by danginsburg** 2015-10-12 20:21 UTC
Labels: reviewed
