### ISSUE TITLE
Mac Book issue.

### ISSUE THREAD

**Issue by jayzonsy** [ValveSoftware/Dota-2#2444] opened 2023-08-31 16:06 UTC
Game hangs when I try to purchase new cache items. 

Reproduce.

Click view treasure on menu
Valve store launches
Click authorize 
Hangs

**Comment by danginsburg** [comment] 2023-09-01 20:47
Closing as duplicate of #2449.  The latest Dota 2 update has a fix for this, please try again.

**Closed as completed by danginsburg** 2023-09-01 20:47 UTC
