### ISSUE TITLE
Hero guides fail to load and Dota Workshop Content loops in Steam Downloads

### ISSUE THREAD

**Issue by epssy** [ValveSoftware/Dota-2#1997] opened 2021-11-28 04:45 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a gist: [here](https://gist.github.com/epssy/8c4b00d4555d3623cc6d339bd4a2b18a)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When selecting a guide for a hero the guide fails to load in the game, the interface just does nothing.  Switching back to the default or Dota Plus guides works fine.  In the background Steam attempts to download the Workshop Content for the guide and fails, triggering a reschedule for five minutes time.  While the game is running, depending on your settings, it can decide to just retry infinitely instead of scheduling this can pin a single CPU core to 100% usage.  

This has been occurring since early this year.  Prior to that it worked fine.  

#### Steps for reproducing this issue:

1. Run Dota2
2. Select a hero guide on any screen it is offered

This will result in the behaviour described above if one of the following is true.  

- Using `ecryptfs` for your home directory or `.steam` folder
- Storing your Steam Library on any other mount than `/tmp`
- Using `tmpfs` for your system `/tmp` directory

#### Root cause and workarounds

This is occurring as Dota2 or Steam is attempting to do a `rename()` across volumes into the `workshop` folder after downloading the hero guide Workshop Content to `/tmp`.  This cross volume operation is not permitted by this call and fails with a `EXDEV (Invalid cross-device link)`.  

More in-depth details, as well as a post with workaround instructions, is available [in this issue thread](https://github.com/ValveSoftware/steam-for-linux/issues/7780).

**Comment by kisak-valve** [comment] 2021-11-28 13:38
Hello @epssy, downloading of workshop content is managed by Steam, and not directly by the Dota 2 client. Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/7780.

**Closed as completed by kisak-valve** 2021-11-28 13:38 UTC
