### ISSUE TITLE
[Linux]Fcitx + Plasma 5 breaks hero selection and in-game typing in Dota 2

### ISSUE THREAD

**Issue by MinervaW1993** [ValveSoftware/Dota-2#1038] opened 2016-10-07 21:38 UTC
I found that Fcitx is working now in Dota2 Client. I can activate the input window by Ctrl+Space while in game. However, when playing game 

1) In hero selection I cannot receive message from teammates or send out any message. I can type message in the input box but after I press enter, nothing happens.

2)I cannot receive the typed message from teammates nor I can type any message. After pressing enter the input box flashes then vanishes without any teammates' typed message. However, messages like "xxx is missing" "Need xxx gold for xxx item" are fine. Same as when watching game play.

After shutting down Fcitx, all problems are gone. This does not happen before (and I cannot activate Fcitx in Dota 2 Client at that time).

Occurs in both Steam stable and beta. Cannot solve the problem by reinstalling everything.

System specs:
(Arch Linux, Plasma 5.8)

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3000 Mhz
    32 logical processors
    16 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.0-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX TITAN/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 370.28
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1005
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                        53.1cm x 29.9cm  (60.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 6144 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: 

Memory:
    RAM:  24070 Mb

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  1853474 Mb
    Largest Free Hard Disk Block:  1439355 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by slouken** [comment] 2016-10-08 18:31
Try setting XMODIFIERS=@im=none
I'm not sure whether you'll actually get IME support if you do that, you may need a newer SDL built with fcitx support.

**Comment by MinervaW1993** [comment] 2016-10-08 18:50
Setting XMODIFIERS=@im=none fixes the problem and the input method is disabled in Dota 2. I am wondering why when setting XMODIFIERS=@im=fcitx will enable input method in the Dota 2 client even if SDL is not built with fcitx support...

**Comment by slouken** [comment] 2016-10-08 19:08
Because SDL does support the general IM API, which fcitx implements, but with the side effects you're seeing.

**Comment by timxx** [comment] 2016-10-12 13:22
@MinervaW1993 You can disable the XMODIFIERS, and build the SDL from official repo (https://hg.libsdl.org/SDL/), be sure installed the fcitx dev headers. And replace the dota2 one, setting **SDL_IM_MODULE=fcitx**, it works for me. (Can type Chinese using fcitx without thoese problems). :)

**Comment by gdrewb-valve** [comment] 2016-10-13 20:43
I believe the update on Oct. 12 contained full support for fcitx. Can people comment on whether things are still broken or not?

**Comment by timxx** [comment] 2016-10-14 11:22
@gdrewb-valve 
I can confirm that it works both with or without **XMODIFIERS=@im=fcitx**.  (**SDL_IM_MODULE=fcitx** also enabled fcitx, I think you already updated to the latest SDL :+1: )

It's nice if you fix the problem that the candidate window is not following the chat intput box of dota 2. :)

**Comment by gdrewb-valve** [comment] 2016-12-22 16:57
The 7.00 HUD updates should have affected things some, are there still active issues here?

**Comment by gdrewb-valve** [comment] 2017-01-02 01:10
Closing pending confirmation that there are still problems.

**Closed as completed by gdrewb-valve** 2017-01-02 01:10 UTC
Labels: reviewed
