### ISSUE TITLE
[Linux] Game eventually crashes when spectating Captains Mode draft from DOTATV

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1073] opened 2016-11-12 04:38 UTC
It's been months that this error keeps appearing. Some days more frequently than others.
Currently under ubuntu 16.10, Gnome 3.22, NVidia 1080 with 370.28 drivers.
I don't have much information to give other than that it happens when spectating a tournament match while game is already in the draft and on Captains Mode. I wouldn't discard it happening while game is loading before the draft screen tho.

It is 100% reproductible ONCE it happens for the first time for that given game. Cpu load is far from loaded, always sitting around 30%. Dota video settings is all on max with v-sync off.

It doesn't matter any cosmetic about terrain or weather.

Doesn't matter if Vulkan or GL. Neither the Graphics driver version (tested under 368, 370, 375).
Also tried a couple o kernel versions and happens on all. (4.4 - 4.8).

I always experience this while co-casting from DotaTV. When on a caster slot inside lobby it is totally fine. So strictly to DotaTV, be it a ticket game or not.

[18501.081317] VKRenderThread[1145]: segfault at 88 ip 00007f34fe8dae5d sp 00007f35050398f0 error 4 in libscaleformui_4_vulkan.so[7f34fe26d000+b04000]
[18541.059219] traps: GLRenderThread[17087] general protection ip:7fa0429d1bd6 sp:7fa048019750 error:0 in libscaleformui_4_gl.so[7fa0423f9000+a03000]
[18588.599505] VKRenderThread[18912]: segfault at 88 ip 00007f2799b39e5d sp 00007f27a02988f0 error 4 in libscaleformui_4_vulkan.so[7f27994cc000+b04000]

System info with CrashID from today -> https://gist.github.com/admshao/b3c1b60add3e2b4b29bedb77b875a7ac

Console.log from past couple of months or so including crashs from today and bunch of other days -> 
https://gist.github.com/admshao/d1a09887521d07432f32a4b119b10c49

**Comment by gdrewb-valve** [comment] 2016-11-12 06:40
Duplicate of #922.

**Closed as completed by gdrewb-valve** 2016-11-12 06:40 UTC
