### ISSUE TITLE
[REBORN][Linux] Ingame interface does not work

### ISSUE THREAD

**Issue by Korobochka** [ValveSoftware/Dota-2#1791] opened 2015-06-23 20:44 UTC
Please see the uploaded screenshot.
http://steamcommunity.com/sharedfiles/filedetails/?id=467728249

Interface seems to be very broken, making game unplayable.
This is a regular Dota 2 map, Solo Play with bots.
Linux Mint 17.1, Intel(R) Core(TM) i5-3570K, 16GB RAM, NVIDIA proprietary driver 331.113 on GeForce GTX 650 Ti.

**Comment by kcazyz** [comment] 2015-06-24 03:22
I have the same problem, exactly. 

My stats are:
Linux Mint 17.1, Intel(R) Core(TM) i7-4710HQ, 8GB RAM, NVIDIA proprietary driver 331.113 on GeForce GTX 860M

**Comment by Densaugeo** [comment] 2015-06-24 03:47
I'm having the same issue in lobby (haven't tried to start a game yet). I'm on Fedora 21, open source radeon driver, Radeon HD 7850 GPU.

Here's my terminal output from starting steam and going directly to the reborn beta:

~~~
[lunariel@morpheus ~]$ steam
Running Steam on fedora 21 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
[0623/234113:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433414140)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)

** (steam:24832): WARNING **: Unknown device type 14

** (steam:24832): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:24832): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:24832): WARNING **: Unknown device type 13

** (steam:24832): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/2: unknown object type

** (steam:24832): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:24832): WARNING **: Unknown device type 14

** (steam:24832): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type

** (steam:24832): WARNING **: Unknown device type 13

** (steam:24832): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/2: unknown object type

** (steam:24832): WARNING **: Unknown device type 14

** (steam:24832): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type
Installing breakpad exception handler for appid(steam)/version(1433441724)

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Ignoring invalid property 'address-labels'

** (steam:24832): WARNING **: Unknown setting 'bridge'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/1 settings: (3) type

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Unknown setting 'generic'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/2 settings: (3) type

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Unknown setting 'generic'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Unknown setting 'generic'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/4 settings: (3) type

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Unknown setting 'generic'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/5 settings: (3) type

** (steam:24832): WARNING **: Ignoring invalid property 'interface-name'

** (steam:24832): WARNING **: Unknown setting 'generic'

** (steam:24832): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/6 settings: (3) type
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB

(steam:24832): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(steam:24832): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Adding licenses for the following package(s): 0, 1259, 2833, 17207, 18914, 19009, 21357, 25544, 26750, 28187, 28539, 28832, 29136, 43922, 48900, 49307, 53153, 53194, 53329, 53345, 69835, 70012
roaming config store loaded successfully - 823 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1433441724)
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/lunariel/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1433441724)
System startup time: 3.94 seconds
[0623/234117:ERROR:renderer_main.cc(212)] Running without renderer sandbox
Running Steam on fedora 21 64-bit
STEAM_RUNTIME has been set by the user to: /home/lunariel/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 70: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 71: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 72: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 73: 32x256, total string texture memory is 540.67 KB
ExecCommandLine: "/home/lunariel/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Installing breakpad exception handler for appid(steam)/version(1433441724)
Generating new string page texture 119: 128x256, total string texture memory is 671.74 KB
Generating new string page texture 120: 384x256, total string texture memory is 1.06 MB
Generating new string page texture 121: 24x256, total string texture memory is 1.09 MB
Game update: AppID 570 "Dota 2", ProcID 24982, IP 0.0.0.0:0
ERROR: ld.so: object '/home/lunariel/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lunariel/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24984 != 24983, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/lunariel/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lunariel/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198017080813 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198017080813
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20150604103636)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Fontconfig warning: "/home/lunariel/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/lunariel/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
~~~

**Comment by Densaugeo** [comment] 2015-06-24 04:14
Reposted in https://github.com/ValveSoftware/Dota-2-Reborn/issues/43

**Comment by Korobochka** [comment] 2015-06-24 09:34
@Densaugeo, thank you. I didn't know about that repository.
I guess this issue can be aborted then.

**Comment by gdrewb-valve** [comment] 2015-06-24 23:41
Closing in favor of the Reborn repo.

**Closed** 2015-06-24 23:41 UTC

**Comment by kcazyz** [comment] 2015-06-25 02:30
I think this should be reopened as it is not the same issue as in the other case. My issue was not fixed by the update, and as someone there pointed out the 3d is rendering for me, the issue is the HUD. Thanks!

**Comment by gdrewb-valve** [comment] 2015-06-25 02:36
@kcazyz, I meant "the Reborn repo" in the general sense, not just item 43, as this is the regular non-Reborn repo and Reborn issues should go in the Reborn repo.  Also there are a number of rendering issue bugs there.  The one in particular I was thinking of was that updating to the 352 drivers fixed graphics problems that people were having with 331, but whether or not that would help you I don't know.

If you go through the other issues and don't find anything go ahead and open your own issue in the Reborn repo.

**Comment by kcazyz** [comment] 2015-06-25 02:37
Oh I see, thank you very much!

**Comment by kcazyz** [comment] 2015-06-25 03:01
Yup upgrading to 352 worked for me, thanks again!
