### ISSUE TITLE
[radeon tahiti xt] in-game visual glitches

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#161] opened 2015-06-28 18:40 UTC
On a state of the art 3D stack, linux/mesa from git,
in a match, reborn has so many visual glitches (textures
shadows), it cannot be played reasonably.

**Comment by gdrewb-valve** [comment] 2015-06-28 18:48
Can you post your full system specs and console text when running Reborn?

**Comment by sylware** [comment] 2015-06-28 21:21
steam log (I had to kill the bigpicture client at the end of the session):
http://pastebin.ca/3039841
Dmesg with the system info:
http://pastebin.ca/3039843
xserver/mesa/llvm... are straight from git (2 days ago)

**Comment by gdrewb-valve** [comment] 2015-06-28 23:08
There's nothing unusual in the two logs so that doesn't pin things down.  Did you exit the app or did it exit on its own?

**Comment by Tele42** [comment] 2015-06-28 23:12
@sylware Are you running mesa newer than http://cgit.freedesktop.org/mesa/mesa/commit/?id=7e5064360c03b8dbdd60298b46e1595418c6cea3 (this came out 2 days ago and I'm told is used by Source 2)?

**Comment by sylware** [comment] 2015-06-29 12:24
@gdrewb-valve I did exit reborn (I had to kill the bigpicture steam client though, it was "stuck" once I exited).
@Tele42, got mesa from today git with the mentioned patch, still the same (some texture glitches, and tons of what seems fog/shadow glitches)

**Comment by sylware** [comment] 2015-07-01 14:30
My bug is a duplicate of bug #150

**Comment by danginsburg** [comment] 2015-07-01 16:26
Closing as duplicate of #150 so we can track in one place.

**Closed as completed by danginsburg** 2015-07-01 16:26 UTC
Labels: duplicate, reviewed
